(test
 (name translation_smoke)
 (libraries frontend util spec2maude_translate)
 (deps (glob_files ../spectec/wasm-3.0/*.spectec))
 (action (run %{test} %{workspace_root}/spectec/wasm-3.0)))

(rule
 (alias runtest)
 (deps
  maude_load.sh
  ../translator/backend/semantics.maude
  ../translator/backend/builtins.maude
  ../translator/backend/relation-backends.maude
  (glob_files ../translator/backend/spectec-support/*.maude)
  ../translator/generated/output.maude)
 (action (run bash %{dep:maude_load.sh} %{workspace_root})))
