let helper_decls ~has_float_sign ~has_float_rep ~has_float_exact =
    (if has_float_sign || has_float_rep || has_float_exact then
      [ ""
      ; "  --- Implemented builtin family: structural floating-point representation/sign operations."
      ; "  vars FS_N FS_M : Nat ."
      ; "  var FS_E : Int ."
      ; "  vars FS_MAG FS_MAG2 : SpectecTerminal ."
      ; "  op builtin.fnmag-valid : Nat SpectecTerminal -> Bool ."
      ; "  ceq builtin.fnmag-valid(FS_N, fNmag.norm__(FS_M, FS_E)) = true"
      ; "    if _and_(_<_(FS_M, _^_(2, defm(FS_N))),"
      ; "            _and_(_<=_(_+_(2, - _^_(2, _-_(defe(FS_N), 1))), FS_E),"
      ; "                  _<=_(FS_E, _-_(_^_(2, _-_(defe(FS_N), 1)), 1)))) = true ."
      ; "  ceq builtin.fnmag-valid(FS_N, fNmag.subnorm_(FS_M)) = true"
      ; "    if _<_(FS_M, _^_(2, defm(FS_N))) ."
      ; "  eq builtin.fnmag-valid(FS_N, fNmag.inf) = true ."
      ; "  ceq builtin.fnmag-valid(FS_N, fNmag.nan_(FS_M)) = true"
      ; "    if _and_(_<=_(1, FS_M), _<_(FS_M, _^_(2, defm(FS_N)))) = true ."
      ]
    else
      [])
    @
    (if has_float_exact then
      [ ""
      ; "  --- Implemented builtin family: exact finite floating-point rational model."
      ; "  vars FI_M FI_N FI_FRAC FI_RESULT : Nat ."
      ; "  vars FC_N FC_M FC_BIT : Nat ."
      ; "  vars FR_N FR_I FR_E FR_FRAC : Nat ."
      ; "  vars FR_SHIFT FR_SCALE FR_Q FR_REM FR_HALF FR_SIG : Nat ."
      ; "  vars FD_N FD_Q : Nat ."
      ; "  vars FP_M FP_SHIFTED : Nat ."
      ; "  vars SQ_N SQ_LO SQ_HI SQ_MID SQ_Q : Nat ."
      ; "  var FI_E : Int ."
      ; "  var FP_E : Int ."
      ; "  vars FD_E FD_EMIN FD_EMAX : Int ."
      ; "  vars SQ_E SQ_EMIN SQ_EMAX : Int ."
      ; "  vars FC_R1 FC_R2 : Rat ."
      ; "  var FR_R : Rat ."
      ; "  var FI_R : Rat ."
      ; "  var FD_R : Rat ."
      ; "  var SQ_R : Rat ."
      ; "  var FI_X : Int ."
      ; "  vars FR_X FR_FLOOR FR_CEIL : Int ."
      ; "  vars FI_F FI_MAG : SpectecTerminal ."
      ; "  vars FC_F1 FC_F2 FC_MAG FC_MAG2 : SpectecTerminal ."
      ; "  vars FR_SOURCE FR_MAG : SpectecTerminal ."
      ; "  op builtin.pow2-rat : Nat -> Rat ."
      ; "  op builtin.scale-rat : Rat Int -> Rat ."
      ; "  op builtin.fmag-rat : Nat SpectecTerminal -> Rat ."
      ; "  op builtin.float-rat : Nat SpectecTerminal -> Rat ."
      ; "  op builtin.float-finite : Nat SpectecTerminal -> Bool ."
      ; "  op builtin.trunc-rat-int : Rat -> Int ."
      ; "  op builtin.nearest-rat-int : Rat -> Int ."
      ; "  op builtin.floor-log2-aux : Nat Nat -> Nat ."
      ; "  op builtin.floor-log2 : Nat -> Nat ."
      ; "  op builtin.floor-log2-rat-aux : Rat Int -> Int ."
      ; "  op builtin.floor-log2-rat : Rat -> Int ."
      ; "  op builtin.nat-fmag-exact : Nat Nat -> Bool ."
      ; "  op builtin.nat-to-fmag : Nat Nat -> SpectecTerminal ."
      ; "  op builtin.round-nat-significand : Nat Nat -> Nat ."
      ; "  op builtin.rounded-nat-to-fmag : Nat Nat -> SpectecTerminal ."
      ; "  op builtin.round-rat-subnormal : Nat Rat -> SpectecTerminal ."
      ; "  op builtin.round-rat-normal : Nat Rat Int -> SpectecTerminal ."
      ; "  op builtin.round-rat-to-fmag : Nat Rat -> SpectecTerminal ."
      ; "  op builtin.floor-half-int : Int -> Int ."
      ; "  op builtin.floor-sqrt-rat-range : Rat Nat Nat -> Nat ."
      ; "  op builtin.nearest-sqrt-rat-int : Rat Nat -> Nat ."
      ; "  op builtin.sqrt-rat-subnormal : Nat Rat -> SpectecTerminal ."
      ; "  op builtin.sqrt-rat-normal : Nat Rat Int -> SpectecTerminal ."
      ; "  op builtin.sqrt-rat-to-fmag : Nat Rat -> SpectecTerminal ."
      ; "  op builtin.sqrt-fmag : Nat SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.int-to-float-like : Nat Int SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.int-to-iN : Nat Int -> Nat ."
      ; "  op builtin.saturate-u-int : Nat Int -> Nat ."
      ; "  op builtin.saturate-s-int : Nat Int -> Nat ."
      ; "  op builtin.bit-not : Nat -> Nat ."
      ; "  op builtin.bit-and : Nat Nat -> Nat ."
      ; "  op builtin.bit-or : Nat Nat -> Nat ."
      ; "  op builtin.bit-xor : Nat Nat -> Nat ."
      ; "  op builtin.float-nan-bit : Nat SpectecTerminal -> Nat ."
      ; "  op builtin.float-sign-bit : Nat SpectecTerminal -> Nat ."
      ; "  op builtin.float-eq-bit : Nat SpectecTerminal SpectecTerminal -> Nat ."
      ; "  op builtin.float-lt-bit : Nat SpectecTerminal SpectecTerminal -> Nat ."
      ; "  op builtin.float-default-nan : Nat -> SpectecTerminal ."
      ; "  op builtin.float-canonical-nan : Nat SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.float-binary-nan : Nat SpectecTerminal SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.float-neg : Nat SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.rat-to-float-nearest : Nat Rat -> SpectecTerminal ."
      ; "  op builtin.rat-to-float-nearest-signed-zero : Nat Nat Rat -> SpectecTerminal ."
      ; "  op builtin.float-signed-zero : Nat -> SpectecTerminal ."
      ; "  op builtin.float-signed-inf : Nat -> SpectecTerminal ."
      ; "  op builtin.float-add-result : Nat SpectecTerminal SpectecTerminal Rat -> SpectecTerminal ."
      ; "  op builtin.float-min-equal : Nat SpectecTerminal SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.float-max-equal : Nat SpectecTerminal SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.float-min : Nat SpectecTerminal SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.float-max : Nat SpectecTerminal SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.float-pmin : Nat SpectecTerminal SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.float-pmax : Nat SpectecTerminal SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.promote-f32-normal-frac : Nat -> Nat ."
      ; "  op builtin.promote-f32-subnorm-frac : Nat -> Nat ."
      ; "  op builtin.promote-f32-subnorm-exp : Nat -> Int ."
      ; "  op builtin.promote-f32-nan-shift : Nat -> Nat ."
      ; "  op builtin.promote-f32-nan-payload : Nat -> Nat ."
      ; "  op builtin.promote-f32 : SpectecTerminal -> SpectecTerminal ."
      ; "  op builtin.demote-f64-nan-shift : Nat -> Nat ."
      ; "  op builtin.demote-f64-nan-payload : Nat -> Nat ."
      ; "  op builtin.demote-f64 : SpectecTerminal -> SpectecTerminal ."
      ; "  eq builtin.pow2-rat(0) = 1 ."
      ; "  ceq builtin.pow2-rat(FI_N) = _*_(2, builtin.pow2-rat(_-_(FI_N, 1)))"
      ; "    if _>_(FI_N, 0) ."
      ; "  ceq builtin.scale-rat(FI_R, FI_E) = _*_(FI_R, builtin.pow2-rat(abs(FI_E)))"
      ; "    if _>=_(FI_E, 0) ."
      ; "  ceq builtin.scale-rat(FI_R, FI_E) = FI_R / builtin.pow2-rat(abs(FI_E))"
      ; "    if _<_(FI_E, 0) ."
      ; "  ceq builtin.fmag-rat(FI_N, fNmag.norm__(FI_FRAC, FI_E)) ="
      ; "      builtin.scale-rat(_/_( _+_(_^_(2, defm(FI_N)), FI_FRAC), builtin.pow2-rat(defm(FI_N))), FI_E)"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.norm__(FI_FRAC, FI_E))) = true ."
      ; "  ceq builtin.fmag-rat(FI_N, fNmag.subnorm_(FI_FRAC)) ="
      ; "      builtin.scale-rat(_/_(FI_FRAC, builtin.pow2-rat(defm(FI_N))), _+_(2, - _^_(2, _-_(defe(FI_N), 1))))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.subnorm_(FI_FRAC))) = true ."
      ; "  ceq builtin.float-rat(FI_N, fN.pos_(FI_MAG)) = builtin.fmag-rat(FI_N, FI_MAG)"
      ; "    if (builtin.fnmag-valid(FI_N, FI_MAG)) = true ."
      ; "  ceq builtin.float-rat(FI_N, fN.neg_(FI_MAG)) = - builtin.fmag-rat(FI_N, FI_MAG)"
      ; "    if (builtin.fnmag-valid(FI_N, FI_MAG)) = true ."
      ; "  ceq builtin.float-finite(FI_N, fN.pos_(fNmag.norm__(FI_FRAC, FI_E))) = true"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.norm__(FI_FRAC, FI_E))) = true ."
      ; "  ceq builtin.float-finite(FI_N, fN.neg_(fNmag.norm__(FI_FRAC, FI_E))) = true"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.norm__(FI_FRAC, FI_E))) = true ."
      ; "  ceq builtin.float-finite(FI_N, fN.pos_(fNmag.subnorm_(FI_FRAC))) = true"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.subnorm_(FI_FRAC))) = true ."
      ; "  ceq builtin.float-finite(FI_N, fN.neg_(fNmag.subnorm_(FI_FRAC))) = true"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.subnorm_(FI_FRAC))) = true ."
      ; "  ceq builtin.float-nan-bit(FC_N, fN.pos_(fNmag.nan_(FC_M))) = 1"
      ; "    if (builtin.fnmag-valid(FC_N, fNmag.nan_(FC_M))) = true ."
      ; "  ceq builtin.float-nan-bit(FC_N, fN.neg_(fNmag.nan_(FC_M))) = 1"
      ; "    if (builtin.fnmag-valid(FC_N, fNmag.nan_(FC_M))) = true ."
      ; "  ceq builtin.float-nan-bit(FC_N, FC_F1) = 0"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  eq builtin.float-nan-bit(FC_N, fN.pos_(fNmag.inf)) = 0 ."
      ; "  eq builtin.float-nan-bit(FC_N, fN.neg_(fNmag.inf)) = 0 ."
      ; "  eq builtin.bit-not(0) = 1 ."
      ; "  eq builtin.bit-not(1) = 0 ."
      ; "  eq builtin.bit-and(0, FC_BIT) = 0 ."
      ; "  eq builtin.bit-and(FC_BIT, 0) = 0 ."
      ; "  eq builtin.bit-and(1, 1) = 1 ."
      ; "  eq builtin.bit-or(1, FC_BIT) = 1 ."
      ; "  eq builtin.bit-or(FC_BIT, 1) = 1 ."
      ; "  eq builtin.bit-or(0, 0) = 0 ."
      ; "  eq builtin.bit-xor(0, 0) = 0 ."
      ; "  eq builtin.bit-xor(0, 1) = 1 ."
      ; "  eq builtin.bit-xor(1, 0) = 1 ."
      ; "  eq builtin.bit-xor(1, 1) = 0 ."
      ; "  ceq builtin.float-sign-bit(FC_N, fN.pos_(FC_MAG)) = 0"
      ; "    if (builtin.fnmag-valid(FC_N, FC_MAG)) = true ."
      ; "  ceq builtin.float-sign-bit(FC_N, fN.neg_(FC_MAG)) = 1"
      ; "    if (builtin.fnmag-valid(FC_N, FC_MAG)) = true ."
      ; "  ceq builtin.float-eq-bit(FC_N, FC_F1, FC_F2) = 0"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 1 ."
      ; "  ceq builtin.float-eq-bit(FC_N, FC_F1, FC_F2) = 0"
      ; "    if builtin.float-nan-bit(FC_N, FC_F2) = 1 ."
      ; "  ceq builtin.float-eq-bit(FC_N, FC_F1, FC_F2) = defbool(bool(_==_(FC_R1, FC_R2)))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ (builtin.float-finite(FC_N, FC_F2)) = true"
      ; "       /\\ FC_R1 := builtin.float-rat(FC_N, FC_F1)"
      ; "       /\\ FC_R2 := builtin.float-rat(FC_N, FC_F2) ."
      ; "  eq builtin.float-eq-bit(FC_N, fN.pos_(fNmag.inf), fN.pos_(fNmag.inf)) = 1 ."
      ; "  eq builtin.float-eq-bit(FC_N, fN.neg_(fNmag.inf), fN.neg_(fNmag.inf)) = 1 ."
      ; "  eq builtin.float-eq-bit(FC_N, fN.pos_(fNmag.inf), fN.neg_(fNmag.inf)) = 0 ."
      ; "  eq builtin.float-eq-bit(FC_N, fN.neg_(fNmag.inf), fN.pos_(fNmag.inf)) = 0 ."
      ; "  ceq builtin.float-eq-bit(FC_N, FC_F1, fN.pos_(fNmag.inf)) = 0"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq builtin.float-eq-bit(FC_N, FC_F1, fN.neg_(fNmag.inf)) = 0"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq builtin.float-eq-bit(FC_N, fN.pos_(fNmag.inf), FC_F1) = 0"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq builtin.float-eq-bit(FC_N, fN.neg_(fNmag.inf), FC_F1) = 0"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq builtin.float-lt-bit(FC_N, FC_F1, FC_F2) = 0"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 1 ."
      ; "  ceq builtin.float-lt-bit(FC_N, FC_F1, FC_F2) = 0"
      ; "    if builtin.float-nan-bit(FC_N, FC_F2) = 1 ."
      ; "  ceq builtin.float-lt-bit(FC_N, FC_F1, FC_F2) = defbool(bool(_<_(FC_R1, FC_R2)))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ (builtin.float-finite(FC_N, FC_F2)) = true"
      ; "       /\\ FC_R1 := builtin.float-rat(FC_N, FC_F1)"
      ; "       /\\ FC_R2 := builtin.float-rat(FC_N, FC_F2) ."
      ; "  eq builtin.float-lt-bit(FC_N, fN.neg_(fNmag.inf), fN.pos_(fNmag.inf)) = 1 ."
      ; "  eq builtin.float-lt-bit(FC_N, fN.pos_(fNmag.inf), fN.neg_(fNmag.inf)) = 0 ."
      ; "  eq builtin.float-lt-bit(FC_N, fN.pos_(fNmag.inf), fN.pos_(fNmag.inf)) = 0 ."
      ; "  eq builtin.float-lt-bit(FC_N, fN.neg_(fNmag.inf), fN.neg_(fNmag.inf)) = 0 ."
      ; "  ceq builtin.float-lt-bit(FC_N, fN.neg_(fNmag.inf), FC_F1) = 1"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq builtin.float-lt-bit(FC_N, fN.pos_(fNmag.inf), FC_F1) = 0"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq builtin.float-lt-bit(FC_N, FC_F1, fN.pos_(fNmag.inf)) = 1"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq builtin.float-lt-bit(FC_N, FC_F1, fN.neg_(fNmag.inf)) = 0"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  eq builtin.float-default-nan(FC_N) = fN.pos_(fNmag.nan_(_^_(2, _-_(defm(FC_N), 1)))) ."
      ; "  ceq builtin.float-canonical-nan(FC_N, fN.pos_(fNmag.nan_(FC_M))) = fN.pos_(fNmag.nan_(FC_M))"
      ; "    if (builtin.fnmag-valid(FC_N, fNmag.nan_(FC_M))) = true"
      ; "       /\\ _>=_(FC_M, _^_(2, _-_(defm(FC_N), 1))) ."
      ; "  ceq builtin.float-canonical-nan(FC_N, fN.pos_(fNmag.nan_(FC_M))) = fN.pos_(fNmag.nan_(_+_(FC_M, _^_(2, _-_(defm(FC_N), 1)))))"
      ; "    if (builtin.fnmag-valid(FC_N, fNmag.nan_(FC_M))) = true"
      ; "       /\\ _<_(FC_M, _^_(2, _-_(defm(FC_N), 1))) ."
      ; "  ceq builtin.float-canonical-nan(FC_N, fN.neg_(fNmag.nan_(FC_M))) = fN.neg_(fNmag.nan_(FC_M))"
      ; "    if (builtin.fnmag-valid(FC_N, fNmag.nan_(FC_M))) = true"
      ; "       /\\ _>=_(FC_M, _^_(2, _-_(defm(FC_N), 1))) ."
      ; "  ceq builtin.float-canonical-nan(FC_N, fN.neg_(fNmag.nan_(FC_M))) = fN.neg_(fNmag.nan_(_+_(FC_M, _^_(2, _-_(defm(FC_N), 1)))))"
      ; "    if (builtin.fnmag-valid(FC_N, fNmag.nan_(FC_M))) = true"
      ; "       /\\ _<_(FC_M, _^_(2, _-_(defm(FC_N), 1))) ."
      ; "  ceq builtin.float-binary-nan(FC_N, fN.pos_(fNmag.nan_(FC_M)), FC_F2) ="
      ; "      builtin.float-canonical-nan(FC_N, fN.pos_(fNmag.nan_(FC_M)))"
      ; "    if (builtin.fnmag-valid(FC_N, fNmag.nan_(FC_M))) = true ."
      ; "  ceq builtin.float-binary-nan(FC_N, fN.neg_(fNmag.nan_(FC_M)), FC_F2) ="
      ; "      builtin.float-canonical-nan(FC_N, fN.neg_(fNmag.nan_(FC_M)))"
      ; "    if (builtin.fnmag-valid(FC_N, fNmag.nan_(FC_M))) = true ."
      ; "  ceq builtin.float-binary-nan(FC_N, FC_F1, fN.pos_(fNmag.nan_(FC_M))) ="
      ; "      builtin.float-canonical-nan(FC_N, fN.pos_(fNmag.nan_(FC_M)))"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 0"
      ; "       /\\ (builtin.fnmag-valid(FC_N, fNmag.nan_(FC_M))) = true ."
      ; "  ceq builtin.float-binary-nan(FC_N, FC_F1, fN.neg_(fNmag.nan_(FC_M))) ="
      ; "      builtin.float-canonical-nan(FC_N, fN.neg_(fNmag.nan_(FC_M)))"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 0"
      ; "       /\\ (builtin.fnmag-valid(FC_N, fNmag.nan_(FC_M))) = true ."
      ; "  ceq builtin.float-neg(FC_N, fN.pos_(FC_MAG)) = fN.neg_(FC_MAG)"
      ; "    if (builtin.fnmag-valid(FC_N, FC_MAG)) = true ."
      ; "  ceq builtin.float-neg(FC_N, fN.neg_(FC_MAG)) = fN.pos_(FC_MAG)"
      ; "    if (builtin.fnmag-valid(FC_N, FC_MAG)) = true ."
      ; "  ceq builtin.rat-to-float-nearest(FC_N, FR_R) = fN.pos_(builtin.round-rat-to-fmag(FC_N, FR_R))"
      ; "    if _>_(FR_R, 0) ."
      ; "  ceq builtin.rat-to-float-nearest(FC_N, FR_R) = fN.neg_(builtin.round-rat-to-fmag(FC_N, - FR_R))"
      ; "    if _<_(FR_R, 0) ."
      ; "  eq builtin.rat-to-float-nearest(FC_N, 0) = fN.pos_(fNmag.subnorm_(0)) ."
      ; "  eq builtin.float-signed-zero(0) = fN.pos_(fNmag.subnorm_(0)) ."
      ; "  eq builtin.float-signed-zero(1) = fN.neg_(fNmag.subnorm_(0)) ."
      ; "  eq builtin.float-signed-inf(0) = fN.pos_(fNmag.inf) ."
      ; "  eq builtin.float-signed-inf(1) = fN.neg_(fNmag.inf) ."
      ; "  ceq builtin.rat-to-float-nearest-signed-zero(FC_N, FC_BIT, FR_R) = builtin.rat-to-float-nearest(FC_N, FR_R)"
      ; "    if _=/=_(FR_R, 0) ."
      ; "  eq builtin.rat-to-float-nearest-signed-zero(FC_N, FC_BIT, 0) = builtin.float-signed-zero(FC_BIT) ."
      ; "  eq builtin.float-add-result(FC_N, fN.neg_(fNmag.subnorm_(0)), fN.neg_(fNmag.subnorm_(0)), 0) = fN.neg_(fNmag.subnorm_(0)) ."
      ; "  ceq builtin.float-add-result(FC_N, FC_F1, FC_F2, FR_R) = builtin.rat-to-float-nearest(FC_N, FR_R)"
      ; "    if _=/=_(FR_R, 0) ."
      ; "  ceq builtin.float-add-result(FC_N, FC_F1, FC_F2, 0) = fN.pos_(fNmag.subnorm_(0))"
      ; "    if _=/=_(FC_F1, fN.neg_(fNmag.subnorm_(0))) ."
      ; "  ceq builtin.float-add-result(FC_N, FC_F1, FC_F2, 0) = fN.pos_(fNmag.subnorm_(0))"
      ; "    if _=/=_(FC_F2, fN.neg_(fNmag.subnorm_(0))) ."
      ; "  ceq builtin.float-min-equal(FC_N, fN.neg_(FC_MAG), FC_F2) = fN.neg_(FC_MAG)"
      ; "    if (builtin.fnmag-valid(FC_N, FC_MAG)) = true"
      ; "       /\\ builtin.float-eq-bit(FC_N, fN.neg_(FC_MAG), FC_F2) = 1 ."
      ; "  ceq builtin.float-min-equal(FC_N, fN.pos_(FC_MAG), fN.neg_(FC_MAG2)) = fN.neg_(FC_MAG2)"
      ; "    if (builtin.fnmag-valid(FC_N, FC_MAG)) = true"
      ; "       /\\ (builtin.fnmag-valid(FC_N, FC_MAG2)) = true"
      ; "       /\\ builtin.float-eq-bit(FC_N, fN.pos_(FC_MAG), fN.neg_(FC_MAG2)) = 1 ."
      ; "  ceq builtin.float-min-equal(FC_N, fN.pos_(FC_MAG), fN.pos_(FC_MAG2)) = fN.pos_(FC_MAG)"
      ; "    if (builtin.fnmag-valid(FC_N, FC_MAG)) = true"
      ; "       /\\ (builtin.fnmag-valid(FC_N, FC_MAG2)) = true"
      ; "       /\\ builtin.float-eq-bit(FC_N, fN.pos_(FC_MAG), fN.pos_(FC_MAG2)) = 1 ."
      ; "  ceq builtin.float-max-equal(FC_N, fN.pos_(FC_MAG), FC_F2) = fN.pos_(FC_MAG)"
      ; "    if (builtin.fnmag-valid(FC_N, FC_MAG)) = true"
      ; "       /\\ builtin.float-eq-bit(FC_N, fN.pos_(FC_MAG), FC_F2) = 1 ."
      ; "  ceq builtin.float-max-equal(FC_N, fN.neg_(FC_MAG), fN.pos_(FC_MAG2)) = fN.pos_(FC_MAG2)"
      ; "    if (builtin.fnmag-valid(FC_N, FC_MAG)) = true"
      ; "       /\\ (builtin.fnmag-valid(FC_N, FC_MAG2)) = true"
      ; "       /\\ builtin.float-eq-bit(FC_N, fN.neg_(FC_MAG), fN.pos_(FC_MAG2)) = 1 ."
      ; "  ceq builtin.float-max-equal(FC_N, fN.neg_(FC_MAG), fN.neg_(FC_MAG2)) = fN.neg_(FC_MAG)"
      ; "    if (builtin.fnmag-valid(FC_N, FC_MAG)) = true"
      ; "       /\\ (builtin.fnmag-valid(FC_N, FC_MAG2)) = true"
      ; "       /\\ builtin.float-eq-bit(FC_N, fN.neg_(FC_MAG), fN.neg_(FC_MAG2)) = 1 ."
      ; "  ceq builtin.float-min(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 1 ."
      ; "  ceq builtin.float-min(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 0"
      ; "       /\\ builtin.float-nan-bit(FC_N, FC_F2) = 1 ."
      ; "  ceq builtin.float-min(FC_N, FC_F1, FC_F2) = builtin.float-min-equal(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-eq-bit(FC_N, FC_F1, FC_F2) = 1 ."
      ; "  ceq builtin.float-min(FC_N, FC_F1, FC_F2) = FC_F1"
      ; "    if builtin.float-lt-bit(FC_N, FC_F1, FC_F2) = 1 ."
      ; "  ceq builtin.float-min(FC_N, FC_F1, FC_F2) = FC_F2"
      ; "    if builtin.float-lt-bit(FC_N, FC_F2, FC_F1) = 1 ."
      ; "  ceq builtin.float-max(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 1 ."
      ; "  ceq builtin.float-max(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 0"
      ; "       /\\ builtin.float-nan-bit(FC_N, FC_F2) = 1 ."
      ; "  ceq builtin.float-max(FC_N, FC_F1, FC_F2) = builtin.float-max-equal(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-eq-bit(FC_N, FC_F1, FC_F2) = 1 ."
      ; "  ceq builtin.float-max(FC_N, FC_F1, FC_F2) = FC_F2"
      ; "    if builtin.float-lt-bit(FC_N, FC_F1, FC_F2) = 1 ."
      ; "  ceq builtin.float-max(FC_N, FC_F1, FC_F2) = FC_F1"
      ; "    if builtin.float-lt-bit(FC_N, FC_F2, FC_F1) = 1 ."
      ; "  ceq builtin.float-pmin(FC_N, FC_F1, FC_F2) = FC_F2"
      ; "    if builtin.float-lt-bit(FC_N, FC_F2, FC_F1) = 1 ."
      ; "  ceq builtin.float-pmin(FC_N, FC_F1, FC_F2) = FC_F1"
      ; "    if builtin.float-lt-bit(FC_N, FC_F2, FC_F1) = 0 ."
      ; "  ceq builtin.float-pmax(FC_N, FC_F1, FC_F2) = FC_F2"
      ; "    if builtin.float-lt-bit(FC_N, FC_F1, FC_F2) = 1 ."
      ; "  ceq builtin.float-pmax(FC_N, FC_F1, FC_F2) = FC_F1"
      ; "    if builtin.float-lt-bit(FC_N, FC_F1, FC_F2) = 0 ."
      ; "  ceq builtin.trunc-rat-int(FI_R) = floor(FI_R)"
      ; "    if _>=_(FI_R, 0) ."
      ; "  ceq builtin.trunc-rat-int(FI_R) = ceiling(FI_R)"
      ; "    if _<_(FI_R, 0) ."
      ; "  ceq builtin.nearest-rat-int(FR_R) = FR_CEIL"
      ; "    if FR_FLOOR := floor(FR_R)"
      ; "       /\\ FR_CEIL := ceiling(FR_R)"
      ; "       /\\ _<_( _-_(FR_CEIL, FR_R), _-_(FR_R, FR_FLOOR)) ."
      ; "  ceq builtin.nearest-rat-int(FR_R) = FR_CEIL"
      ; "    if FR_FLOOR := floor(FR_R)"
      ; "       /\\ FR_CEIL := ceiling(FR_R)"
      ; "       /\\ _==_( _-_(FR_CEIL, FR_R), _-_(FR_R, FR_FLOOR))"
      ; "       /\\ _rem_(abs(FR_CEIL), 2) = 0 ."
      ; "  ceq builtin.nearest-rat-int(FR_R) = FR_FLOOR"
      ; "    if FR_FLOOR := floor(FR_R)"
      ; "       /\\ FR_CEIL := ceiling(FR_R)"
      ; "       /\\ _>_( _-_(FR_CEIL, FR_R), _-_(FR_R, FR_FLOOR)) ."
      ; "  ceq builtin.nearest-rat-int(FR_R) = FR_FLOOR"
      ; "    if FR_FLOOR := floor(FR_R)"
      ; "       /\\ FR_CEIL := ceiling(FR_R)"
      ; "       /\\ _==_( _-_(FR_CEIL, FR_R), _-_(FR_R, FR_FLOOR))"
      ; "       /\\ _>_(_rem_(abs(FR_CEIL), 2), 0) ."
      ; "  ceq builtin.floor-log2-aux(FR_I, FR_E) = FR_E"
      ; "    if _<=_(_^_(2, FR_E), FR_I)"
      ; "       /\\ _<_(FR_I, _^_(2, _+_(FR_E, 1))) ."
      ; "  ceq builtin.floor-log2-aux(FR_I, FR_E) = builtin.floor-log2-aux(FR_I, _+_(FR_E, 1))"
      ; "    if _>=_(FR_I, _^_(2, _+_(FR_E, 1))) ."
      ; "  ceq builtin.floor-log2(FR_I) = builtin.floor-log2-aux(FR_I, 0)"
      ; "    if _>_(FR_I, 0) ."
      ; "  ceq builtin.floor-log2-rat-aux(FD_R, FD_E) = FD_E"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ _<=_(builtin.scale-rat(1, FD_E), FD_R)"
      ; "       /\\ _<_(FD_R, builtin.scale-rat(1, _+_(FD_E, 1))) ."
      ; "  ceq builtin.floor-log2-rat-aux(FD_R, FD_E) = builtin.floor-log2-rat-aux(FD_R, _-_(FD_E, 1))"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ _<_(FD_R, builtin.scale-rat(1, FD_E)) ."
      ; "  ceq builtin.floor-log2-rat-aux(FD_R, FD_E) = builtin.floor-log2-rat-aux(FD_R, _+_(FD_E, 1))"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ _>=_(FD_R, builtin.scale-rat(1, _+_(FD_E, 1))) ."
      ; "  ceq builtin.floor-log2-rat(FD_R) = builtin.floor-log2-rat-aux(FD_R, 0)"
      ; "    if _>_(FD_R, 0) ."
      ; "  ceq builtin.round-rat-subnormal(FD_N, FD_R) = fNmag.subnorm_(0)"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ FD_EMIN := _+_(2, - _^_(2, _-_(defe(FD_N), 1)))"
      ; "       /\\ FD_Q := builtin.nearest-rat-int(FD_R / builtin.scale-rat(1, _-_(FD_EMIN, defm(FD_N))))"
      ; "       /\\ FD_Q = 0 ."
      ; "  ceq builtin.round-rat-subnormal(FD_N, FD_R) = fNmag.subnorm_(FD_Q)"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ FD_EMIN := _+_(2, - _^_(2, _-_(defe(FD_N), 1)))"
      ; "       /\\ FD_Q := builtin.nearest-rat-int(FD_R / builtin.scale-rat(1, _-_(FD_EMIN, defm(FD_N))))"
      ; "       /\\ _>_(FD_Q, 0)"
      ; "       /\\ _<_(FD_Q, _^_(2, defm(FD_N))) ."
      ; "  ceq builtin.round-rat-subnormal(FD_N, FD_R) = fNmag.norm__(0, FD_EMIN)"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ FD_EMIN := _+_(2, - _^_(2, _-_(defe(FD_N), 1)))"
      ; "       /\\ FD_Q := builtin.nearest-rat-int(FD_R / builtin.scale-rat(1, _-_(FD_EMIN, defm(FD_N))))"
      ; "       /\\ FD_Q = _^_(2, defm(FD_N)) ."
      ; "  ceq builtin.round-rat-normal(FD_N, FD_R, FD_E) = fNmag.norm__(_-_(FD_Q, _^_(2, defm(FD_N))), FD_E)"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ FD_Q := builtin.nearest-rat-int(FD_R / builtin.scale-rat(1, _-_(FD_E, defm(FD_N))))"
      ; "       /\\ _<_(FD_Q, _^_(2, _+_(defm(FD_N), 1)))"
      ; "       /\\ (builtin.fnmag-valid(FD_N, fNmag.norm__(_-_(FD_Q, _^_(2, defm(FD_N))), FD_E))) = true ."
      ; "  ceq builtin.round-rat-normal(FD_N, FD_R, FD_E) = fNmag.norm__(0, _+_(FD_E, 1))"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ FD_EMAX := _-_(_^_(2, _-_(defe(FD_N), 1)), 1)"
      ; "       /\\ FD_Q := builtin.nearest-rat-int(FD_R / builtin.scale-rat(1, _-_(FD_E, defm(FD_N))))"
      ; "       /\\ FD_Q = _^_(2, _+_(defm(FD_N), 1))"
      ; "       /\\ _<_(FD_E, FD_EMAX)"
      ; "       /\\ (builtin.fnmag-valid(FD_N, fNmag.norm__(0, _+_(FD_E, 1)))) = true ."
      ; "  ceq builtin.round-rat-normal(FD_N, FD_R, FD_E) = fNmag.inf"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ FD_EMAX := _-_(_^_(2, _-_(defe(FD_N), 1)), 1)"
      ; "       /\\ FD_Q := builtin.nearest-rat-int(FD_R / builtin.scale-rat(1, _-_(FD_E, defm(FD_N))))"
      ; "       /\\ FD_Q = _^_(2, _+_(defm(FD_N), 1))"
      ; "       /\\ FD_E = FD_EMAX ."
      ; "  eq builtin.round-rat-to-fmag(FD_N, 0) = fNmag.subnorm_(0) ."
      ; "  ceq builtin.round-rat-to-fmag(FD_N, FD_R) = builtin.round-rat-subnormal(FD_N, FD_R)"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ FD_E := builtin.floor-log2-rat(FD_R)"
      ; "       /\\ FD_EMIN := _+_(2, - _^_(2, _-_(defe(FD_N), 1)))"
      ; "       /\\ _<_(FD_E, FD_EMIN) ."
      ; "  ceq builtin.round-rat-to-fmag(FD_N, FD_R) = builtin.round-rat-normal(FD_N, FD_R, FD_E)"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ FD_E := builtin.floor-log2-rat(FD_R)"
      ; "       /\\ FD_EMIN := _+_(2, - _^_(2, _-_(defe(FD_N), 1)))"
      ; "       /\\ FD_EMAX := _-_(_^_(2, _-_(defe(FD_N), 1)), 1)"
      ; "       /\\ _>=_(FD_E, FD_EMIN)"
      ; "       /\\ _<=_(FD_E, FD_EMAX) ."
      ; "  ceq builtin.round-rat-to-fmag(FD_N, FD_R) = fNmag.inf"
      ; "    if _>_(FD_R, 0)"
      ; "       /\\ FD_E := builtin.floor-log2-rat(FD_R)"
      ; "       /\\ FD_EMAX := _-_(_^_(2, _-_(defe(FD_N), 1)), 1)"
      ; "       /\\ _>_(FD_E, FD_EMAX) ."
      ; "  ceq builtin.floor-half-int(SQ_E) = _quo_(SQ_E, 2)"
      ; "    if _>=_(SQ_E, 0) ."
      ; "  ceq builtin.floor-half-int(SQ_E) = - _quo_(_+_(abs(SQ_E), 1), 2)"
      ; "    if _<_(SQ_E, 0) ."
      ; "  eq builtin.floor-sqrt-rat-range(SQ_R, SQ_LO, SQ_LO) = SQ_LO ."
      ; "  ceq builtin.floor-sqrt-rat-range(SQ_R, SQ_LO, SQ_HI) ="
      ; "      builtin.floor-sqrt-rat-range(SQ_R, SQ_MID, SQ_HI)"
      ; "    if _<_(SQ_LO, SQ_HI)"
      ; "       /\\ SQ_MID := _quo_(_+_(_+_(SQ_LO, SQ_HI), 1), 2)"
      ; "       /\\ _<=_(_*_(SQ_MID, SQ_MID), SQ_R) ."
      ; "  ceq builtin.floor-sqrt-rat-range(SQ_R, SQ_LO, SQ_HI) ="
      ; "      builtin.floor-sqrt-rat-range(SQ_R, SQ_LO, _-_(SQ_MID, 1))"
      ; "    if _<_(SQ_LO, SQ_HI)"
      ; "       /\\ SQ_MID := _quo_(_+_(_+_(SQ_LO, SQ_HI), 1), 2)"
      ; "       /\\ _>_(_*_(SQ_MID, SQ_MID), SQ_R) ."
      ; "  ceq builtin.nearest-sqrt-rat-int(SQ_R, SQ_HI) = SQ_Q"
      ; "    if _>=_(SQ_R, 0)"
      ; "       /\\ SQ_Q := builtin.floor-sqrt-rat-range(SQ_R, 0, SQ_HI)"
      ; "       /\\ _<_( _*_(4, SQ_R), _^_(_+_(_*_(2, SQ_Q), 1), 2)) ."
      ; "  ceq builtin.nearest-sqrt-rat-int(SQ_R, SQ_HI) = _+_(SQ_Q, 1)"
      ; "    if _>=_(SQ_R, 0)"
      ; "       /\\ SQ_Q := builtin.floor-sqrt-rat-range(SQ_R, 0, SQ_HI)"
      ; "       /\\ _>_( _*_(4, SQ_R), _^_(_+_(_*_(2, SQ_Q), 1), 2)) ."
      ; "  ceq builtin.nearest-sqrt-rat-int(SQ_R, SQ_HI) = SQ_Q"
      ; "    if _>=_(SQ_R, 0)"
      ; "       /\\ SQ_Q := builtin.floor-sqrt-rat-range(SQ_R, 0, SQ_HI)"
      ; "       /\\ _==_( _*_(4, SQ_R), _^_(_+_(_*_(2, SQ_Q), 1), 2))"
      ; "       /\\ _rem_(SQ_Q, 2) = 0 ."
      ; "  ceq builtin.nearest-sqrt-rat-int(SQ_R, SQ_HI) = _+_(SQ_Q, 1)"
      ; "    if _>=_(SQ_R, 0)"
      ; "       /\\ SQ_Q := builtin.floor-sqrt-rat-range(SQ_R, 0, SQ_HI)"
      ; "       /\\ _==_( _*_(4, SQ_R), _^_(_+_(_*_(2, SQ_Q), 1), 2))"
      ; "       /\\ _>_(_rem_(SQ_Q, 2), 0) ."
      ; "  ceq builtin.sqrt-rat-subnormal(SQ_N, SQ_R) = fNmag.subnorm_(0)"
      ; "    if _>_(SQ_R, 0)"
      ; "       /\\ SQ_EMIN := _+_(2, - _^_(2, _-_(defe(SQ_N), 1)))"
      ; "       /\\ SQ_Q := builtin.nearest-sqrt-rat-int(builtin.scale-rat(SQ_R, _*_(2, _-_(defm(SQ_N), SQ_EMIN))), _^_(2, defm(SQ_N)))"
      ; "       /\\ SQ_Q = 0 ."
      ; "  ceq builtin.sqrt-rat-subnormal(SQ_N, SQ_R) = fNmag.subnorm_(SQ_Q)"
      ; "    if _>_(SQ_R, 0)"
      ; "       /\\ SQ_EMIN := _+_(2, - _^_(2, _-_(defe(SQ_N), 1)))"
      ; "       /\\ SQ_Q := builtin.nearest-sqrt-rat-int(builtin.scale-rat(SQ_R, _*_(2, _-_(defm(SQ_N), SQ_EMIN))), _^_(2, defm(SQ_N)))"
      ; "       /\\ _>_(SQ_Q, 0)"
      ; "       /\\ _<_(SQ_Q, _^_(2, defm(SQ_N))) ."
      ; "  ceq builtin.sqrt-rat-subnormal(SQ_N, SQ_R) = fNmag.norm__(0, SQ_EMIN)"
      ; "    if _>_(SQ_R, 0)"
      ; "       /\\ SQ_EMIN := _+_(2, - _^_(2, _-_(defe(SQ_N), 1)))"
      ; "       /\\ SQ_Q := builtin.nearest-sqrt-rat-int(builtin.scale-rat(SQ_R, _*_(2, _-_(defm(SQ_N), SQ_EMIN))), _^_(2, defm(SQ_N)))"
      ; "       /\\ SQ_Q = _^_(2, defm(SQ_N)) ."
      ; "  ceq builtin.sqrt-rat-normal(SQ_N, SQ_R, SQ_E) = fNmag.norm__(_-_(SQ_Q, _^_(2, defm(SQ_N))), SQ_E)"
      ; "    if _>_(SQ_R, 0)"
      ; "       /\\ SQ_Q := builtin.nearest-sqrt-rat-int(builtin.scale-rat(SQ_R, _*_(2, _-_(defm(SQ_N), SQ_E))), _^_(2, _+_(defm(SQ_N), 1)))"
      ; "       /\\ _<_(SQ_Q, _^_(2, _+_(defm(SQ_N), 1)))"
      ; "       /\\ (builtin.fnmag-valid(SQ_N, fNmag.norm__(_-_(SQ_Q, _^_(2, defm(SQ_N))), SQ_E))) = true ."
      ; "  ceq builtin.sqrt-rat-normal(SQ_N, SQ_R, SQ_E) = fNmag.norm__(0, _+_(SQ_E, 1))"
      ; "    if _>_(SQ_R, 0)"
      ; "       /\\ SQ_EMAX := _-_(_^_(2, _-_(defe(SQ_N), 1)), 1)"
      ; "       /\\ SQ_Q := builtin.nearest-sqrt-rat-int(builtin.scale-rat(SQ_R, _*_(2, _-_(defm(SQ_N), SQ_E))), _^_(2, _+_(defm(SQ_N), 1)))"
      ; "       /\\ SQ_Q = _^_(2, _+_(defm(SQ_N), 1))"
      ; "       /\\ _<_(SQ_E, SQ_EMAX)"
      ; "       /\\ (builtin.fnmag-valid(SQ_N, fNmag.norm__(0, _+_(SQ_E, 1)))) = true ."
      ; "  ceq builtin.sqrt-rat-normal(SQ_N, SQ_R, SQ_E) = fNmag.inf"
      ; "    if _>_(SQ_R, 0)"
      ; "       /\\ SQ_EMAX := _-_(_^_(2, _-_(defe(SQ_N), 1)), 1)"
      ; "       /\\ SQ_Q := builtin.nearest-sqrt-rat-int(builtin.scale-rat(SQ_R, _*_(2, _-_(defm(SQ_N), SQ_E))), _^_(2, _+_(defm(SQ_N), 1)))"
      ; "       /\\ SQ_Q = _^_(2, _+_(defm(SQ_N), 1))"
      ; "       /\\ SQ_E = SQ_EMAX ."
      ; "  eq builtin.sqrt-rat-to-fmag(SQ_N, 0) = fNmag.subnorm_(0) ."
      ; "  ceq builtin.sqrt-rat-to-fmag(SQ_N, SQ_R) = builtin.sqrt-rat-subnormal(SQ_N, SQ_R)"
      ; "    if _>_(SQ_R, 0)"
      ; "       /\\ SQ_E := builtin.floor-half-int(builtin.floor-log2-rat(SQ_R))"
      ; "       /\\ SQ_EMIN := _+_(2, - _^_(2, _-_(defe(SQ_N), 1)))"
      ; "       /\\ _<_(SQ_E, SQ_EMIN) ."
      ; "  ceq builtin.sqrt-rat-to-fmag(SQ_N, SQ_R) = builtin.sqrt-rat-normal(SQ_N, SQ_R, SQ_E)"
      ; "    if _>_(SQ_R, 0)"
      ; "       /\\ SQ_E := builtin.floor-half-int(builtin.floor-log2-rat(SQ_R))"
      ; "       /\\ SQ_EMIN := _+_(2, - _^_(2, _-_(defe(SQ_N), 1)))"
      ; "       /\\ SQ_EMAX := _-_(_^_(2, _-_(defe(SQ_N), 1)), 1)"
      ; "       /\\ _>=_(SQ_E, SQ_EMIN)"
      ; "       /\\ _<=_(SQ_E, SQ_EMAX) ."
      ; "  ceq builtin.sqrt-rat-to-fmag(SQ_N, SQ_R) = fNmag.inf"
      ; "    if _>_(SQ_R, 0)"
      ; "       /\\ SQ_E := builtin.floor-half-int(builtin.floor-log2-rat(SQ_R))"
      ; "       /\\ SQ_EMAX := _-_(_^_(2, _-_(defe(SQ_N), 1)), 1)"
      ; "       /\\ _>_(SQ_E, SQ_EMAX) ."
      ; "  ceq builtin.sqrt-fmag(SQ_N, FI_MAG) = builtin.sqrt-rat-to-fmag(SQ_N, builtin.fmag-rat(SQ_N, FI_MAG))"
      ; "    if (builtin.float-finite(SQ_N, fN.pos_(FI_MAG))) = true ."
      ; "  eq builtin.promote-f32-normal-frac(FP_M) ="
      ; "      _*_(FP_M, _^_(2, _-_(defm(64), defm(32)))) ."
      ; "  ceq builtin.promote-f32-subnorm-frac(FP_M) ="
      ; "      _-_(_*_(FP_M, _^_(2, _-_(defm(64), builtin.floor-log2(FP_M)))), _^_(2, defm(64)))"
      ; "    if _>_(FP_M, 0) ."
      ; "  ceq builtin.promote-f32-subnorm-exp(FP_M) ="
      ; "      _+_(builtin.floor-log2(FP_M), _+_(_+_(2, - _^_(2, _-_(defe(32), 1))), - defm(32)))"
      ; "    if _>_(FP_M, 0) ."
      ; "  eq builtin.promote-f32-nan-shift(FP_M) ="
      ; "      _*_(FP_M, _^_(2, _-_(defm(64), defm(32)))) ."
      ; "  ceq builtin.promote-f32-nan-payload(FP_M) = builtin.promote-f32-nan-shift(FP_M)"
      ; "    if _>=_(builtin.promote-f32-nan-shift(FP_M), _^_(2, _-_(defm(64), 1))) ."
      ; "  ceq builtin.promote-f32-nan-payload(FP_M) ="
      ; "      _+_(builtin.promote-f32-nan-shift(FP_M), _^_(2, _-_(defm(64), 1)))"
      ; "    if _<_(builtin.promote-f32-nan-shift(FP_M), _^_(2, _-_(defm(64), 1))) ."
      ; "  ceq builtin.promote-f32(fN.pos_(fNmag.norm__(FP_M, FP_E))) ="
      ; "      fN.pos_(fNmag.norm__(builtin.promote-f32-normal-frac(FP_M), FP_E))"
      ; "    if (builtin.fnmag-valid(32, fNmag.norm__(FP_M, FP_E))) = true ."
      ; "  ceq builtin.promote-f32(fN.neg_(fNmag.norm__(FP_M, FP_E))) ="
      ; "      fN.neg_(fNmag.norm__(builtin.promote-f32-normal-frac(FP_M), FP_E))"
      ; "    if (builtin.fnmag-valid(32, fNmag.norm__(FP_M, FP_E))) = true ."
      ; "  eq builtin.promote-f32(fN.pos_(fNmag.subnorm_(0))) = fN.pos_(fNmag.subnorm_(0)) ."
      ; "  eq builtin.promote-f32(fN.neg_(fNmag.subnorm_(0))) = fN.neg_(fNmag.subnorm_(0)) ."
      ; "  ceq builtin.promote-f32(fN.pos_(fNmag.subnorm_(FP_M))) ="
      ; "      fN.pos_(fNmag.norm__(builtin.promote-f32-subnorm-frac(FP_M), builtin.promote-f32-subnorm-exp(FP_M)))"
      ; "    if _>_(FP_M, 0)"
      ; "       /\\ (builtin.fnmag-valid(32, fNmag.subnorm_(FP_M))) = true ."
      ; "  ceq builtin.promote-f32(fN.neg_(fNmag.subnorm_(FP_M))) ="
      ; "      fN.neg_(fNmag.norm__(builtin.promote-f32-subnorm-frac(FP_M), builtin.promote-f32-subnorm-exp(FP_M)))"
      ; "    if _>_(FP_M, 0)"
      ; "       /\\ (builtin.fnmag-valid(32, fNmag.subnorm_(FP_M))) = true ."
      ; "  eq builtin.promote-f32(fN.pos_(fNmag.inf)) = fN.pos_(fNmag.inf) ."
      ; "  eq builtin.promote-f32(fN.neg_(fNmag.inf)) = fN.neg_(fNmag.inf) ."
      ; "  ceq builtin.promote-f32(fN.pos_(fNmag.nan_(FP_M))) ="
      ; "      fN.pos_(fNmag.nan_(builtin.promote-f32-nan-payload(FP_M)))"
      ; "    if (builtin.fnmag-valid(32, fNmag.nan_(FP_M))) = true ."
      ; "  ceq builtin.promote-f32(fN.neg_(fNmag.nan_(FP_M))) ="
      ; "      fN.neg_(fNmag.nan_(builtin.promote-f32-nan-payload(FP_M)))"
      ; "    if (builtin.fnmag-valid(32, fNmag.nan_(FP_M))) = true ."
      ; "  eq builtin.demote-f64-nan-shift(FP_M) ="
      ; "      _quo_(FP_M, _^_(2, _-_(defm(64), defm(32)))) ."
      ; "  ceq builtin.demote-f64-nan-payload(FP_M) = builtin.demote-f64-nan-shift(FP_M)"
      ; "    if _>=_(builtin.demote-f64-nan-shift(FP_M), _^_(2, _-_(defm(32), 1))) ."
      ; "  ceq builtin.demote-f64-nan-payload(FP_M) ="
      ; "      _+_(builtin.demote-f64-nan-shift(FP_M), _^_(2, _-_(defm(32), 1)))"
      ; "    if _<_(builtin.demote-f64-nan-shift(FP_M), _^_(2, _-_(defm(32), 1))) ."
      ; "  ceq builtin.demote-f64(fN.pos_(FI_MAG)) ="
      ; "      fN.pos_(builtin.round-rat-to-fmag(32, builtin.fmag-rat(64, FI_MAG)))"
      ; "    if (builtin.float-finite(64, fN.pos_(FI_MAG))) = true ."
      ; "  ceq builtin.demote-f64(fN.neg_(FI_MAG)) ="
      ; "      fN.neg_(builtin.round-rat-to-fmag(32, builtin.fmag-rat(64, FI_MAG)))"
      ; "    if (builtin.float-finite(64, fN.neg_(FI_MAG))) = true ."
      ; "  eq builtin.demote-f64(fN.pos_(fNmag.inf)) = fN.pos_(fNmag.inf) ."
      ; "  eq builtin.demote-f64(fN.neg_(fNmag.inf)) = fN.neg_(fNmag.inf) ."
      ; "  ceq builtin.demote-f64(fN.pos_(fNmag.nan_(FP_M))) ="
      ; "      fN.pos_(fNmag.nan_(builtin.demote-f64-nan-payload(FP_M)))"
      ; "    if (builtin.fnmag-valid(64, fNmag.nan_(FP_M))) = true ."
      ; "  ceq builtin.demote-f64(fN.neg_(fNmag.nan_(FP_M))) ="
      ; "      fN.neg_(fNmag.nan_(builtin.demote-f64-nan-payload(FP_M)))"
      ; "    if (builtin.fnmag-valid(64, fNmag.nan_(FP_M))) = true ."
      ; "  eq builtin.nat-fmag-exact(FR_N, 0) = true ."
      ; "  ceq builtin.nat-fmag-exact(FR_N, FR_I) = true"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _<=_(FR_E, defm(FR_N)) ."
      ; "  ceq builtin.nat-fmag-exact(FR_N, FR_I) = true"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _>_(FR_E, defm(FR_N))"
      ; "       /\\ _rem_(FR_I, _^_(2, _-_(FR_E, defm(FR_N)))) = 0 ."
      ; "  eq builtin.nat-to-fmag(FR_N, 0) = fNmag.subnorm_(0) ."
      ; "  ceq builtin.nat-to-fmag(FR_N, FR_I) = fNmag.norm__(FR_FRAC, FR_E)"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _<=_(FR_E, defm(FR_N))"
      ; "       /\\ FR_FRAC := _*_( _-_(FR_I, _^_(2, FR_E)), _^_(2, _-_(defm(FR_N), FR_E)))"
      ; "       /\\ (builtin.fnmag-valid(FR_N, fNmag.norm__(FR_FRAC, FR_E))) = true ."
      ; "  ceq builtin.nat-to-fmag(FR_N, FR_I) = fNmag.norm__(FR_FRAC, FR_E)"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _>_(FR_E, defm(FR_N))"
      ; "       /\\ _rem_(FR_I, _^_(2, _-_(FR_E, defm(FR_N)))) = 0"
      ; "       /\\ FR_FRAC := _-_(_quo_(FR_I, _^_(2, _-_(FR_E, defm(FR_N)))), _^_(2, defm(FR_N)))"
      ; "       /\\ (builtin.fnmag-valid(FR_N, fNmag.norm__(FR_FRAC, FR_E))) = true ."
      ; "  ceq builtin.round-nat-significand(FR_N, FR_I) = FR_Q"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _>_(FR_E, defm(FR_N))"
      ; "       /\\ FR_SHIFT := _-_(FR_E, defm(FR_N))"
      ; "       /\\ FR_SCALE := _^_(2, FR_SHIFT)"
      ; "       /\\ FR_Q := _quo_(FR_I, FR_SCALE)"
      ; "       /\\ FR_REM := _rem_(FR_I, FR_SCALE)"
      ; "       /\\ FR_HALF := _^_(2, _-_(FR_SHIFT, 1))"
      ; "       /\\ _<_(FR_REM, FR_HALF) ."
      ; "  ceq builtin.round-nat-significand(FR_N, FR_I) = _+_(FR_Q, 1)"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _>_(FR_E, defm(FR_N))"
      ; "       /\\ FR_SHIFT := _-_(FR_E, defm(FR_N))"
      ; "       /\\ FR_SCALE := _^_(2, FR_SHIFT)"
      ; "       /\\ FR_Q := _quo_(FR_I, FR_SCALE)"
      ; "       /\\ FR_REM := _rem_(FR_I, FR_SCALE)"
      ; "       /\\ FR_HALF := _^_(2, _-_(FR_SHIFT, 1))"
      ; "       /\\ _>_(FR_REM, FR_HALF) ."
      ; "  ceq builtin.round-nat-significand(FR_N, FR_I) = FR_Q"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _>_(FR_E, defm(FR_N))"
      ; "       /\\ FR_SHIFT := _-_(FR_E, defm(FR_N))"
      ; "       /\\ FR_SCALE := _^_(2, FR_SHIFT)"
      ; "       /\\ FR_Q := _quo_(FR_I, FR_SCALE)"
      ; "       /\\ FR_REM := _rem_(FR_I, FR_SCALE)"
      ; "       /\\ FR_HALF := _^_(2, _-_(FR_SHIFT, 1))"
      ; "       /\\ _==_(FR_REM, FR_HALF)"
      ; "       /\\ _rem_(FR_Q, 2) = 0 ."
      ; "  ceq builtin.round-nat-significand(FR_N, FR_I) = _+_(FR_Q, 1)"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _>_(FR_E, defm(FR_N))"
      ; "       /\\ FR_SHIFT := _-_(FR_E, defm(FR_N))"
      ; "       /\\ FR_SCALE := _^_(2, FR_SHIFT)"
      ; "       /\\ FR_Q := _quo_(FR_I, FR_SCALE)"
      ; "       /\\ FR_REM := _rem_(FR_I, FR_SCALE)"
      ; "       /\\ FR_HALF := _^_(2, _-_(FR_SHIFT, 1))"
      ; "       /\\ _==_(FR_REM, FR_HALF)"
      ; "       /\\ _>_(_rem_(FR_Q, 2), 0) ."
      ; "  eq builtin.rounded-nat-to-fmag(FR_N, 0) = fNmag.subnorm_(0) ."
      ; "  ceq builtin.rounded-nat-to-fmag(FR_N, FR_I) = builtin.nat-to-fmag(FR_N, FR_I)"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _<=_(FR_E, defm(FR_N)) ."
      ; "  ceq builtin.rounded-nat-to-fmag(FR_N, FR_I) = fNmag.norm__(_-_(FR_SIG, _^_(2, defm(FR_N))), FR_E)"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _>_(FR_E, defm(FR_N))"
      ; "       /\\ FR_SIG := builtin.round-nat-significand(FR_N, FR_I)"
      ; "       /\\ _<_(FR_SIG, _^_(2, _+_(defm(FR_N), 1)))"
      ; "       /\\ (builtin.fnmag-valid(FR_N, fNmag.norm__(_-_(FR_SIG, _^_(2, defm(FR_N))), FR_E))) = true ."
      ; "  ceq builtin.rounded-nat-to-fmag(FR_N, FR_I) = fNmag.norm__(0, _+_(FR_E, 1))"
      ; "    if _>_(FR_I, 0)"
      ; "       /\\ FR_E := builtin.floor-log2(FR_I)"
      ; "       /\\ _>_(FR_E, defm(FR_N))"
      ; "       /\\ FR_SIG := builtin.round-nat-significand(FR_N, FR_I)"
      ; "       /\\ FR_SIG = _^_(2, _+_(defm(FR_N), 1))"
      ; "       /\\ (builtin.fnmag-valid(FR_N, fNmag.norm__(0, _+_(FR_E, 1)))) = true ."
      ; "  ceq builtin.int-to-float-like(FR_N, FR_X, FR_SOURCE) = fN.pos_(builtin.nat-to-fmag(FR_N, abs(FR_X)))"
      ; "    if _>_(FR_X, 0)"
      ; "       /\\ builtin.nat-fmag-exact(FR_N, abs(FR_X)) = true ."
      ; "  ceq builtin.int-to-float-like(FR_N, FR_X, FR_SOURCE) = fN.neg_(builtin.nat-to-fmag(FR_N, abs(FR_X)))"
      ; "    if _<_(FR_X, 0)"
      ; "       /\\ builtin.nat-fmag-exact(FR_N, abs(FR_X)) = true ."
      ; "  ceq builtin.int-to-float-like(FR_N, 0, fN.pos_(FR_MAG)) = fN.pos_(fNmag.subnorm_(0))"
      ; "    if (builtin.fnmag-valid(FR_N, FR_MAG)) = true ."
      ; "  ceq builtin.int-to-float-like(FR_N, 0, fN.neg_(FR_MAG)) = fN.neg_(fNmag.subnorm_(0))"
      ; "    if (builtin.fnmag-valid(FR_N, FR_MAG)) = true ."
      ; "  ceq builtin.int-to-iN(FI_N, FI_X) = FI_X"
      ; "    if _>=_(FI_X, 0) ."
      ; "  ceq builtin.int-to-iN(FI_N, FI_X) = sd(_^_(2, FI_N), abs(FI_X))"
      ; "    if _<_(FI_X, 0) ."
      ; "  ceq builtin.saturate-u-int(FI_N, FI_X) = 0"
      ; "    if _<_(FI_X, 0) ."
      ; "  ceq builtin.saturate-u-int(FI_N, FI_X) = builtin.int-to-iN(FI_N, FI_X)"
      ; "    if _>=_(FI_X, 0)"
      ; "       /\\ _<_(FI_X, _^_(2, FI_N)) ."
      ; "  ceq builtin.saturate-u-int(FI_N, FI_X) = _-_(_^_(2, FI_N), 1)"
      ; "    if _>=_(FI_X, _^_(2, FI_N)) ."
      ; "  ceq builtin.saturate-s-int(FI_N, FI_X) = builtin.int-to-iN(FI_N, - _^_(2, _-_(FI_N, 1)))"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ _<_(FI_X, - _^_(2, _-_(FI_N, 1))) ."
      ; "  ceq builtin.saturate-s-int(FI_N, FI_X) = builtin.int-to-iN(FI_N, FI_X)"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ _>=_(FI_X, - _^_(2, _-_(FI_N, 1)))"
      ; "       /\\ _<=_(FI_X, _-_( _^_(2, _-_(FI_N, 1)), 1)) ."
      ; "  ceq builtin.saturate-s-int(FI_N, FI_X) = _-_(_^_(2, _-_(FI_N, 1)), 1)"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ _>_(FI_X, _-_( _^_(2, _-_(FI_N, 1)), 1)) ."
      ]
    else
      [])



let implemented_equations ~has_entry =
  let has_float_round =
    has_entry "fceil_" || has_entry "ffloor_" || has_entry "ftrunc_"
    || has_entry "fnearest_"
  in
  let has_float_minmax =
    has_entry "fmin_" || has_entry "fmax_" || has_entry "fpmin_"
    || has_entry "fpmax_"
  in
  let has_float_compare =
    has_entry "feq_" || has_entry "fne_" || has_entry "flt_"
    || has_entry "fgt_" || has_entry "fle_" || has_entry "fge_"
  in
    (if has_entry "fsqrt_" then
      [ ""
      ; "  ceq deffsqrtx5fx(FI_N, fN.pos_(FI_MAG)) = fN.pos_(builtin.sqrt-fmag(FI_N, FI_MAG))"
      ; "    if (builtin.float-finite(FI_N, fN.pos_(FI_MAG))) = true ."
      ; "  eq deffsqrtx5fx(FI_N, fN.pos_(fNmag.inf)) = fN.pos_(fNmag.inf) ."
      ; "  eq deffsqrtx5fx(FI_N, fN.neg_(fNmag.subnorm_(0))) = fN.neg_(fNmag.subnorm_(0)) ."
      ; "  ceq deffsqrtx5fx(FI_N, fN.neg_(fNmag.subnorm_(FI_FRAC))) = builtin.float-default-nan(FI_N)"
      ; "    if _>_(FI_FRAC, 0)"
      ; "       /\\ (builtin.fnmag-valid(FI_N, fNmag.subnorm_(FI_FRAC))) = true ."
      ; "  ceq deffsqrtx5fx(FI_N, fN.neg_(fNmag.norm__(FI_FRAC, FI_E))) = builtin.float-default-nan(FI_N)"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.norm__(FI_FRAC, FI_E))) = true ."
      ; "  eq deffsqrtx5fx(FI_N, fN.neg_(fNmag.inf)) = builtin.float-default-nan(FI_N) ."
      ; "  ceq deffsqrtx5fx(FI_N, fN.pos_(fNmag.nan_(FI_FRAC))) = builtin.float-canonical-nan(FI_N, fN.pos_(fNmag.nan_(FI_FRAC)))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq deffsqrtx5fx(FI_N, fN.neg_(fNmag.nan_(FI_FRAC))) = builtin.float-canonical-nan(FI_N, fN.neg_(fNmag.nan_(FI_FRAC)))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.nan_(FI_FRAC))) = true ."
      ]
    else
      [])
    @
    (if has_float_round then
      [ ""
      ; "  ceq deffceilx5fx(FI_N, FI_F) = builtin.int-to-float-like(FI_N, FI_X, FI_F)"
      ; "    if (builtin.float-finite(FI_N, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_N, FI_F)"
      ; "       /\\ FI_X := ceiling(FI_R) ."
      ; "  ceq defffloorx5fx(FI_N, FI_F) = builtin.int-to-float-like(FI_N, FI_X, FI_F)"
      ; "    if (builtin.float-finite(FI_N, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_N, FI_F)"
      ; "       /\\ FI_X := floor(FI_R) ."
      ; "  ceq defftruncx5fx(FI_N, FI_F) = builtin.int-to-float-like(FI_N, FI_X, FI_F)"
      ; "    if (builtin.float-finite(FI_N, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_N, FI_F)"
      ; "       /\\ FI_X := builtin.trunc-rat-int(FI_R) ."
      ; "  ceq deffnearestx5fx(FI_N, FI_F) = builtin.int-to-float-like(FI_N, FI_X, FI_F)"
      ; "    if (builtin.float-finite(FI_N, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_N, FI_F)"
      ; "       /\\ FI_X := builtin.nearest-rat-int(FI_R) ."
      ; "  eq deffceilx5fx(FI_N, fN.pos_(fNmag.inf)) = fN.pos_(fNmag.inf) ."
      ; "  eq deffceilx5fx(FI_N, fN.neg_(fNmag.inf)) = fN.neg_(fNmag.inf) ."
      ; "  eq defffloorx5fx(FI_N, fN.pos_(fNmag.inf)) = fN.pos_(fNmag.inf) ."
      ; "  eq defffloorx5fx(FI_N, fN.neg_(fNmag.inf)) = fN.neg_(fNmag.inf) ."
      ; "  eq defftruncx5fx(FI_N, fN.pos_(fNmag.inf)) = fN.pos_(fNmag.inf) ."
      ; "  eq defftruncx5fx(FI_N, fN.neg_(fNmag.inf)) = fN.neg_(fNmag.inf) ."
      ; "  eq deffnearestx5fx(FI_N, fN.pos_(fNmag.inf)) = fN.pos_(fNmag.inf) ."
      ; "  eq deffnearestx5fx(FI_N, fN.neg_(fNmag.inf)) = fN.neg_(fNmag.inf) ."
      ; "  ceq deffceilx5fx(FI_N, fN.pos_(fNmag.nan_(FI_FRAC))) = builtin.float-canonical-nan(FI_N, fN.pos_(fNmag.nan_(FI_FRAC)))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq deffceilx5fx(FI_N, fN.neg_(fNmag.nan_(FI_FRAC))) = builtin.float-canonical-nan(FI_N, fN.neg_(fNmag.nan_(FI_FRAC)))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq defffloorx5fx(FI_N, fN.pos_(fNmag.nan_(FI_FRAC))) = builtin.float-canonical-nan(FI_N, fN.pos_(fNmag.nan_(FI_FRAC)))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq defffloorx5fx(FI_N, fN.neg_(fNmag.nan_(FI_FRAC))) = builtin.float-canonical-nan(FI_N, fN.neg_(fNmag.nan_(FI_FRAC)))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq defftruncx5fx(FI_N, fN.pos_(fNmag.nan_(FI_FRAC))) = builtin.float-canonical-nan(FI_N, fN.pos_(fNmag.nan_(FI_FRAC)))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq defftruncx5fx(FI_N, fN.neg_(fNmag.nan_(FI_FRAC))) = builtin.float-canonical-nan(FI_N, fN.neg_(fNmag.nan_(FI_FRAC)))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq deffnearestx5fx(FI_N, fN.pos_(fNmag.nan_(FI_FRAC))) = builtin.float-canonical-nan(FI_N, fN.pos_(fNmag.nan_(FI_FRAC)))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq deffnearestx5fx(FI_N, fN.neg_(fNmag.nan_(FI_FRAC))) = builtin.float-canonical-nan(FI_N, fN.neg_(fNmag.nan_(FI_FRAC)))"
      ; "    if (builtin.fnmag-valid(FI_N, fNmag.nan_(FI_FRAC))) = true ."
      ]
    else
      [])
    @
    (if has_entry "fadd_" then
      [ ""
      ; "  ceq deffaddx5fx(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 1 ."
      ; "  ceq deffaddx5fx(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 0"
      ; "       /\\ builtin.float-nan-bit(FC_N, FC_F2) = 1 ."
      ; "  eq deffaddx5fx(FC_N, fN.pos_(fNmag.inf), fN.pos_(fNmag.inf)) = fN.pos_(fNmag.inf) ."
      ; "  eq deffaddx5fx(FC_N, fN.neg_(fNmag.inf), fN.neg_(fNmag.inf)) = fN.neg_(fNmag.inf) ."
      ; "  eq deffaddx5fx(FC_N, fN.pos_(fNmag.inf), fN.neg_(fNmag.inf)) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffaddx5fx(FC_N, fN.neg_(fNmag.inf), fN.pos_(fNmag.inf)) = builtin.float-default-nan(FC_N) ."
      ; "  ceq deffaddx5fx(FC_N, fN.pos_(fNmag.inf), FC_F1) = fN.pos_(fNmag.inf)"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq deffaddx5fx(FC_N, FC_F1, fN.pos_(fNmag.inf)) = fN.pos_(fNmag.inf)"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq deffaddx5fx(FC_N, fN.neg_(fNmag.inf), FC_F1) = fN.neg_(fNmag.inf)"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq deffaddx5fx(FC_N, FC_F1, fN.neg_(fNmag.inf)) = fN.neg_(fNmag.inf)"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq deffaddx5fx(FC_N, FC_F1, FC_F2) = builtin.float-add-result(FC_N, FC_F1, FC_F2, _+_(FC_R1, FC_R2))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ (builtin.float-finite(FC_N, FC_F2)) = true"
      ; "       /\\ FC_R1 := builtin.float-rat(FC_N, FC_F1)"
      ; "       /\\ FC_R2 := builtin.float-rat(FC_N, FC_F2) ."
      ]
    else
      [])
    @
    (if has_entry "fsub_" then
      [ ""
      ; "  ceq deffsubx5fx(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 1 ."
      ; "  ceq deffsubx5fx(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 0"
      ; "       /\\ builtin.float-nan-bit(FC_N, FC_F2) = 1 ."
      ; "  ceq deffsubx5fx(FC_N, FC_F1, FC_F2) = deffaddx5fx(FC_N, FC_F1, builtin.float-neg(FC_N, FC_F2))"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 0"
      ; "       /\\ builtin.float-nan-bit(FC_N, FC_F2) = 0 ."
      ]
    else
      [])
    @
    (if has_entry "fmul_" then
      [ ""
      ; "  ceq deffmulx5fx(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 1 ."
      ; "  ceq deffmulx5fx(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 0"
      ; "       /\\ builtin.float-nan-bit(FC_N, FC_F2) = 1 ."
      ; "  eq deffmulx5fx(FC_N, fN.pos_(fNmag.inf), fN.pos_(fNmag.subnorm_(0))) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffmulx5fx(FC_N, fN.pos_(fNmag.inf), fN.neg_(fNmag.subnorm_(0))) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffmulx5fx(FC_N, fN.neg_(fNmag.inf), fN.pos_(fNmag.subnorm_(0))) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffmulx5fx(FC_N, fN.neg_(fNmag.inf), fN.neg_(fNmag.subnorm_(0))) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffmulx5fx(FC_N, fN.pos_(fNmag.subnorm_(0)), fN.pos_(fNmag.inf)) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffmulx5fx(FC_N, fN.neg_(fNmag.subnorm_(0)), fN.pos_(fNmag.inf)) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffmulx5fx(FC_N, fN.pos_(fNmag.subnorm_(0)), fN.neg_(fNmag.inf)) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffmulx5fx(FC_N, fN.neg_(fNmag.subnorm_(0)), fN.neg_(fNmag.inf)) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffmulx5fx(FC_N, fN.pos_(fNmag.inf), fN.pos_(fNmag.inf)) = fN.pos_(fNmag.inf) ."
      ; "  eq deffmulx5fx(FC_N, fN.pos_(fNmag.inf), fN.neg_(fNmag.inf)) = fN.neg_(fNmag.inf) ."
      ; "  eq deffmulx5fx(FC_N, fN.neg_(fNmag.inf), fN.pos_(fNmag.inf)) = fN.neg_(fNmag.inf) ."
      ; "  eq deffmulx5fx(FC_N, fN.neg_(fNmag.inf), fN.neg_(fNmag.inf)) = fN.pos_(fNmag.inf) ."
      ; "  ceq deffmulx5fx(FC_N, fN.pos_(fNmag.inf), FC_F1) ="
      ; "      builtin.float-signed-inf(builtin.float-sign-bit(FC_N, FC_F1))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ _=/=_(builtin.float-rat(FC_N, FC_F1), 0) ."
      ; "  ceq deffmulx5fx(FC_N, FC_F1, fN.pos_(fNmag.inf)) ="
      ; "      builtin.float-signed-inf(builtin.float-sign-bit(FC_N, FC_F1))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ _=/=_(builtin.float-rat(FC_N, FC_F1), 0) ."
      ; "  ceq deffmulx5fx(FC_N, fN.neg_(fNmag.inf), FC_F1) ="
      ; "      builtin.float-signed-inf(builtin.bit-xor(1, builtin.float-sign-bit(FC_N, FC_F1)))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ _=/=_(builtin.float-rat(FC_N, FC_F1), 0) ."
      ; "  ceq deffmulx5fx(FC_N, FC_F1, fN.neg_(fNmag.inf)) ="
      ; "      builtin.float-signed-inf(builtin.bit-xor(1, builtin.float-sign-bit(FC_N, FC_F1)))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ _=/=_(builtin.float-rat(FC_N, FC_F1), 0) ."
      ; "  ceq deffmulx5fx(FC_N, FC_F1, FC_F2) ="
      ; "      builtin.rat-to-float-nearest-signed-zero("
      ; "        FC_N,"
      ; "        builtin.bit-xor(builtin.float-sign-bit(FC_N, FC_F1), builtin.float-sign-bit(FC_N, FC_F2)),"
      ; "        _*_(FC_R1, FC_R2))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ (builtin.float-finite(FC_N, FC_F2)) = true"
      ; "       /\\ FC_R1 := builtin.float-rat(FC_N, FC_F1)"
      ; "       /\\ FC_R2 := builtin.float-rat(FC_N, FC_F2) ."
      ]
    else
      [])
    @
    (if has_entry "fdiv_" then
      [ ""
      ; "  ceq deffdivx5fx(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 1 ."
      ; "  ceq deffdivx5fx(FC_N, FC_F1, FC_F2) = builtin.float-binary-nan(FC_N, FC_F1, FC_F2)"
      ; "    if builtin.float-nan-bit(FC_N, FC_F1) = 0"
      ; "       /\\ builtin.float-nan-bit(FC_N, FC_F2) = 1 ."
      ; "  eq deffdivx5fx(FC_N, fN.pos_(fNmag.subnorm_(0)), fN.pos_(fNmag.subnorm_(0))) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffdivx5fx(FC_N, fN.pos_(fNmag.subnorm_(0)), fN.neg_(fNmag.subnorm_(0))) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffdivx5fx(FC_N, fN.neg_(fNmag.subnorm_(0)), fN.pos_(fNmag.subnorm_(0))) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffdivx5fx(FC_N, fN.neg_(fNmag.subnorm_(0)), fN.neg_(fNmag.subnorm_(0))) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffdivx5fx(FC_N, fN.pos_(fNmag.inf), fN.pos_(fNmag.inf)) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffdivx5fx(FC_N, fN.pos_(fNmag.inf), fN.neg_(fNmag.inf)) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffdivx5fx(FC_N, fN.neg_(fNmag.inf), fN.pos_(fNmag.inf)) = builtin.float-default-nan(FC_N) ."
      ; "  eq deffdivx5fx(FC_N, fN.neg_(fNmag.inf), fN.neg_(fNmag.inf)) = builtin.float-default-nan(FC_N) ."
      ; "  ceq deffdivx5fx(FC_N, FC_F1, fN.pos_(fNmag.subnorm_(0))) ="
      ; "      builtin.float-signed-inf(builtin.float-sign-bit(FC_N, FC_F1))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ _=/=_(builtin.float-rat(FC_N, FC_F1), 0) ."
      ; "  ceq deffdivx5fx(FC_N, FC_F1, fN.neg_(fNmag.subnorm_(0))) ="
      ; "      builtin.float-signed-inf(builtin.bit-xor(builtin.float-sign-bit(FC_N, FC_F1), 1))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ _=/=_(builtin.float-rat(FC_N, FC_F1), 0) ."
      ; "  ceq deffdivx5fx(FC_N, fN.pos_(fNmag.inf), FC_F1) ="
      ; "      builtin.float-signed-inf(builtin.float-sign-bit(FC_N, FC_F1))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq deffdivx5fx(FC_N, fN.neg_(fNmag.inf), FC_F1) ="
      ; "      builtin.float-signed-inf(builtin.bit-xor(1, builtin.float-sign-bit(FC_N, FC_F1)))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq deffdivx5fx(FC_N, FC_F1, fN.pos_(fNmag.inf)) ="
      ; "      builtin.float-signed-zero(builtin.float-sign-bit(FC_N, FC_F1))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq deffdivx5fx(FC_N, FC_F1, fN.neg_(fNmag.inf)) ="
      ; "      builtin.float-signed-zero(builtin.bit-xor(builtin.float-sign-bit(FC_N, FC_F1), 1))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true ."
      ; "  ceq deffdivx5fx(FC_N, FC_F1, FC_F2) ="
      ; "      builtin.rat-to-float-nearest-signed-zero("
      ; "        FC_N,"
      ; "        builtin.bit-xor(builtin.float-sign-bit(FC_N, FC_F1), builtin.float-sign-bit(FC_N, FC_F2)),"
      ; "        _/_(FC_R1, FC_R2))"
      ; "    if (builtin.float-finite(FC_N, FC_F1)) = true"
      ; "       /\\ (builtin.float-finite(FC_N, FC_F2)) = true"
      ; "       /\\ FC_R1 := builtin.float-rat(FC_N, FC_F1)"
      ; "       /\\ FC_R2 := builtin.float-rat(FC_N, FC_F2)"
      ; "       /\\ _=/=_(FC_R2, 0) ."
      ]
    else
      [])
    @
    (if has_float_minmax then
      [ ""
      ; "  eq deffminx5fx(FC_N, FC_F1, FC_F2) ="
      ; "      builtin.float-min(FC_N, FC_F1, FC_F2) ."
      ; "  eq deffmaxx5fx(FC_N, FC_F1, FC_F2) ="
      ; "      builtin.float-max(FC_N, FC_F1, FC_F2) ."
      ; "  eq deffpminx5fx(FC_N, FC_F1, FC_F2) ="
      ; "      builtin.float-pmin(FC_N, FC_F1, FC_F2) ."
      ; "  eq deffpmaxx5fx(FC_N, FC_F1, FC_F2) ="
      ; "      builtin.float-pmax(FC_N, FC_F1, FC_F2) ."
      ]
    else
      [])
    @
    (if has_float_compare then
      [ ""
      ; "  eq deffeqx5fx(FC_N, FC_F1, FC_F2) ="
      ; "      u32.wrap_(builtin.float-eq-bit(FC_N, FC_F1, FC_F2)) ."
      ; "  eq deffnex5fx(FC_N, FC_F1, FC_F2) ="
      ; "      u32.wrap_("
      ; "        builtin.bit-or(builtin.float-nan-bit(FC_N, FC_F1),"
      ; "          builtin.bit-or(builtin.float-nan-bit(FC_N, FC_F2),"
      ; "            builtin.bit-not(builtin.float-eq-bit(FC_N, FC_F1, FC_F2))))) ."
      ; "  eq deffltx5fx(FC_N, FC_F1, FC_F2) ="
      ; "      u32.wrap_(builtin.float-lt-bit(FC_N, FC_F1, FC_F2)) ."
      ; "  eq deffgtx5fx(FC_N, FC_F1, FC_F2) ="
      ; "      u32.wrap_(builtin.float-lt-bit(FC_N, FC_F2, FC_F1)) ."
      ; "  eq defflex5fx(FC_N, FC_F1, FC_F2) ="
      ; "      u32.wrap_("
      ; "        builtin.bit-and(builtin.bit-not(builtin.float-nan-bit(FC_N, FC_F1)),"
      ; "          builtin.bit-and(builtin.bit-not(builtin.float-nan-bit(FC_N, FC_F2)),"
      ; "            builtin.bit-not(builtin.float-lt-bit(FC_N, FC_F2, FC_F1))))) ."
      ; "  eq deffgex5fx(FC_N, FC_F1, FC_F2) ="
      ; "      u32.wrap_("
      ; "        builtin.bit-and(builtin.bit-not(builtin.float-nan-bit(FC_N, FC_F1)),"
      ; "          builtin.bit-and(builtin.bit-not(builtin.float-nan-bit(FC_N, FC_F2)),"
      ; "            builtin.bit-not(builtin.float-lt-bit(FC_N, FC_F1, FC_F2))))) ."
      ]
    else
      [])
    @
    (if has_entry "trunc__" then
      [ ""
      ; "  ceq deftruncx5fxx5fx(FI_M, FI_N, sx.u, FI_F) = iN.wrap_(builtin.int-to-iN(FI_N, FI_X))"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ (builtin.float-finite(FI_M, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_M, FI_F)"
      ; "       /\\ FI_X := builtin.trunc-rat-int(FI_R)"
      ; "       /\\ _>=_(FI_X, 0)"
      ; "       /\\ _<_(FI_X, _^_(2, FI_N)) ."
      ; "  ceq deftruncx5fxx5fx(FI_M, FI_N, sx.s, FI_F) = iN.wrap_(builtin.int-to-iN(FI_N, FI_X))"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ (builtin.float-finite(FI_M, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_M, FI_F)"
      ; "       /\\ FI_X := builtin.trunc-rat-int(FI_R)"
      ; "       /\\ _>=_(FI_X, - _^_(2, _-_(FI_N, 1)))"
      ; "       /\\ _<=_(FI_X, _-_( _^_(2, _-_(FI_N, 1)), 1)) ."
      ; "  eq deftruncx5fxx5fx(FI_M, FI_N, sx.u, fN.pos_(fNmag.inf)) = eps ."
      ; "  eq deftruncx5fxx5fx(FI_M, FI_N, sx.u, fN.neg_(fNmag.inf)) = eps ."
      ; "  ceq deftruncx5fxx5fx(FI_M, FI_N, sx.u, fN.pos_(fNmag.nan_(FI_FRAC))) = eps"
      ; "    if (builtin.fnmag-valid(FI_M, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq deftruncx5fxx5fx(FI_M, FI_N, sx.u, fN.neg_(fNmag.nan_(FI_FRAC))) = eps"
      ; "    if (builtin.fnmag-valid(FI_M, fNmag.nan_(FI_FRAC))) = true ."
      ; "  eq deftruncx5fxx5fx(FI_M, FI_N, sx.s, fN.pos_(fNmag.inf)) = eps ."
      ; "  eq deftruncx5fxx5fx(FI_M, FI_N, sx.s, fN.neg_(fNmag.inf)) = eps ."
      ; "  ceq deftruncx5fxx5fx(FI_M, FI_N, sx.s, fN.pos_(fNmag.nan_(FI_FRAC))) = eps"
      ; "    if (builtin.fnmag-valid(FI_M, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq deftruncx5fxx5fx(FI_M, FI_N, sx.s, fN.neg_(fNmag.nan_(FI_FRAC))) = eps"
      ; "    if (builtin.fnmag-valid(FI_M, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq deftruncx5fxx5fx(FI_M, FI_N, sx.u, FI_F) = eps"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ (builtin.float-finite(FI_M, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_M, FI_F)"
      ; "       /\\ FI_X := builtin.trunc-rat-int(FI_R)"
      ; "       /\\ _<_(FI_X, 0) ."
      ; "  ceq deftruncx5fxx5fx(FI_M, FI_N, sx.u, FI_F) = eps"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ (builtin.float-finite(FI_M, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_M, FI_F)"
      ; "       /\\ FI_X := builtin.trunc-rat-int(FI_R)"
      ; "       /\\ _>=_(FI_X, _^_(2, FI_N)) ."
      ; "  ceq deftruncx5fxx5fx(FI_M, FI_N, sx.s, FI_F) = eps"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ (builtin.float-finite(FI_M, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_M, FI_F)"
      ; "       /\\ FI_X := builtin.trunc-rat-int(FI_R)"
      ; "       /\\ _<_(FI_X, - _^_(2, _-_(FI_N, 1))) ."
      ; "  ceq deftruncx5fxx5fx(FI_M, FI_N, sx.s, FI_F) = eps"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ (builtin.float-finite(FI_M, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_M, FI_F)"
      ; "       /\\ FI_X := builtin.trunc-rat-int(FI_R)"
      ; "       /\\ _>_(FI_X, _-_( _^_(2, _-_(FI_N, 1)), 1)) ."
      ]
    else
      [])
    @
    (if has_entry "trunc_sat__" then
      [ ""
      ; "  ceq deftruncx5fxsatx5fxx5fx(FI_M, FI_N, sx.u, FI_F) = iN.wrap_(builtin.saturate-u-int(FI_N, FI_X))"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ (builtin.float-finite(FI_M, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_M, FI_F)"
      ; "       /\\ FI_X := builtin.trunc-rat-int(FI_R) ."
      ; "  ceq deftruncx5fxsatx5fxx5fx(FI_M, FI_N, sx.s, FI_F) = iN.wrap_(builtin.saturate-s-int(FI_N, FI_X))"
      ; "    if _>_(FI_N, 0)"
      ; "       /\\ (builtin.float-finite(FI_M, FI_F)) = true"
      ; "       /\\ FI_R := builtin.float-rat(FI_M, FI_F)"
      ; "       /\\ FI_X := builtin.trunc-rat-int(FI_R) ."
      ; "  eq deftruncx5fxsatx5fxx5fx(FI_M, FI_N, sx.u, fN.pos_(fNmag.inf)) = iN.wrap_(_-_(_^_(2, FI_N), 1)) ."
      ; "  eq deftruncx5fxsatx5fxx5fx(FI_M, FI_N, sx.u, fN.neg_(fNmag.inf)) = iN.wrap_(0) ."
      ; "  ceq deftruncx5fxsatx5fxx5fx(FI_M, FI_N, sx.u, fN.pos_(fNmag.nan_(FI_FRAC))) = iN.wrap_(0)"
      ; "    if (builtin.fnmag-valid(FI_M, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq deftruncx5fxsatx5fxx5fx(FI_M, FI_N, sx.u, fN.neg_(fNmag.nan_(FI_FRAC))) = iN.wrap_(0)"
      ; "    if (builtin.fnmag-valid(FI_M, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq deftruncx5fxsatx5fxx5fx(FI_M, FI_N, sx.s, fN.pos_(fNmag.inf)) = iN.wrap_(_-_(_^_(2, _-_(FI_N, 1)), 1))"
      ; "    if _>_(FI_N, 0) ."
      ; "  ceq deftruncx5fxsatx5fxx5fx(FI_M, FI_N, sx.s, fN.neg_(fNmag.inf)) = iN.wrap_(builtin.int-to-iN(FI_N, - _^_(2, _-_(FI_N, 1))))"
      ; "    if _>_(FI_N, 0) ."
      ; "  ceq deftruncx5fxsatx5fxx5fx(FI_M, FI_N, sx.s, fN.pos_(fNmag.nan_(FI_FRAC))) = iN.wrap_(0)"
      ; "    if (builtin.fnmag-valid(FI_M, fNmag.nan_(FI_FRAC))) = true ."
      ; "  ceq deftruncx5fxsatx5fxx5fx(FI_M, FI_N, sx.s, fN.neg_(fNmag.nan_(FI_FRAC))) = iN.wrap_(0)"
      ; "    if (builtin.fnmag-valid(FI_M, fNmag.nan_(FI_FRAC))) = true ."
      ]
    else
      [])
    @
    (if has_entry "convert__" then
      [ ""
      ; "  ceq defconvertx5fxx5fx(FI_M, FI_N, sx.u, iN.wrap_(FI_RESULT)) ="
      ; "      fN.pos_(builtin.rounded-nat-to-fmag(FI_N, FI_RESULT))"
      ; "    if _>_(FI_M, 0)"
      ; "       /\\ _>_(FI_N, 0)"
      ; "       /\\ _<_(FI_RESULT, _^_(2, FI_M))"
      ; "       /\\ (builtin.fnmag-valid(FI_N, builtin.rounded-nat-to-fmag(FI_N, FI_RESULT))) = true ."
      ; "  ceq defconvertx5fxx5fx(FI_M, FI_N, sx.s, iN.wrap_(FI_RESULT)) ="
      ; "      fN.pos_(builtin.rounded-nat-to-fmag(FI_N, FI_RESULT))"
      ; "    if _>_(FI_M, 0)"
      ; "       /\\ _>_(FI_N, 0)"
      ; "       /\\ _<_(FI_RESULT, _^_(2, _-_(FI_M, 1)))"
      ; "       /\\ (builtin.fnmag-valid(FI_N, builtin.rounded-nat-to-fmag(FI_N, FI_RESULT))) = true ."
      ; "  ceq defconvertx5fxx5fx(FI_M, FI_N, sx.s, iN.wrap_(FI_RESULT)) ="
      ; "      fN.neg_(builtin.rounded-nat-to-fmag(FI_N, _-_(_^_(2, FI_M), FI_RESULT)))"
      ; "    if _>_(FI_M, 0)"
      ; "       /\\ _>_(FI_N, 0)"
      ; "       /\\ _>=_(FI_RESULT, _^_(2, _-_(FI_M, 1)))"
      ; "       /\\ _<_(FI_RESULT, _^_(2, FI_M))"
      ; "       /\\ (builtin.fnmag-valid(FI_N, builtin.rounded-nat-to-fmag(FI_N, _-_(_^_(2, FI_M), FI_RESULT)))) = true ."
      ]
    else
      [])
    @
    (if has_entry "demote__" then
      [ ""
      ; "  ceq defdemotex5fxx5fx(64, 32, fN.pos_(FI_MAG)) = builtin.demote-f64(fN.pos_(FI_MAG))"
      ; "    if (builtin.fnmag-valid(64, FI_MAG)) = true ."
      ; "  ceq defdemotex5fxx5fx(64, 32, fN.neg_(FI_MAG)) = builtin.demote-f64(fN.neg_(FI_MAG))"
      ; "    if (builtin.fnmag-valid(64, FI_MAG)) = true ."
      ]
    else
      [])
    @
    (if has_entry "promote__" then
      [ ""
      ; "  ceq defpromotex5fxx5fx(32, 64, fN.pos_(FI_MAG)) = builtin.promote-f32(fN.pos_(FI_MAG))"
      ; "    if (builtin.fnmag-valid(32, FI_MAG)) = true ."
      ; "  ceq defpromotex5fxx5fx(32, 64, fN.neg_(FI_MAG)) = builtin.promote-f32(fN.neg_(FI_MAG))"
      ; "    if (builtin.fnmag-valid(32, FI_MAG)) = true ."
      ]
    else
      [])
    @
    (if has_entry "fabs_" then
      [ ""
      ; "  ceq deffabsx5fx(FS_N, fN.pos_(FS_MAG)) = fN.pos_(FS_MAG)"
      ; "    if (builtin.fnmag-valid(FS_N, FS_MAG)) = true ."
      ; "  ceq deffabsx5fx(FS_N, fN.neg_(FS_MAG)) = fN.pos_(FS_MAG)"
      ; "    if (builtin.fnmag-valid(FS_N, FS_MAG)) = true ."
      ]
    else
      [])
    @
    (if has_entry "fneg_" then
      [ ""
      ; "  ceq deffnegx5fx(FS_N, fN.pos_(FS_MAG)) = fN.neg_(FS_MAG)"
      ; "    if (builtin.fnmag-valid(FS_N, FS_MAG)) = true ."
      ; "  ceq deffnegx5fx(FS_N, fN.neg_(FS_MAG)) = fN.pos_(FS_MAG)"
      ; "    if (builtin.fnmag-valid(FS_N, FS_MAG)) = true ."
      ]
    else
      [])
    @
    (if has_entry "fcopysign_" then
      [ ""
      ; "  ceq deffcopysignx5fx(FS_N, fN.pos_(FS_MAG), fN.pos_(FS_MAG2)) = fN.pos_(FS_MAG)"
      ; "    if (builtin.fnmag-valid(FS_N, FS_MAG)) = true"
      ; "       /\\ (builtin.fnmag-valid(FS_N, FS_MAG2)) = true ."
      ; "  ceq deffcopysignx5fx(FS_N, fN.neg_(FS_MAG), fN.pos_(FS_MAG2)) = fN.pos_(FS_MAG)"
      ; "    if (builtin.fnmag-valid(FS_N, FS_MAG)) = true"
      ; "       /\\ (builtin.fnmag-valid(FS_N, FS_MAG2)) = true ."
      ; "  ceq deffcopysignx5fx(FS_N, fN.pos_(FS_MAG), fN.neg_(FS_MAG2)) = fN.neg_(FS_MAG)"
      ; "    if (builtin.fnmag-valid(FS_N, FS_MAG)) = true"
      ; "       /\\ (builtin.fnmag-valid(FS_N, FS_MAG2)) = true ."
      ; "  ceq deffcopysignx5fx(FS_N, fN.neg_(FS_MAG), fN.neg_(FS_MAG2)) = fN.neg_(FS_MAG)"
      ; "    if (builtin.fnmag-valid(FS_N, FS_MAG)) = true"
      ; "       /\\ (builtin.fnmag-valid(FS_N, FS_MAG2)) = true ."
      ]
    else
      [])
