mod CLIENT-WASM is
  protecting WASM-BUILTINS .

  sort ClientRunState .

  --- clientCall(args)부터 시작해서 clientResult(result)까지 실제 Wasm 실행
  op clientCall   : ValList -> ClientRunState [ctor] .
  op clientInit   : SpectecTerminal ValList -> ClientRunState [ctor frozen (1)] .
  op clientExec   : SpectecTerminal -> ClientRunState [ctor frozen (1)] .
  op clientResult : ValList -> ClientRunState [ctor] .

  op clientModule : -> SpectecTerminal .
  op clientName : -> SpectecTerminals .
  op clientEmptyStore : -> SpectecTerminal .
  op clientFindFunc : SpectecTerminals SpectecTerminals ~> Nat .

  vars C C2 Z XA : SpectecTerminal .
  vars NAME OTHER EXPORTS : SpectecTerminals .
  vars ARGS RESULT : ValList .
  var ADDR : Nat .


  --- 실제 client.wasm
  eq clientModule =
    MODULE(TYPE(REC(SUB(_?(FINAL), eps, FUNC_->_((I32 I32), I32)))), eps, eps,
    eps, eps, eps,
    spectec-FUNC-2(0, eps,
    (LOCAL.GET(0) CONST(I32, 0) RELOP(I32, EQ)
     IF__ELSE_(-RESULT(_?(I32)),
     (LOCAL.GET(1) CONST(I32, 0) RELOP(I32, EQ)
      IF__ELSE_(-RESULT(_?(I32)), CONST(I32, 1), CONST(I32, 0))),
     (LOCAL.GET(0) CONST(I32, 1) RELOP(I32, EQ)
      IF__ELSE_(-RESULT(_?(I32)),
      (LOCAL.GET(1) CONST(I32, 1) RELOP(I32, EQ)
       IF__ELSE_(-RESULT(_?(I32)), CONST(I32, 2), CONST(I32, 1))),
      CONST(I32, 2)))))),
    eps, eps, eps,
    EXPORT(((99 108 105 101 110) (116 95 115 116 101 112)), FUNC(0))) .


  eq clientName =
    (99 108 105 101 110)
    (116 95 115 116 101 112) .


  eq clientEmptyStore =
    {(item('TAGS, eps) ;
      (item('GLOBALS, eps) ;
       (item('MEMS, eps) ;
        (item('TABLES, eps) ;
         (item('FUNCS, eps) ;
          (item('DATAS, eps) ;
           (item('ELEMS, eps) ;
            (item('STRUCTS, eps) ;
             (item('ARRAYS, eps) ;
              item('EXNS, eps))))))))))} .


  eq clientFindFunc(
       {(item('NAME, NAME) ; item('ADDR, FUNC(ADDR)))} EXPORTS,
       NAME)
    = ADDR .

  ceq clientFindFunc(
        {(item('NAME, OTHER) ; item('ADDR, XA))} EXPORTS,
        NAME)
    = clientFindFunc(EXPORTS, NAME)
    if OTHER =/= NAME .


  --- wasm2maude가 원래 생성했던 실행 과정
  crl [client-instantiate] :
    clientCall(ARGS)
    =>
    clientInit(C, ARGS)
    if instantiate(clientEmptyStore, clientModule, eps) => C .


  crl [client-init-step] :
    clientInit(C, ARGS)
    =>
    clientInit(C2, ARGS)
    if Step(C) => C2 .


  crl [client-invoke] :
    clientInit(C, ARGS)
    =>
    clientExec(
      invoke(
        spectec-store(Z),
        clientFindFunc(
          value('EXPORTS, spectec-moduleinst(Z)),
          clientName),
        ARGS))
    if (Z ; eps) := C .


  crl [client-step] :
    clientExec(C)
    =>
    clientExec(C2)
    if Step(C) => C2 .


  crl [client-finished] :
    clientExec(C)
    =>
    clientResult(RESULT)
    if (Z ; RESULT) := C .

endm