load 1-4 

mod 2_0_VALIDATION is
  inc DSL-TERM .
  inc DSL-PRETYPE .
  inc DSL-EXEC .

  inc 1_1_SYNTAX_VALUES .
  inc 1_2_SYNTAX_TYPES .
  inc 1_3_SYNTAX_INSTRUCTIONS .
  inc 1_4_SYNTAX_MODULES .

  subsort Int < WasmTerminal .
  subsort Nat < WasmTerminal .

  op nat : -> WasmType [ctor] . 
  var I : Int .
  var T : WasmTerminal .

  op N :  -> WasmType [ctor] .
  eq typecheck(T, N) =  typecheck(T, WasmType) .
  op M :  -> WasmType [ctor] .
  eq typecheck(T, M) =  typecheck(T, WasmType) .
  op K :  -> WasmType [ctor] .
  eq typecheck(T, K) =  typecheck(T, WasmType) .
  op n :  -> WasmType [ctor] .
  eq typecheck(T, n) =  typecheck(T, WasmType) .
  op m :  -> WasmType [ctor] .
  eq typecheck(T, m) =  typecheck(T, WasmType) .

  op $min : WasmTerminal WasmTerminal -> WasmTerminal .
  var NAT : WasmTerminal .
  var NAT : WasmTerminal .
  var I : WasmTerminal .
  eq $min(I) = I .
  var I : WasmTerminal .
  eq $min(I) = J .


  op $sum : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq sum(0) = 0 .
  eq sum(0) = (N + $sum(0)) .


  op $prod : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq prod(0) = 1 .
  eq prod(0) = (N * $prod(0)) .


  op $opt_ : WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq opt_(UNKNOWN) = 0 .
  eq opt_(UNKNOWN) = 0 .


  op $concat_ : WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq concat_(UNKNOWN) = 0 .
  eq concat_(UNKNOWN) = 0 .


  op $concatn_ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  var NAT : WasmTerminal .
  eq concatn_(UNKNOWN) = 0 .
  eq concatn_(UNKNOWN) = 0 .


  op $concatopt_ : WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq concatopt_(UNKNOWN) = 0 .
  eq concatopt_(UNKNOWN) = 0 .


  op $inv_concat_ : WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .



  op $inv_concatn_ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var NAT : WasmTerminal .
  var _ : WasmTerminal .



  op $disjoint_ : WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq disjoint_(UNKNOWN) = 0 .
  eq disjoint_(UNKNOWN) = (not (0) /\ $disjoint-(X, 0)) .


  op $setminus1_ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var X : WasmTerminal .
  var _ : WasmTerminal .
  eq setminus1_(UNKNOWN) = 0 .
  eq setminus1_(UNKNOWN) = 0 .
  eq setminus1_(UNKNOWN) = $setminus1-(X, W, 0) .


  op $setminus_ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq setminus_(UNKNOWN) = 0 .
  eq setminus_(UNKNOWN) = 0 .


  op $setproduct2_ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var X : WasmTerminal .
  var _ : WasmTerminal .
  eq setproduct2_(UNKNOWN) = 0 .
  eq setproduct2_(UNKNOWN) = 0 .


  op $setproduct1_ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq setproduct1_(UNKNOWN) = 0 .
  eq setproduct1_(UNKNOWN) = 0 .


  op $setproduct_ : WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq setproduct_(UNKNOWN) = 0 .
  eq setproduct_(UNKNOWN) = $setproduct1-(X, 0, $setproduct-(X, 0)) .


  op $ND :  -> WasmTerminal .


  op bit :  -> WasmType [ctor] .
 
  ceq typecheck(i, bit) = true 
   if ((I == 0) \/ (I == 1)) .
  op byte :  -> WasmType [ctor] .
 
  ceq typecheck(i, byte) = true 
   if ((I >= 0) /\ (I <= 255)) .
  op uN : WasmTerminal -> WasmType [ctor] .
  var N_UN : Nat . 
  ceq typecheck(i, uN(N)) = true 
   if typecheck(N, N) /\ ((I >= 0) /\ (I <= ((2 ^ N) - 1))) .
  op sN : WasmTerminal -> WasmType [ctor] .
  var N_SN : Nat . 
  ceq typecheck(i, sN(N)) = true 
   if typecheck(N, N) /\ ((((I >= -((2 ^ (N - 1)))) /\ (I <= -(1))) \/ (I == 0)) \/ ((I >= +(1)) /\ (I <= (+((2 ^ (N - 1))) - 1)))) .
  op iN : WasmTerminal -> WasmType [ctor] .
  eq typecheck(T, iN(N)) = typecheck(N, N) /\  typecheck(T, uN(N)) .
  op u8 :  -> WasmType [ctor] .
  eq typecheck(T, u8) =  typecheck(T, uN(8)) .
  op u16 :  -> WasmType [ctor] .
  eq typecheck(T, u16) =  typecheck(T, uN(16)) .
  op u31 :  -> WasmType [ctor] .
  eq typecheck(T, u31) =  typecheck(T, uN(31)) .
  op u32 :  -> WasmType [ctor] .
  eq typecheck(T, u32) =  typecheck(T, uN(32)) .
  op u64 :  -> WasmType [ctor] .
  eq typecheck(T, u64) =  typecheck(T, uN(64)) .
  op s33 :  -> WasmType [ctor] .
  eq typecheck(T, s33) =  typecheck(T, sN(33)) .
  op i32 :  -> WasmType [ctor] .
  eq typecheck(T, i32) =  typecheck(T, iN(32)) .
  op i64 :  -> WasmType [ctor] .
  eq typecheck(T, i64) =  typecheck(T, iN(64)) .
  op i128 :  -> WasmType [ctor] .
  eq typecheck(T, i128) =  typecheck(T, iN(128)) .

  op $signif : WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  eq signif(32) = 23 .
  eq signif(64) = 52 .


  op $expon : WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  eq expon(32) = 8 .
  eq expon(64) = 11 .


  op $M : WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  var N : WasmTerminal .
  eq $M(N) = $signif(N) .


  op $E : WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  var N : WasmTerminal .
  eq $E(N) = $expon(N) .

  op exp :  -> WasmType [ctor] .
  eq typecheck(T, exp) =  typecheck(T, WasmType) .
  op fNmag : WasmTerminal -> WasmType [ctor] .
  var N_FNMAG : Nat . 
  ceq typecheck(i, fNmag(N)) = true 
   if typecheck(N, N) /\ ((M < (2 ^ $M(N))) /\ (((2 - (2 ^ ($E(N) - 1))) <= EXP) /\ (EXP <= ((2 ^ ($E(N) - 1)) - 1)))) .
  var N_FNMAG : Nat . 
  ceq typecheck(i, fNmag(N)) = true 
   if typecheck(N, N) /\ ((M < (2 ^ $M(N))) /\ ((2 - (2 ^ ($E(N) - 1))) == EXP)) .
  op INF :  -> WasmTerminal [ctor] .
  eq typecheck(INF, fNmag(N)) = typecheck(N, N) .
  var N_FNMAG : Nat . 
  ceq typecheck(i, fNmag(N)) = true 
   if typecheck(N, N) /\ ((1 <= M) /\ (M < (2 ^ $M(N)))) .
  op fN : WasmTerminal -> WasmType [ctor] .
  op POS _ : WasmTerminal -> WasmTerminal [ctor] .
  var FNMAG1 : WasmTerminal .
  eq typecheck(POS FNMAG1, fN(N)) = typecheck(N, N) /\ typecheck(FNMAG1, fNmag(N)) .
  op NEG _ : WasmTerminal -> WasmTerminal [ctor] .
  var FNMAG1 : WasmTerminal .
  eq typecheck(NEG FNMAG1, fN(N)) = typecheck(N, N) /\ typecheck(FNMAG1, fNmag(N)) .
  op f32 :  -> WasmType [ctor] .
  eq typecheck(T, f32) =  typecheck(T, fN(32)) .
  op f64 :  -> WasmType [ctor] .
  eq typecheck(T, f64) =  typecheck(T, fN(64)) .

  op $fzero : WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  var N : WasmTerminal .
  eq $fzero(N) = POS .


  op $fnat : WasmTerminal WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  var NAT : WasmTerminal .
  var N : WasmTerminal .
  eq $fnat(N) = POS .


  op $fone : WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  var N : WasmTerminal .
  eq $fone(N) = POS .


  op $canon_ : WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  var N : WasmTerminal .
  eq $canon_(N) = (2 ^ ($signif(N) - 1)) .

  op vN : WasmTerminal -> WasmType [ctor] .
  eq typecheck(T, vN(N)) = typecheck(N, N) /\  typecheck(T, uN(N)) .
  op v128 :  -> WasmType [ctor] .
  eq typecheck(T, v128) =  typecheck(T, vN(128)) .
  op list : WasmTerminal -> WasmType [ctor] .
  var N_LIST : Nat . 
  ceq typecheck(i, list(X)) = true 
   if (0 < (2 ^ 32)) .
  op char :  -> WasmType [ctor] .
 
  ceq typecheck(i, char) = true 
   if (((I >= 0) /\ (I <= 55295)) \/ ((I >= 57344) /\ (I <= 1114111))) .

  op $utf8 : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .


  op name :  -> WasmType [ctor] .
 
  ceq typecheck(i, name) = true 
   if (0 < (2 ^ 32)) .
  op idx :  -> WasmType [ctor] .
  eq typecheck(T, idx) =  typecheck(T, u32) .
  op laneidx :  -> WasmType [ctor] .
  eq typecheck(T, laneidx) =  typecheck(T, u8) .
  op typeidx :  -> WasmType [ctor] .
  eq typecheck(T, typeidx) =  typecheck(T, idx) .
  op funcidx :  -> WasmType [ctor] .
  eq typecheck(T, funcidx) =  typecheck(T, idx) .
  op globalidx :  -> WasmType [ctor] .
  eq typecheck(T, globalidx) =  typecheck(T, idx) .
  op tableidx :  -> WasmType [ctor] .
  eq typecheck(T, tableidx) =  typecheck(T, idx) .
  op memidx :  -> WasmType [ctor] .
  eq typecheck(T, memidx) =  typecheck(T, idx) .
  op tagidx :  -> WasmType [ctor] .
  eq typecheck(T, tagidx) =  typecheck(T, idx) .
  op elemidx :  -> WasmType [ctor] .
  eq typecheck(T, elemidx) =  typecheck(T, idx) .
  op dataidx :  -> WasmType [ctor] .
  eq typecheck(T, dataidx) =  typecheck(T, idx) .
  op labelidx :  -> WasmType [ctor] .
  eq typecheck(T, labelidx) =  typecheck(T, idx) .
  op localidx :  -> WasmType [ctor] .
  eq typecheck(T, localidx) =  typecheck(T, idx) .
  op fieldidx :  -> WasmType [ctor] .
  eq typecheck(T, fieldidx) =  typecheck(T, idx) .
  op externidx :  -> WasmType [ctor] .
  op FUNC _ : WasmTerminal -> WasmTerminal [ctor] .
  var FUNCIDX1 : WasmTerminal .
  eq typecheck(FUNC FUNCIDX1, externidx) = typecheck(FUNCIDX1, funcidx) .
  op GLOBAL _ : WasmTerminal -> WasmTerminal [ctor] .
  var GLOBALIDX1 : WasmTerminal .
  eq typecheck(GLOBAL GLOBALIDX1, externidx) = typecheck(GLOBALIDX1, globalidx) .
  op TABLE _ : WasmTerminal -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  eq typecheck(TABLE TABLEIDX1, externidx) = typecheck(TABLEIDX1, tableidx) .
  op MEM _ : WasmTerminal -> WasmTerminal [ctor] .
  var MEMIDX1 : WasmTerminal .
  eq typecheck(MEM MEMIDX1, externidx) = typecheck(MEMIDX1, memidx) .
  op TAG _ : WasmTerminal -> WasmTerminal [ctor] .
  var TAGIDX1 : WasmTerminal .
  eq typecheck(TAG TAGIDX1, externidx) = typecheck(TAGIDX1, tagidx) .

  op $funcsxx : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq funcsxx(0) = 0 .
  eq funcsxx(0) = 0 .
  eq funcsxx(0) = $funcsxx(0) .


  op $globalsxx : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq globalsxx(0) = 0 .
  eq globalsxx(0) = 0 .
  eq globalsxx(0) = $globalsxx(0) .


  op $tablesxx : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq tablesxx(0) = 0 .
  eq tablesxx(0) = 0 .
  eq tablesxx(0) = $tablesxx(0) .


  op $memsxx : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq memsxx(0) = 0 .
  eq memsxx(0) = 0 .
  eq memsxx(0) = $memsxx(0) .


  op $tagsxx : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq tagsxx(0) = 0 .
  eq tagsxx(0) = 0 .
  eq tagsxx(0) = $tagsxx(0) .

  op free :  -> WasmType [ctor] .


  op $free_opt : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq free_opt(0) = 0 .
  eq free_opt(0) = FREE .


  op $free_list : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq free_list(0) = 0 .
  eq free_list(0) = 0 .


  op $free_typeidx : WasmTerminal -> WasmTerminal .
  var TYPEIDX : WasmTerminal .
  var TYPEIDX : WasmTerminal .
  eq $free_typeidx(TYPEIDX) = 0 .


  op $free_funcidx : WasmTerminal -> WasmTerminal .
  var FUNCIDX : WasmTerminal .
  var FUNCIDX : WasmTerminal .
  eq $free_funcidx(FUNCIDX) = 0 .


  op $free_globalidx : WasmTerminal -> WasmTerminal .
  var GLOBALIDX : WasmTerminal .
  var GLOBALIDX : WasmTerminal .
  eq $free_globalidx(GLOBALIDX) = 0 .


  op $free_tableidx : WasmTerminal -> WasmTerminal .
  var TABLEIDX : WasmTerminal .
  var TABLEIDX : WasmTerminal .
  eq $free_tableidx(TABLEIDX) = 0 .


  op $free_memidx : WasmTerminal -> WasmTerminal .
  var MEMIDX : WasmTerminal .
  var MEMIDX : WasmTerminal .
  eq $free_memidx(MEMIDX) = 0 .


  op $free_elemidx : WasmTerminal -> WasmTerminal .
  var ELEMIDX : WasmTerminal .
  var ELEMIDX : WasmTerminal .
  eq $free_elemidx(ELEMIDX) = 0 .


  op $free_dataidx : WasmTerminal -> WasmTerminal .
  var DATAIDX : WasmTerminal .
  var DATAIDX : WasmTerminal .
  eq $free_dataidx(DATAIDX) = 0 .


  op $free_localidx : WasmTerminal -> WasmTerminal .
  var LOCALIDX : WasmTerminal .
  var LOCALIDX : WasmTerminal .
  eq $free_localidx(LOCALIDX) = 0 .


  op $free_labelidx : WasmTerminal -> WasmTerminal .
  var LABELIDX : WasmTerminal .
  var LABELIDX : WasmTerminal .
  eq $free_labelidx(LABELIDX) = 0 .


  op $free_externidx : WasmTerminal -> WasmTerminal .
  var EXTERNIDX : WasmTerminal .
  eq free_externidx(FUNC) = $free-funcidx(FUNCIDX) .
  eq free_externidx(GLOBAL) = $free-globalidx(GLOBALIDX) .
  eq free_externidx(TABLE) = $free-tableidx(TABLEIDX) .
  eq free_externidx(MEM) = $free-memidx(MEMIDX) .

  op null :  -> WasmType [ctor] .
  op NULL :  -> WasmTerminal [ctor] .
  eq typecheck(NULL, null) = true .
  op addrtype :  -> WasmType [ctor] .
  op I32 :  -> WasmTerminal [ctor] .
  eq typecheck(I32, addrtype) = true .
  op I64 :  -> WasmTerminal [ctor] .
  eq typecheck(I64, addrtype) = true .
  op numtype :  -> WasmType [ctor] .
  op I32 :  -> WasmTerminal [ctor] .
  eq typecheck(I32, numtype) = true .
  op I64 :  -> WasmTerminal [ctor] .
  eq typecheck(I64, numtype) = true .
  op F32 :  -> WasmTerminal [ctor] .
  eq typecheck(F32, numtype) = true .
  op F64 :  -> WasmTerminal [ctor] .
  eq typecheck(F64, numtype) = true .
  op vectype :  -> WasmType [ctor] .
  op V128 :  -> WasmTerminal [ctor] .
  eq typecheck(V128, vectype) = true .
  op consttype :  -> WasmType [ctor] .
  op I32 :  -> WasmTerminal [ctor] .
  eq typecheck(I32, consttype) = true .
  op I64 :  -> WasmTerminal [ctor] .
  eq typecheck(I64, consttype) = true .
  op F32 :  -> WasmTerminal [ctor] .
  eq typecheck(F32, consttype) = true .
  op F64 :  -> WasmTerminal [ctor] .
  eq typecheck(F64, consttype) = true .
  op V128 :  -> WasmTerminal [ctor] .
  eq typecheck(V128, consttype) = true .
  op absheaptype :  -> WasmType [ctor] .
  op ANY :  -> WasmTerminal [ctor] .
  eq typecheck(ANY, absheaptype) = true .
  op EQ :  -> WasmTerminal [ctor] .
  eq typecheck(EQ, absheaptype) = true .
  op I31 :  -> WasmTerminal [ctor] .
  eq typecheck(I31, absheaptype) = true .
  op STRUCT :  -> WasmTerminal [ctor] .
  eq typecheck(STRUCT, absheaptype) = true .
  op ARRAY :  -> WasmTerminal [ctor] .
  eq typecheck(ARRAY, absheaptype) = true .
  op NONE :  -> WasmTerminal [ctor] .
  eq typecheck(NONE, absheaptype) = true .
  op FUNC :  -> WasmTerminal [ctor] .
  eq typecheck(FUNC, absheaptype) = true .
  op NOFUNC :  -> WasmTerminal [ctor] .
  eq typecheck(NOFUNC, absheaptype) = true .
  op EXN :  -> WasmTerminal [ctor] .
  eq typecheck(EXN, absheaptype) = true .
  op NOEXN :  -> WasmTerminal [ctor] .
  eq typecheck(NOEXN, absheaptype) = true .
  op EXTERN :  -> WasmTerminal [ctor] .
  eq typecheck(EXTERN, absheaptype) = true .
  op NOEXTERN :  -> WasmTerminal [ctor] .
  eq typecheck(NOEXTERN, absheaptype) = true .
  op BOT :  -> WasmTerminal [ctor] .
  eq typecheck(BOT, absheaptype) = true .
  op mut :  -> WasmType [ctor] .
  op MUT :  -> WasmTerminal [ctor] .
  eq typecheck(MUT, mut) = true .
  op final :  -> WasmType [ctor] .
  op FINAL :  -> WasmTerminal [ctor] .
  eq typecheck(FINAL, final) = true .
  op typeuse :  -> WasmType [ctor] .
  op -IDX _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(-IDX TYPEIDX1, typeuse) = typecheck(TYPEIDX1, typeidx) .
  op -DEF _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var RECTYPE1 : WasmTerminal .
  var N1 : WasmTerminal .
  eq typecheck(-DEF RECTYPE1 N1, typeuse) = typecheck(RECTYPE1, rectype) /\ typecheck(N1, n) .
  op REC _ : WasmTerminal -> WasmTerminal [ctor] .
  var N1 : WasmTerminal .
  eq typecheck(REC N1, typeuse) = typecheck(N1, n) .
  op heaptype :  -> WasmType [ctor] .
  op ANY :  -> WasmTerminal [ctor] .
  eq typecheck(ANY, heaptype) = true .
  op EQ :  -> WasmTerminal [ctor] .
  eq typecheck(EQ, heaptype) = true .
  op I31 :  -> WasmTerminal [ctor] .
  eq typecheck(I31, heaptype) = true .
  op STRUCT :  -> WasmTerminal [ctor] .
  eq typecheck(STRUCT, heaptype) = true .
  op ARRAY :  -> WasmTerminal [ctor] .
  eq typecheck(ARRAY, heaptype) = true .
  op NONE :  -> WasmTerminal [ctor] .
  eq typecheck(NONE, heaptype) = true .
  op FUNC :  -> WasmTerminal [ctor] .
  eq typecheck(FUNC, heaptype) = true .
  op NOFUNC :  -> WasmTerminal [ctor] .
  eq typecheck(NOFUNC, heaptype) = true .
  op EXN :  -> WasmTerminal [ctor] .
  eq typecheck(EXN, heaptype) = true .
  op NOEXN :  -> WasmTerminal [ctor] .
  eq typecheck(NOEXN, heaptype) = true .
  op EXTERN :  -> WasmTerminal [ctor] .
  eq typecheck(EXTERN, heaptype) = true .
  op NOEXTERN :  -> WasmTerminal [ctor] .
  eq typecheck(NOEXTERN, heaptype) = true .
  op BOT :  -> WasmTerminal [ctor] .
  eq typecheck(BOT, heaptype) = true .
  op -IDX _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(-IDX TYPEIDX1, heaptype) = typecheck(TYPEIDX1, typeidx) .
  op REC _ : WasmTerminal -> WasmTerminal [ctor] .
  var N1 : WasmTerminal .
  eq typecheck(REC N1, heaptype) = typecheck(N1, n) .
  op -DEF _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var RECTYPE1 : WasmTerminal .
  var N1 : WasmTerminal .
  eq typecheck(-DEF RECTYPE1 N1, heaptype) = typecheck(RECTYPE1, rectype) /\ typecheck(N1, n) .
  op valtype :  -> WasmType [ctor] .
  op I32 :  -> WasmTerminal [ctor] .
  eq typecheck(I32, valtype) = true .
  op I64 :  -> WasmTerminal [ctor] .
  eq typecheck(I64, valtype) = true .
  op F32 :  -> WasmTerminal [ctor] .
  eq typecheck(F32, valtype) = true .
  op F64 :  -> WasmTerminal [ctor] .
  eq typecheck(F64, valtype) = true .
  op V128 :  -> WasmTerminal [ctor] .
  eq typecheck(V128, valtype) = true .
  op REF _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NULL1 : WasmTerminal .
  var HEAPTYPE1 : WasmTerminal .
  eq typecheck(REF NULL1 HEAPTYPE1, valtype) = typecheck(NULL1, null) /\ typecheck(HEAPTYPE1, heaptype) .
  op BOT :  -> WasmTerminal [ctor] .
  eq typecheck(BOT, valtype) = true .
  op storagetype :  -> WasmType [ctor] .
  op BOT :  -> WasmTerminal [ctor] .
  eq typecheck(BOT, storagetype) = true .
  op I32 :  -> WasmTerminal [ctor] .
  eq typecheck(I32, storagetype) = true .
  op I64 :  -> WasmTerminal [ctor] .
  eq typecheck(I64, storagetype) = true .
  op F32 :  -> WasmTerminal [ctor] .
  eq typecheck(F32, storagetype) = true .
  op F64 :  -> WasmTerminal [ctor] .
  eq typecheck(F64, storagetype) = true .
  op V128 :  -> WasmTerminal [ctor] .
  eq typecheck(V128, storagetype) = true .
  op REF _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NULL1 : WasmTerminal .
  var HEAPTYPE1 : WasmTerminal .
  eq typecheck(REF NULL1 HEAPTYPE1, storagetype) = typecheck(NULL1, null) /\ typecheck(HEAPTYPE1, heaptype) .
  op I8 :  -> WasmTerminal [ctor] .
  eq typecheck(I8, storagetype) = true .
  op I16 :  -> WasmTerminal [ctor] .
  eq typecheck(I16, storagetype) = true .
  op resulttype :  -> WasmType [ctor] .
  eq typecheck(T, resulttype) =  typecheck(T, list(valtype)) .
  op fieldtype :  -> WasmType [ctor] .

  var MUT1 : WasmTerminal .
  var STORAGETYPE1 : WasmTerminal .
  eq typecheck(MUT1 STORAGETYPE1, fieldtype) = typecheck(MUT1, mut) /\ typecheck(STORAGETYPE1, storagetype) .
  op comptype :  -> WasmType [ctor] .
  op STRUCT _ : WasmTerminal -> WasmTerminal [ctor] .
  var LIST1 : WasmTerminal .
  eq typecheck(STRUCT LIST1, comptype) = typecheck(LIST1, list(fieldtype)) .
  op ARRAY _ : WasmTerminal -> WasmTerminal [ctor] .
  var FIELDTYPE1 : WasmTerminal .
  eq typecheck(ARRAY FIELDTYPE1, comptype) = typecheck(FIELDTYPE1, fieldtype) .
  op FUNC _ _ : WasmTerminals WasmTerminals -> WasmTerminal [ctor] .
  var RESULTTYPE1 : WasmTerminals .
  var RESULTTYPE2 : WasmTerminals .
  eq typecheck(FUNC RESULTTYPE1 RESULTTYPE2, comptype) = typecheck(RESULTTYPE1, resulttype) /\ typecheck(RESULTTYPE2, resulttype) .
  op subtype :  -> WasmType [ctor] .
  op SUB _ _ _ : WasmTerminal WasmTerminals WasmTerminal -> WasmTerminal [ctor] .
  var FINAL1 : WasmTerminal .
  var TYPEUSE* : WasmTerminals .
  var COMPTYPE1 : WasmTerminal .
  eq typecheck(SUB FINAL1 TYPEUSE* COMPTYPE1, subtype) = typecheck(FINAL1, final) /\ typecheck(TYPEUSE*, typeuse) /\ typecheck(COMPTYPE1, comptype) .
  op rectype :  -> WasmType [ctor] .
  op REC _ : WasmTerminal -> WasmTerminal [ctor] .
  var LIST1 : WasmTerminal .
  eq typecheck(REC LIST1, rectype) = typecheck(LIST1, list(subtype)) .
  op deftype :  -> WasmType [ctor] .
  op -DEF _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var RECTYPE1 : WasmTerminal .
  var N1 : WasmTerminal .
  eq typecheck(-DEF RECTYPE1 N1, deftype) = typecheck(RECTYPE1, rectype) /\ typecheck(N1, n) .
  op typevar :  -> WasmType [ctor] .
  op -IDX _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(-IDX TYPEIDX1, typevar) = typecheck(TYPEIDX1, typeidx) .
  op REC _ : WasmTerminal -> WasmTerminal [ctor] .
  var N1 : WasmTerminal .
  eq typecheck(REC N1, typevar) = typecheck(N1, n) .
  op reftype :  -> WasmType [ctor] .
  op REF _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NULL1 : WasmTerminal .
  var HEAPTYPE1 : WasmTerminal .
  eq typecheck(REF NULL1 HEAPTYPE1, reftype) = typecheck(NULL1, null) /\ typecheck(HEAPTYPE1, heaptype) .
  op Inn :  -> WasmType [ctor] .
  eq typecheck(T, Inn) =  typecheck(T, addrtype) .
  op Fnn :  -> WasmType [ctor] .
  op F32 :  -> WasmTerminal [ctor] .
  eq typecheck(F32, Fnn) = true .
  op F64 :  -> WasmTerminal [ctor] .
  eq typecheck(F64, Fnn) = true .
  op Vnn :  -> WasmType [ctor] .
  eq typecheck(T, Vnn) =  typecheck(T, vectype) .
  op Cnn :  -> WasmType [ctor] .
  op I32 :  -> WasmTerminal [ctor] .
  eq typecheck(I32, Cnn) = true .
  op I64 :  -> WasmTerminal [ctor] .
  eq typecheck(I64, Cnn) = true .
  op F32 :  -> WasmTerminal [ctor] .
  eq typecheck(F32, Cnn) = true .
  op F64 :  -> WasmTerminal [ctor] .
  eq typecheck(F64, Cnn) = true .
  op V128 :  -> WasmTerminal [ctor] .
  eq typecheck(V128, Cnn) = true .

  op $ANYREF :  -> WasmTerminal .
  eq ANYREF = REF .


  op $EQREF :  -> WasmTerminal .
  eq EQREF = REF .


  op $I31REF :  -> WasmTerminal .
  eq I31REF = REF .


  op $STRUCTREF :  -> WasmTerminal .
  eq STRUCTREF = REF .


  op $ARRAYREF :  -> WasmTerminal .
  eq ARRAYREF = REF .


  op $FUNCREF :  -> WasmTerminal .
  eq FUNCREF = REF .


  op $EXNREF :  -> WasmTerminal .
  eq EXNREF = REF .


  op $EXTERNREF :  -> WasmTerminal .
  eq EXTERNREF = REF .


  op $NULLREF :  -> WasmTerminal .
  eq NULLREF = REF .


  op $NULLFUNCREF :  -> WasmTerminal .
  eq NULLFUNCREF = REF .


  op $NULLEXNREF :  -> WasmTerminal .
  eq NULLEXNREF = REF .


  op $NULLEXTERNREF :  -> WasmTerminal .
  eq NULLEXTERNREF = REF .

  op packtype :  -> WasmType [ctor] .
  op I8 :  -> WasmTerminal [ctor] .
  eq typecheck(I8, packtype) = true .
  op I16 :  -> WasmTerminal [ctor] .
  eq typecheck(I16, packtype) = true .
  op lanetype :  -> WasmType [ctor] .
  op I32 :  -> WasmTerminal [ctor] .
  eq typecheck(I32, lanetype) = true .
  op I64 :  -> WasmTerminal [ctor] .
  eq typecheck(I64, lanetype) = true .
  op F32 :  -> WasmTerminal [ctor] .
  eq typecheck(F32, lanetype) = true .
  op F64 :  -> WasmTerminal [ctor] .
  eq typecheck(F64, lanetype) = true .
  op I8 :  -> WasmTerminal [ctor] .
  eq typecheck(I8, lanetype) = true .
  op I16 :  -> WasmTerminal [ctor] .
  eq typecheck(I16, lanetype) = true .
  op Pnn :  -> WasmType [ctor] .
  eq typecheck(T, Pnn) =  typecheck(T, packtype) .
  op Jnn :  -> WasmType [ctor] .
  op I32 :  -> WasmTerminal [ctor] .
  eq typecheck(I32, Jnn) = true .
  op I64 :  -> WasmTerminal [ctor] .
  eq typecheck(I64, Jnn) = true .
  op I8 :  -> WasmTerminal [ctor] .
  eq typecheck(I8, Jnn) = true .
  op I16 :  -> WasmTerminal [ctor] .
  eq typecheck(I16, Jnn) = true .
  op Lnn :  -> WasmType [ctor] .
  eq typecheck(T, Lnn) =  typecheck(T, lanetype) .
  op limits :  -> WasmType [ctor] .
  op lbrack _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var U641 : WasmTerminal .
  var U642 : WasmTerminal .
  eq typecheck(lbrack U641 U642, limits) = typecheck(U641, u64) /\ typecheck(U642, u64) .
  op tagtype :  -> WasmType [ctor] .
  eq typecheck(T, tagtype) =  typecheck(T, typeuse) .
  op globaltype :  -> WasmType [ctor] .

  var MUT1 : WasmTerminal .
  var VALTYPE1 : WasmTerminal .
  eq typecheck(MUT1 VALTYPE1, globaltype) = typecheck(MUT1, mut) /\ typecheck(VALTYPE1, valtype) .
  op memtype :  -> WasmType [ctor] .
  op PAGE _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var ADDRTYPE1 : WasmTerminal .
  var LIMITS1 : WasmTerminal .
  eq typecheck(PAGE ADDRTYPE1 LIMITS1, memtype) = typecheck(ADDRTYPE1, addrtype) /\ typecheck(LIMITS1, limits) .
  op tabletype :  -> WasmType [ctor] .

  var ADDRTYPE1 : WasmTerminal .
  var LIMITS1 : WasmTerminal .
  var REFTYPE1 : WasmTerminal .
  eq typecheck(ADDRTYPE1 LIMITS1 REFTYPE1, tabletype) = typecheck(ADDRTYPE1, addrtype) /\ typecheck(LIMITS1, limits) /\ typecheck(REFTYPE1, reftype) .
  op datatype :  -> WasmType [ctor] .
  op OK :  -> WasmTerminal [ctor] .
  eq typecheck(OK, datatype) = true .
  op elemtype :  -> WasmType [ctor] .
  eq typecheck(T, elemtype) =  typecheck(T, reftype) .
  op externtype :  -> WasmType [ctor] .
  op TAG _ : WasmTerminal -> WasmTerminal [ctor] .
  var TAGTYPE1 : WasmTerminal .
  eq typecheck(TAG TAGTYPE1, externtype) = typecheck(TAGTYPE1, tagtype) .
  op GLOBAL _ : WasmTerminal -> WasmTerminal [ctor] .
  var GLOBALTYPE1 : WasmTerminal .
  eq typecheck(GLOBAL GLOBALTYPE1, externtype) = typecheck(GLOBALTYPE1, globaltype) .
  op MEM _ : WasmTerminal -> WasmTerminal [ctor] .
  var MEMTYPE1 : WasmTerminal .
  eq typecheck(MEM MEMTYPE1, externtype) = typecheck(MEMTYPE1, memtype) .
  op TABLE _ : WasmTerminal -> WasmTerminal [ctor] .
  var TABLETYPE1 : WasmTerminal .
  eq typecheck(TABLE TABLETYPE1, externtype) = typecheck(TABLETYPE1, tabletype) .
  op FUNC _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEUSE1 : WasmTerminal .
  eq typecheck(FUNC TYPEUSE1, externtype) = typecheck(TYPEUSE1, typeuse) .
  op moduletype :  -> WasmType [ctor] .
  op arrow _ _ : WasmTerminals WasmTerminals -> WasmTerminal [ctor] .
  var EXTERNTYPE* : WasmTerminals .
  var EXTERNTYPE* : WasmTerminals .
  eq typecheck(arrow EXTERNTYPE* EXTERNTYPE*, moduletype) = typecheck(EXTERNTYPE*, externtype) /\ typecheck(EXTERNTYPE*, externtype) .

  op $IN : WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  eq IN(32) = I32 .
  eq IN(64) = I64 .


  op $FN : WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  eq FN(32) = F32 .
  eq FN(64) = F64 .


  op $JN : WasmTerminal -> WasmTerminal .
  var N : WasmTerminal .
  eq JN(8) = I8 .
  eq JN(16) = I16 .
  eq JN(32) = I32 .
  eq JN(64) = I64 .


  op $size : WasmTerminal -> WasmTerminal .
  var NUMTYPE : WasmTerminal .
  eq size(I32) = 32 .
  eq size(I64) = 64 .
  eq size(F32) = 32 .
  eq size(F64) = 64 .


  op $vsize : WasmTerminal -> WasmTerminal .
  var VECTYPE : WasmTerminal .
  eq vsize(V128) = 128 .


  op $psize : WasmTerminal -> WasmTerminal .
  var PACKTYPE : WasmTerminal .
  eq psize(I8) = 8 .
  eq psize(I16) = 16 .


  op $lsize : WasmTerminal -> WasmTerminal .
  var LANETYPE : WasmTerminal .
  eq lsize(NUMTYPE) = $size(NUMTYPE) .
  eq lsize(PACKTYPE) = $psize(PACKTYPE) .


  op $zsize : WasmTerminal -> WasmTerminal .
  var STORAGETYPE : WasmTerminal .
  eq zsize(NUMTYPE) = $size(NUMTYPE) .
  eq zsize(VECTYPE) = $vsize(VECTYPE) .
  eq zsize(PACKTYPE) = $psize(PACKTYPE) .


  op $isize : WasmTerminal -> WasmTerminal .
  var INN : WasmTerminal .
  var INN : WasmTerminal .
  eq $isize(INN) = $size(INN) .


  op $jsize : WasmTerminal -> WasmTerminal .
  var JNN : WasmTerminal .
  var JNN : WasmTerminal .
  eq $jsize(JNN) = $lsize(JNN) .


  op $fsize : WasmTerminal -> WasmTerminal .
  var FNN : WasmTerminal .
  var FNN : WasmTerminal .
  eq $fsize(FNN) = $size(FNN) .


  op $inv_isize : WasmTerminal -> WasmTerminal .
  var NAT : WasmTerminal .
  eq inv_isize(32) = I32 .
  eq inv_isize(64) = I64 .


  op $inv_jsize : WasmTerminal -> WasmTerminal .
  var NAT : WasmTerminal .
  eq inv_jsize(8) = I8 .
  eq inv_jsize(16) = I16 .
  var N : WasmTerminal .
  eq $inv_jsize(N) = $inv-isize(N) .


  op $inv_fsize : WasmTerminal -> WasmTerminal .
  var NAT : WasmTerminal .
  eq inv_fsize(32) = F32 .
  eq inv_fsize(64) = F64 .


  op $sizenn : WasmTerminal -> WasmTerminal .
  var NUMTYPE : WasmTerminal .
  var NT : WasmTerminal .
  eq $sizenn(NT) = $size(NT) .


  op $sizenn1 : WasmTerminal -> WasmTerminal .
  var NUMTYPE : WasmTerminal .
  var NT : WasmTerminal .
  eq $sizenn1(NT) = $size(NT) .


  op $sizenn2 : WasmTerminal -> WasmTerminal .
  var NUMTYPE : WasmTerminal .
  var NT : WasmTerminal .
  eq $sizenn2(NT) = $size(NT) .


  op $vsizenn : WasmTerminal -> WasmTerminal .
  var VECTYPE : WasmTerminal .
  var VT : WasmTerminal .
  eq $vsizenn(VT) = $vsize(VT) .


  op $psizenn : WasmTerminal -> WasmTerminal .
  var PACKTYPE : WasmTerminal .
  var PT : WasmTerminal .
  eq $psizenn(PT) = $psize(PT) .


  op $lsizenn : WasmTerminal -> WasmTerminal .
  var LANETYPE : WasmTerminal .
  var LT : WasmTerminal .
  eq $lsizenn(LT) = $lsize(LT) .


  op $lsizenn1 : WasmTerminal -> WasmTerminal .
  var LANETYPE : WasmTerminal .
  var LT : WasmTerminal .
  eq $lsizenn1(LT) = $lsize(LT) .


  op $lsizenn2 : WasmTerminal -> WasmTerminal .
  var LANETYPE : WasmTerminal .
  var LT : WasmTerminal .
  eq $lsizenn2(LT) = $lsize(LT) .


  op $jsizenn : WasmTerminal -> WasmTerminal .
  var JNN : WasmTerminal .
  var JNN : WasmTerminal .
  eq $jsizenn(JNN) = $lsize(JNN) .


  op $inv_jsizenn : WasmTerminal -> WasmTerminal .
  var NAT : WasmTerminal .
  var N : WasmTerminal .
  eq $inv_jsizenn(N) = $inv-jsize(N) .


  op $lunpack : WasmTerminal -> WasmTerminal .
  var LANETYPE : WasmTerminal .
  eq lunpack(NUMTYPE) = NUMTYPE .
  eq lunpack(PACKTYPE) = I32 .


  op $unpack : WasmTerminal -> WasmTerminal .
  var STORAGETYPE : WasmTerminal .
  eq unpack(VALTYPE) = VALTYPE .
  eq unpack(PACKTYPE) = I32 .


  op $nunpack : WasmTerminal -> WasmTerminal .
  var STORAGETYPE : WasmTerminal .
  eq nunpack(NUMTYPE) = NUMTYPE .
  eq nunpack(PACKTYPE) = I32 .


  op $vunpack : WasmTerminal -> WasmTerminal .
  var STORAGETYPE : WasmTerminal .
  eq vunpack(VECTYPE) = VECTYPE .


  op $cunpack : WasmTerminal -> WasmTerminal .
  var STORAGETYPE : WasmTerminal .
  eq cunpack(CONSTTYPE) = CONSTTYPE .
  eq cunpack(PACKTYPE) = I32 .
  eq cunpack(LANETYPE) = $lunpack(LANETYPE) .


  op $minat : WasmTerminal WasmTerminal -> WasmTerminal .
  var ADDRTYPE : WasmTerminal .
  var ADDRTYPE : WasmTerminal .
  var AT_1 : WasmTerminal .
  eq $minat(AT_1) = AT_1 .
  var AT_1 : WasmTerminal .
  eq $minat(AT_1) = AT_2 .


  op $diffrt : WasmTerminal WasmTerminal -> WasmTerminal .
  var REFTYPE : WasmTerminal .
  var REFTYPE : WasmTerminal .
  eq diffrt(REF) = REF .
  eq diffrt(REF) = REF .


  op $as_deftype : WasmTerminal -> WasmTerminal .
  var TYPEUSE : WasmTerminal .
  eq as_deftype(DT) = DT .


  op $tagsxt : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq tagsxt(0) = 0 .
  eq tagsxt(0) = 0 .
  eq tagsxt(0) = $tagsxt(0) .


  op $globalsxt : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq globalsxt(0) = 0 .
  eq globalsxt(0) = 0 .
  eq globalsxt(0) = $globalsxt(0) .


  op $memsxt : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq memsxt(0) = 0 .
  eq memsxt(0) = 0 .
  eq memsxt(0) = $memsxt(0) .


  op $tablesxt : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq tablesxt(0) = 0 .
  eq tablesxt(0) = 0 .
  eq tablesxt(0) = $tablesxt(0) .


  op $funcsxt : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq funcsxt(0) = 0 .
  eq funcsxt(0) = 0 .
  eq funcsxt(0) = $funcsxt(0) .


  op $subst_typevar : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var TYPEVAR : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  var TV : WasmTerminal .
  eq $subst_typevar(TV) = TV .
  var TV : WasmTerminal .
  eq $subst_typevar(TV) = TU_1 .
  var TV : WasmTerminal .
  eq $subst_typevar(TV) = $subst-typevar(TV, 0, 0) .


  op $minus_recs : WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq minus_recs(0) = 0 .
  eq minus_recs(0) = $minus-recs(0, 0) .
  eq minus_recs(0) = 0 .


  op $subst_packtype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var PACKTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  var PT : WasmTerminal .
  eq $subst_packtype(PT) = PT .


  op $subst_numtype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var NUMTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  var NT : WasmTerminal .
  eq $subst_numtype(NT) = NT .


  op $subst_vectype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var VECTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  var VT : WasmTerminal .
  eq $subst_vectype(VT) = VT .


  op $subst_typeuse : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var TYPEUSE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_typeuse(TV') = $subst-typevar(TV', 0, 0) .
  eq subst_typeuse(DT) = $subst-deftype(DT, 0, 0) .


  op $subst_heaptype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var HEAPTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_heaptype(TV') = $subst-typevar(TV', 0, 0) .
  eq subst_heaptype(DT) = $subst-deftype(DT, 0, 0) .
  var HT : WasmTerminal .
  eq $subst_heaptype(HT) = HT .


  op $subst_reftype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var REFTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_reftype(REF) = REF .


  op $subst_valtype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var VALTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_valtype(NT) = $subst-numtype(NT, 0, 0) .
  eq subst_valtype(VT) = $subst-vectype(VT, 0, 0) .
  eq subst_valtype(RT) = $subst-reftype(RT, 0, 0) .
  eq subst_valtype(BOT) = BOT .


  op $subst_storagetype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var STORAGETYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_storagetype(T) = $subst-valtype(T, 0, 0) .
  eq subst_storagetype(PT) = $subst-packtype(PT, 0, 0) .


  op $subst_fieldtype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var FIELDTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_fieldtype(UNKNOWN_CASE) = UNKNOWN_CASE .


  op $subst_comptype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var COMPTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_comptype(STRUCT) = STRUCT .
  eq subst_comptype(ARRAY) = ARRAY .
  eq subst_comptype(FUNC) = FUNC .


  op $subst_subtype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var SUBTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_subtype(SUB) = SUB .


  op $subst_rectype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var RECTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_rectype(REC) = REC .


  op $subst_deftype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var DEFTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_deftype(_DEF) = _DEF .


  op $subst_addrtype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var ADDRTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  var AT : WasmTerminal .
  eq $subst_addrtype(AT) = AT .


  op $subst_tagtype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var TAGTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  var TU' : WasmTerminal .
  eq $subst_tagtype(TU') = $subst-typeuse(TU', 0, 0) .


  op $subst_globaltype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var GLOBALTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_globaltype(UNKNOWN_CASE) = UNKNOWN_CASE .


  op $subst_memtype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var MEMTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_memtype(UNKNOWN_CASE) = UNKNOWN_CASE .


  op $subst_tabletype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var TABLETYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_tabletype(UNKNOWN_CASE) = UNKNOWN_CASE .


  op $subst_externtype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var EXTERNTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_externtype(TAG) = TAG .
  eq subst_externtype(GLOBAL) = GLOBAL .
  eq subst_externtype(TABLE) = TABLE .
  eq subst_externtype(MEM) = MEM .
  eq subst_externtype(FUNC) = FUNC .


  op $subst_moduletype : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var MODULETYPE : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_moduletype(UNKNOWN_CASE) = UNKNOWN_CASE .


  op $subst_all_valtype : WasmTerminal WasmTerminal -> WasmTerminal .
  var VALTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var T : WasmTerminal .
  eq $subst_all_valtype(T) = $subst-valtype(T, 0, 0) .


  op $subst_all_reftype : WasmTerminal WasmTerminal -> WasmTerminal .
  var REFTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var RT : WasmTerminal .
  eq $subst_all_reftype(RT) = $subst-reftype(RT, 0, 0) .


  op $subst_all_deftype : WasmTerminal WasmTerminal -> WasmTerminal .
  var DEFTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var DT : WasmTerminal .
  eq $subst_all_deftype(DT) = $subst-deftype(DT, 0, 0) .


  op $subst_all_tagtype : WasmTerminal WasmTerminal -> WasmTerminal .
  var TAGTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var JT : WasmTerminal .
  eq $subst_all_tagtype(JT) = $subst-tagtype(JT, 0, 0) .


  op $subst_all_globaltype : WasmTerminal WasmTerminal -> WasmTerminal .
  var GLOBALTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var GT : WasmTerminal .
  eq $subst_all_globaltype(GT) = $subst-globaltype(GT, 0, 0) .


  op $subst_all_memtype : WasmTerminal WasmTerminal -> WasmTerminal .
  var MEMTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var MT : WasmTerminal .
  eq $subst_all_memtype(MT) = $subst-memtype(MT, 0, 0) .


  op $subst_all_tabletype : WasmTerminal WasmTerminal -> WasmTerminal .
  var TABLETYPE : WasmTerminal .
  var _ : WasmTerminal .
  var TT : WasmTerminal .
  eq $subst_all_tabletype(TT) = $subst-tabletype(TT, 0, 0) .


  op $subst_all_externtype : WasmTerminal WasmTerminal -> WasmTerminal .
  var EXTERNTYPE : WasmTerminal .
  var _ : WasmTerminal .
  var XT : WasmTerminal .
  eq $subst_all_externtype(XT) = $subst-externtype(XT, 0, 0) .


  op $subst_all_moduletype : WasmTerminal WasmTerminal -> WasmTerminal .
  var MODULETYPE : WasmTerminal .
  var _ : WasmTerminal .
  var MMT : WasmTerminal .
  eq $subst_all_moduletype(MMT) = $subst-moduletype(MMT, 0, 0) .


  op $subst_all_deftypes : WasmTerminal WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  eq subst_all_deftypes(0) = 0 .
  eq subst_all_deftypes(0) = 0 .


  op $rollrt : WasmTerminal WasmTerminal -> WasmTerminal .
  var TYPEIDX : WasmTerminal .
  var RECTYPE : WasmTerminal .
  var X : WasmTerminal .
  eq $rollrt(X) = REC .


  op $unrollrt : WasmTerminal -> WasmTerminal .
  var RECTYPE : WasmTerminal .
  var RECTYPE : WasmTerminal .
  eq $unrollrt(RECTYPE) = REC .


  op $rolldt : WasmTerminal WasmTerminal -> WasmTerminal .
  var TYPEIDX : WasmTerminal .
  var RECTYPE : WasmTerminal .
  var X : WasmTerminal .
  eq $rolldt(X) = 0 .


  op $unrolldt : WasmTerminal -> WasmTerminal .
  var DEFTYPE : WasmTerminal .
  eq unrolldt(_DEF) = 0 .


  op $expanddt : WasmTerminal -> WasmTerminal .
  var DEFTYPE : WasmTerminal .
  var DEFTYPE : WasmTerminal .
  eq $expanddt(DEFTYPE) = COMPTYPE .


  op $free_addrtype : WasmTerminal -> WasmTerminal .
  var NUMTYPE : WasmTerminal .
  eq free_addrtype(ADDRTYPE) = 0 .


  op $free_numtype : WasmTerminal -> WasmTerminal .
  var NUMTYPE : WasmTerminal .
  var NUMTYPE : WasmTerminal .
  eq $free_numtype(NUMTYPE) = 0 .


  op $free_packtype : WasmTerminal -> WasmTerminal .
  var PACKTYPE : WasmTerminal .
  var PACKTYPE : WasmTerminal .
  eq $free_packtype(PACKTYPE) = 0 .


  op $free_lanetype : WasmTerminal -> WasmTerminal .
  var LANETYPE : WasmTerminal .
  eq free_lanetype(NUMTYPE) = $free-numtype(NUMTYPE) .
  eq free_lanetype(PACKTYPE) = $free-packtype(PACKTYPE) .


  op $free_vectype : WasmTerminal -> WasmTerminal .
  var VECTYPE : WasmTerminal .
  var VECTYPE : WasmTerminal .
  eq $free_vectype(VECTYPE) = 0 .


  op $free_consttype : WasmTerminal -> WasmTerminal .
  var CONSTTYPE : WasmTerminal .
  eq free_consttype(NUMTYPE) = $free-numtype(NUMTYPE) .
  eq free_consttype(VECTYPE) = $free-vectype(VECTYPE) .


  op $free_absheaptype : WasmTerminal -> WasmTerminal .
  var ABSHEAPTYPE : WasmTerminal .
  var ABSHEAPTYPE : WasmTerminal .
  eq $free_absheaptype(ABSHEAPTYPE) = 0 .


  op $free_typevar : WasmTerminal -> WasmTerminal .
  var TYPEVAR : WasmTerminal .
  eq free_typevar(_IDX) = $free-typeidx(TYPEIDX) .
  eq free_typevar(REC) = 0 .


  op $free_heaptype : WasmTerminal -> WasmTerminal .
  var HEAPTYPE : WasmTerminal .
  eq free_heaptype(ABSHEAPTYPE) = $free-absheaptype(ABSHEAPTYPE) .
  eq free_heaptype(TYPEUSE) = $free-typeuse(TYPEUSE) .


  op $free_reftype : WasmTerminal -> WasmTerminal .
  var REFTYPE : WasmTerminal .
  eq free_reftype(REF) = $free-heaptype(HEAPTYPE) .


  op $free_typeuse : WasmTerminal -> WasmTerminal .
  var TYPEUSE : WasmTerminal .
  eq free_typeuse(TYPEVAR) = $free-typevar(TYPEVAR) .
  eq free_typeuse(DEFTYPE) = $free-deftype(DEFTYPE) .


  op $free_valtype : WasmTerminal -> WasmTerminal .
  var VALTYPE : WasmTerminal .
  eq free_valtype(NUMTYPE) = $free-numtype(NUMTYPE) .
  eq free_valtype(VECTYPE) = $free-vectype(VECTYPE) .
  eq free_valtype(REFTYPE) = $free-reftype(REFTYPE) .
  eq free_valtype(BOT) = 0 .


  op $free_resulttype : WasmTerminal -> WasmTerminal .
  var RESULTTYPE : WasmTerminal .
  eq free_resulttype(UNKNOWN_CASE) = $free-list(0) .


  op $free_storagetype : WasmTerminal -> WasmTerminal .
  var STORAGETYPE : WasmTerminal .
  eq free_storagetype(VALTYPE) = $free-valtype(VALTYPE) .
  eq free_storagetype(PACKTYPE) = $free-packtype(PACKTYPE) .


  op $free_fieldtype : WasmTerminal -> WasmTerminal .
  var FIELDTYPE : WasmTerminal .
  eq free_fieldtype(UNKNOWN_CASE) = $free-storagetype(STORAGETYPE) .


  op $free_comptype : WasmTerminal -> WasmTerminal .
  var COMPTYPE : WasmTerminal .
  eq free_comptype(STRUCT) = $free-list(0) .
  eq free_comptype(ARRAY) = $free-fieldtype(FIELDTYPE) .
  eq free_comptype(FUNC) = 0 .


  op $free_subtype : WasmTerminal -> WasmTerminal .
  var SUBTYPE : WasmTerminal .
  eq free_subtype(SUB) = 0 .


  op $free_rectype : WasmTerminal -> WasmTerminal .
  var RECTYPE : WasmTerminal .
  eq free_rectype(REC) = $free-list(0) .


  op $free_deftype : WasmTerminal -> WasmTerminal .
  var DEFTYPE : WasmTerminal .
  eq free_deftype(_DEF) = $free-rectype(RECTYPE) .


  op $free_tagtype : WasmTerminal -> WasmTerminal .
  var TAGTYPE : WasmTerminal .
  eq free_tagtype(DEFTYPE) = $free-deftype(DEFTYPE) .


  op $free_globaltype : WasmTerminal -> WasmTerminal .
  var GLOBALTYPE : WasmTerminal .
  eq free_globaltype(UNKNOWN_CASE) = $free-valtype(VALTYPE) .


  op $free_memtype : WasmTerminal -> WasmTerminal .
  var MEMTYPE : WasmTerminal .
  eq free_memtype(UNKNOWN_CASE) = $free-addrtype(ADDRTYPE) .


  op $free_tabletype : WasmTerminal -> WasmTerminal .
  var TABLETYPE : WasmTerminal .
  eq free_tabletype(UNKNOWN_CASE) = 0 .


  op $free_datatype : WasmTerminal -> WasmTerminal .
  var DATATYPE : WasmTerminal .
  eq free_datatype(OK) = 0 .


  op $free_elemtype : WasmTerminal -> WasmTerminal .
  var ELEMTYPE : WasmTerminal .
  var REFTYPE : WasmTerminal .
  eq $free_elemtype(REFTYPE) = $free-reftype(REFTYPE) .


  op $free_externtype : WasmTerminal -> WasmTerminal .
  var EXTERNTYPE : WasmTerminal .
  eq free_externtype(TAG) = $free-tagtype(TAGTYPE) .
  eq free_externtype(GLOBAL) = $free-globaltype(GLOBALTYPE) .
  eq free_externtype(MEM) = $free-memtype(MEMTYPE) .
  eq free_externtype(TABLE) = $free-tabletype(TABLETYPE) .
  eq free_externtype(FUNC) = $free-typeuse(TYPEUSE) .


  op $free_moduletype : WasmTerminal -> WasmTerminal .
  var MODULETYPE : WasmTerminal .
  eq free_moduletype(UNKNOWN_CASE) = 0 .

  op num- : WasmTerminal -> WasmType [ctor] .
  eq typecheck(T, num-(INN)) = typecheck(INN, Inn) /\  typecheck(T, iN($sizenn(INN))) .
  eq typecheck(T, num-(FNN)) = typecheck(FNN, Fnn) /\  typecheck(T, fN($sizenn(FNN))) .
  op pack- : WasmTerminal -> WasmType [ctor] .
  eq typecheck(T, pack-(PNN)) = typecheck(PNN, Pnn) /\  typecheck(T, iN($psizenn(PNN))) .
  op lane- : WasmTerminal -> WasmType [ctor] .
  eq typecheck(T, lane-(NUMTYPE)) = typecheck(NUMTYPE, numtype) /\  typecheck(T, num-(NUMTYPE)) .
  eq typecheck(T, lane-(PACKTYPE)) = typecheck(PACKTYPE, packtype) /\  typecheck(T, pack-(PACKTYPE)) .
  eq typecheck(T, lane-(JNN)) = typecheck(JNN, Jnn) /\  typecheck(T, iN($lsize(JNN))) .
  op vec- : WasmTerminal -> WasmType [ctor] .
  eq typecheck(T, vec-(VNN)) = typecheck(VNN, Vnn) /\  typecheck(T, vN($vsize(VNN))) .
  op lit- : WasmTerminal -> WasmType [ctor] .
  eq typecheck(T, lit-(NUMTYPE)) = typecheck(NUMTYPE, numtype) /\  typecheck(T, num-(NUMTYPE)) .
  eq typecheck(T, lit-(VECTYPE)) = typecheck(VECTYPE, vectype) /\  typecheck(T, vec-(VECTYPE)) .
  eq typecheck(T, lit-(PACKTYPE)) = typecheck(PACKTYPE, packtype) /\  typecheck(T, pack-(PACKTYPE)) .
  op sz :  -> WasmType [ctor] .
 
  ceq typecheck(i, sz) = true 
   if ((((I == 8) \/ (I == 16)) \/ (I == 32)) \/ (I == 64)) .
  op sx :  -> WasmType [ctor] .
  op U :  -> WasmTerminal [ctor] .
  eq typecheck(U, sx) = true .
  op S :  -> WasmTerminal [ctor] .
  eq typecheck(S, sx) = true .
  op unop- : WasmTerminal -> WasmType [ctor] .
  op CLZ :  -> WasmTerminal [ctor] .
  eq typecheck(CLZ, unop-(INN)) = typecheck(INN, Inn) .
  op CTZ :  -> WasmTerminal [ctor] .
  eq typecheck(CTZ, unop-(INN)) = typecheck(INN, Inn) .
  op POPCNT :  -> WasmTerminal [ctor] .
  eq typecheck(POPCNT, unop-(INN)) = typecheck(INN, Inn) .
  var N_UNOP- : Nat . 
  ceq typecheck(i, unop-(INN)) = true 
   if typecheck(INN, Inn) /\ (0 < $sizenn(INN)) .
  op ABS :  -> WasmTerminal [ctor] .
  eq typecheck(ABS, unop-(FNN)) = typecheck(FNN, Fnn) .
  op NEG :  -> WasmTerminal [ctor] .
  eq typecheck(NEG, unop-(FNN)) = typecheck(FNN, Fnn) .
  op SQRT :  -> WasmTerminal [ctor] .
  eq typecheck(SQRT, unop-(FNN)) = typecheck(FNN, Fnn) .
  op CEIL :  -> WasmTerminal [ctor] .
  eq typecheck(CEIL, unop-(FNN)) = typecheck(FNN, Fnn) .
  op FLOOR :  -> WasmTerminal [ctor] .
  eq typecheck(FLOOR, unop-(FNN)) = typecheck(FNN, Fnn) .
  op TRUNC :  -> WasmTerminal [ctor] .
  eq typecheck(TRUNC, unop-(FNN)) = typecheck(FNN, Fnn) .
  op NEAREST :  -> WasmTerminal [ctor] .
  eq typecheck(NEAREST, unop-(FNN)) = typecheck(FNN, Fnn) .
  op binop- : WasmTerminal -> WasmType [ctor] .
  op ADD :  -> WasmTerminal [ctor] .
  eq typecheck(ADD, binop-(INN)) = typecheck(INN, Inn) .
  op SUB :  -> WasmTerminal [ctor] .
  eq typecheck(SUB, binop-(INN)) = typecheck(INN, Inn) .
  op MUL :  -> WasmTerminal [ctor] .
  eq typecheck(MUL, binop-(INN)) = typecheck(INN, Inn) .
  op DIV _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(DIV SX1, binop-(INN)) = typecheck(INN, Inn) /\ typecheck(SX1, sx) .
  op REM _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(REM SX1, binop-(INN)) = typecheck(INN, Inn) /\ typecheck(SX1, sx) .
  op AND :  -> WasmTerminal [ctor] .
  eq typecheck(AND, binop-(INN)) = typecheck(INN, Inn) .
  op OR :  -> WasmTerminal [ctor] .
  eq typecheck(OR, binop-(INN)) = typecheck(INN, Inn) .
  op XOR :  -> WasmTerminal [ctor] .
  eq typecheck(XOR, binop-(INN)) = typecheck(INN, Inn) .
  op SHL :  -> WasmTerminal [ctor] .
  eq typecheck(SHL, binop-(INN)) = typecheck(INN, Inn) .
  op SHR _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(SHR SX1, binop-(INN)) = typecheck(INN, Inn) /\ typecheck(SX1, sx) .
  op ROTL :  -> WasmTerminal [ctor] .
  eq typecheck(ROTL, binop-(INN)) = typecheck(INN, Inn) .
  op ROTR :  -> WasmTerminal [ctor] .
  eq typecheck(ROTR, binop-(INN)) = typecheck(INN, Inn) .
  op ADD :  -> WasmTerminal [ctor] .
  eq typecheck(ADD, binop-(FNN)) = typecheck(FNN, Fnn) .
  op SUB :  -> WasmTerminal [ctor] .
  eq typecheck(SUB, binop-(FNN)) = typecheck(FNN, Fnn) .
  op MUL :  -> WasmTerminal [ctor] .
  eq typecheck(MUL, binop-(FNN)) = typecheck(FNN, Fnn) .
  op DIV :  -> WasmTerminal [ctor] .
  eq typecheck(DIV, binop-(FNN)) = typecheck(FNN, Fnn) .
  op MIN :  -> WasmTerminal [ctor] .
  eq typecheck(MIN, binop-(FNN)) = typecheck(FNN, Fnn) .
  op MAX :  -> WasmTerminal [ctor] .
  eq typecheck(MAX, binop-(FNN)) = typecheck(FNN, Fnn) .
  op COPYSIGN :  -> WasmTerminal [ctor] .
  eq typecheck(COPYSIGN, binop-(FNN)) = typecheck(FNN, Fnn) .
  op testop- : WasmTerminal -> WasmType [ctor] .
  op EQZ :  -> WasmTerminal [ctor] .
  eq typecheck(EQZ, testop-(INN)) = typecheck(INN, Inn) .
  op relop- : WasmTerminal -> WasmType [ctor] .
  op EQ :  -> WasmTerminal [ctor] .
  eq typecheck(EQ, relop-(INN)) = typecheck(INN, Inn) .
  op NE :  -> WasmTerminal [ctor] .
  eq typecheck(NE, relop-(INN)) = typecheck(INN, Inn) .
  op LT _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(LT SX1, relop-(INN)) = typecheck(INN, Inn) /\ typecheck(SX1, sx) .
  op GT _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(GT SX1, relop-(INN)) = typecheck(INN, Inn) /\ typecheck(SX1, sx) .
  op LE _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(LE SX1, relop-(INN)) = typecheck(INN, Inn) /\ typecheck(SX1, sx) .
  op GE _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(GE SX1, relop-(INN)) = typecheck(INN, Inn) /\ typecheck(SX1, sx) .
  op EQ :  -> WasmTerminal [ctor] .
  eq typecheck(EQ, relop-(FNN)) = typecheck(FNN, Fnn) .
  op NE :  -> WasmTerminal [ctor] .
  eq typecheck(NE, relop-(FNN)) = typecheck(FNN, Fnn) .
  op LT :  -> WasmTerminal [ctor] .
  eq typecheck(LT, relop-(FNN)) = typecheck(FNN, Fnn) .
  op GT :  -> WasmTerminal [ctor] .
  eq typecheck(GT, relop-(FNN)) = typecheck(FNN, Fnn) .
  op LE :  -> WasmTerminal [ctor] .
  eq typecheck(LE, relop-(FNN)) = typecheck(FNN, Fnn) .
  op GE :  -> WasmTerminal [ctor] .
  eq typecheck(GE, relop-(FNN)) = typecheck(FNN, Fnn) .
  op cvtop-- : WasmTerminal -> WasmType [ctor] .
  var N_CVTOP-- : Nat . 
  ceq typecheck(i, cvtop--(INN-1, INN-2)) = true 
   if typecheck(INN-1, Inn-1) /\ typecheck(INN-2, Inn-2) /\ ($sizenn1(INN-1) < $sizenn2(INN-2)) .
  var N_CVTOP-- : Nat . 
  ceq typecheck(i, cvtop--(INN-1, INN-2)) = true 
   if typecheck(INN-1, Inn-1) /\ typecheck(INN-2, Inn-2) /\ ($sizenn1(INN-1) > $sizenn2(INN-2)) .
  op CONVERT _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(CONVERT SX1, cvtop--(INN-1, FNN-2)) = typecheck(INN-1, Inn-1) /\ typecheck(FNN-2, Fnn-2) /\ typecheck(SX1, sx) .
  var N_CVTOP-- : Nat . 
  ceq typecheck(i, cvtop--(INN-1, FNN-2)) = true 
   if typecheck(INN-1, Inn-1) /\ typecheck(FNN-2, Fnn-2) /\ ($sizenn1(INN-1) == $sizenn2(FNN-2)) .
  op TRUNC _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(TRUNC SX1, cvtop--(FNN-1, INN-2)) = typecheck(FNN-1, Fnn-1) /\ typecheck(INN-2, Inn-2) /\ typecheck(SX1, sx) .
  op TRUNC-SAT _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(TRUNC-SAT SX1, cvtop--(FNN-1, INN-2)) = typecheck(FNN-1, Fnn-1) /\ typecheck(INN-2, Inn-2) /\ typecheck(SX1, sx) .
  var N_CVTOP-- : Nat . 
  ceq typecheck(i, cvtop--(FNN-1, INN-2)) = true 
   if typecheck(FNN-1, Fnn-1) /\ typecheck(INN-2, Inn-2) /\ ($sizenn1(FNN-1) == $sizenn2(INN-2)) .
  var N_CVTOP-- : Nat . 
  ceq typecheck(i, cvtop--(FNN-1, FNN-2)) = true 
   if typecheck(FNN-1, Fnn-1) /\ typecheck(FNN-2, Fnn-2) /\ ($sizenn1(FNN-1) < $sizenn2(FNN-2)) .
  var N_CVTOP-- : Nat . 
  ceq typecheck(i, cvtop--(FNN-1, FNN-2)) = true 
   if typecheck(FNN-1, Fnn-1) /\ typecheck(FNN-2, Fnn-2) /\ ($sizenn1(FNN-1) > $sizenn2(FNN-2)) .
  op dim :  -> WasmType [ctor] .
 
  ceq typecheck(i, dim) = true 
   if (((((I == 1) \/ (I == 2)) \/ (I == 4)) \/ (I == 8)) \/ (I == 16)) .
  op shape :  -> WasmType [ctor] .
 
  ceq typecheck(i, shape) = true 
   if (($lsize(LANETYPE) * 0) == 128) .

  op $dim : WasmTerminal -> WasmTerminal .
  var SHAPE : WasmTerminal .
  eq dim(UNKNOWN_CASE) = UNKNOWN_CASE .


  op $lanetype : WasmTerminal -> WasmTerminal .
  var SHAPE : WasmTerminal .
  eq lanetype(UNKNOWN_CASE) = LNN .


  op $unpackshape : WasmTerminal -> WasmTerminal .
  var SHAPE : WasmTerminal .
  eq unpackshape(UNKNOWN_CASE) = $lunpack(LNN) .

  op ishape :  -> WasmType [ctor] .
 
  ceq typecheck(i, ishape) = true 
   if ($lanetype(SHAPE) == JNN) .
  op bshape :  -> WasmType [ctor] .
 
  ceq typecheck(i, bshape) = true 
   if ($lanetype(SHAPE) == I8) .
  op zero :  -> WasmType [ctor] .
  op ZERO :  -> WasmTerminal [ctor] .
  eq typecheck(ZERO, zero) = true .
  op half :  -> WasmType [ctor] .
  op LOW :  -> WasmTerminal [ctor] .
  eq typecheck(LOW, half) = true .
  op HIGH :  -> WasmTerminal [ctor] .
  eq typecheck(HIGH, half) = true .
  op vvunop :  -> WasmType [ctor] .
  op NOT :  -> WasmTerminal [ctor] .
  eq typecheck(NOT, vvunop) = true .
  op vvbinop :  -> WasmType [ctor] .
  op AND :  -> WasmTerminal [ctor] .
  eq typecheck(AND, vvbinop) = true .
  op ANDNOT :  -> WasmTerminal [ctor] .
  eq typecheck(ANDNOT, vvbinop) = true .
  op OR :  -> WasmTerminal [ctor] .
  eq typecheck(OR, vvbinop) = true .
  op XOR :  -> WasmTerminal [ctor] .
  eq typecheck(XOR, vvbinop) = true .
  op vvternop :  -> WasmType [ctor] .
  op BITSELECT :  -> WasmTerminal [ctor] .
  eq typecheck(BITSELECT, vvternop) = true .
  op vvtestop :  -> WasmType [ctor] .
  op ANY-TRUE :  -> WasmTerminal [ctor] .
  eq typecheck(ANY-TRUE, vvtestop) = true .
  op vunop- : WasmTerminal -> WasmType [ctor] .
  op ABS :  -> WasmTerminal [ctor] .
  eq typecheck(ABS, vunop-(UNKNOWN_CASE)) = typecheck(JNN, Jnn) /\ typecheck(M, M) .
  op NEG :  -> WasmTerminal [ctor] .
  eq typecheck(NEG, vunop-(UNKNOWN_CASE)) = typecheck(JNN, Jnn) /\ typecheck(M, M) .
  var N_VUNOP- : Nat . 
  ceq typecheck(i, vunop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ ($lsizenn(JNN) == 8) .
  op ABS :  -> WasmTerminal [ctor] .
  eq typecheck(ABS, vunop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op NEG :  -> WasmTerminal [ctor] .
  eq typecheck(NEG, vunop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op SQRT :  -> WasmTerminal [ctor] .
  eq typecheck(SQRT, vunop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op CEIL :  -> WasmTerminal [ctor] .
  eq typecheck(CEIL, vunop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op FLOOR :  -> WasmTerminal [ctor] .
  eq typecheck(FLOOR, vunop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op TRUNC :  -> WasmTerminal [ctor] .
  eq typecheck(TRUNC, vunop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op NEAREST :  -> WasmTerminal [ctor] .
  eq typecheck(NEAREST, vunop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op vbinop- : WasmTerminal -> WasmType [ctor] .
  op ADD :  -> WasmTerminal [ctor] .
  eq typecheck(ADD, vbinop-(UNKNOWN_CASE)) = typecheck(JNN, Jnn) /\ typecheck(M, M) .
  op SUB :  -> WasmTerminal [ctor] .
  eq typecheck(SUB, vbinop-(UNKNOWN_CASE)) = typecheck(JNN, Jnn) /\ typecheck(M, M) .
  var N_VBINOP- : Nat . 
  ceq typecheck(i, vbinop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ ($lsizenn(JNN) <= 16) .
  var N_VBINOP- : Nat . 
  ceq typecheck(i, vbinop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ ($lsizenn(JNN) <= 16) .
  var N_VBINOP- : Nat . 
  ceq typecheck(i, vbinop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ ($lsizenn(JNN) >= 16) .
  var N_VBINOP- : Nat . 
  ceq typecheck(i, vbinop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ ($lsizenn(JNN) <= 16) .
  var N_VBINOP- : Nat . 
  ceq typecheck(i, vbinop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ ($lsizenn(JNN) == 16) .
  var N_VBINOP- : Nat . 
  ceq typecheck(i, vbinop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ ($lsizenn(JNN) == 16) .
  var N_VBINOP- : Nat . 
  ceq typecheck(i, vbinop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ ($lsizenn(JNN) <= 32) .
  var N_VBINOP- : Nat . 
  ceq typecheck(i, vbinop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ ($lsizenn(JNN) <= 32) .
  op ADD :  -> WasmTerminal [ctor] .
  eq typecheck(ADD, vbinop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op SUB :  -> WasmTerminal [ctor] .
  eq typecheck(SUB, vbinop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op MUL :  -> WasmTerminal [ctor] .
  eq typecheck(MUL, vbinop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op DIV :  -> WasmTerminal [ctor] .
  eq typecheck(DIV, vbinop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op MIN :  -> WasmTerminal [ctor] .
  eq typecheck(MIN, vbinop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op MAX :  -> WasmTerminal [ctor] .
  eq typecheck(MAX, vbinop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op PMIN :  -> WasmTerminal [ctor] .
  eq typecheck(PMIN, vbinop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op PMAX :  -> WasmTerminal [ctor] .
  eq typecheck(PMAX, vbinop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op RELAXED-MIN :  -> WasmTerminal [ctor] .
  eq typecheck(RELAXED-MIN, vbinop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op RELAXED-MAX :  -> WasmTerminal [ctor] .
  eq typecheck(RELAXED-MAX, vbinop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op vternop- : WasmTerminal -> WasmType [ctor] .
  op RELAXED-LANESELECT :  -> WasmTerminal [ctor] .
  eq typecheck(RELAXED-LANESELECT, vternop-(UNKNOWN_CASE)) = typecheck(JNN, Jnn) /\ typecheck(M, M) .
  op RELAXED-MADD :  -> WasmTerminal [ctor] .
  eq typecheck(RELAXED-MADD, vternop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op RELAXED-NMADD :  -> WasmTerminal [ctor] .
  eq typecheck(RELAXED-NMADD, vternop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op vtestop- : WasmTerminal -> WasmType [ctor] .
  op ALL-TRUE :  -> WasmTerminal [ctor] .
  eq typecheck(ALL-TRUE, vtestop-(UNKNOWN_CASE)) = typecheck(JNN, Jnn) /\ typecheck(M, M) .
  op vrelop- : WasmTerminal -> WasmType [ctor] .
  op EQ :  -> WasmTerminal [ctor] .
  eq typecheck(EQ, vrelop-(UNKNOWN_CASE)) = typecheck(JNN, Jnn) /\ typecheck(M, M) .
  op NE :  -> WasmTerminal [ctor] .
  eq typecheck(NE, vrelop-(UNKNOWN_CASE)) = typecheck(JNN, Jnn) /\ typecheck(M, M) .
  var N_VRELOP- : Nat . 
  ceq typecheck(i, vrelop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ (($lsizenn(JNN) =/= 64) \/ (SX == S)) .
  var N_VRELOP- : Nat . 
  ceq typecheck(i, vrelop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ (($lsizenn(JNN) =/= 64) \/ (SX == S)) .
  var N_VRELOP- : Nat . 
  ceq typecheck(i, vrelop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ (($lsizenn(JNN) =/= 64) \/ (SX == S)) .
  var N_VRELOP- : Nat . 
  ceq typecheck(i, vrelop-(UNKNOWN_CASE)) = true 
   if typecheck(JNN, Jnn) /\ typecheck(M, M) /\ (($lsizenn(JNN) =/= 64) \/ (SX == S)) .
  op EQ :  -> WasmTerminal [ctor] .
  eq typecheck(EQ, vrelop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op NE :  -> WasmTerminal [ctor] .
  eq typecheck(NE, vrelop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op LT :  -> WasmTerminal [ctor] .
  eq typecheck(LT, vrelop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op GT :  -> WasmTerminal [ctor] .
  eq typecheck(GT, vrelop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op LE :  -> WasmTerminal [ctor] .
  eq typecheck(LE, vrelop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op GE :  -> WasmTerminal [ctor] .
  eq typecheck(GE, vrelop-(UNKNOWN_CASE)) = typecheck(FNN, Fnn) /\ typecheck(M, M) .
  op vshiftop- : WasmTerminal -> WasmType [ctor] .
  op SHL :  -> WasmTerminal [ctor] .
  eq typecheck(SHL, vshiftop-(UNKNOWN_CASE)) = typecheck(JNN, Jnn) /\ typecheck(M, M) .
  op SHR _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(SHR SX1, vshiftop-(UNKNOWN_CASE)) = typecheck(JNN, Jnn) /\ typecheck(M, M) /\ typecheck(SX1, sx) .
  op vswizzlop- : WasmTerminal -> WasmType [ctor] .
  op SWIZZLE :  -> WasmTerminal [ctor] .
  eq typecheck(SWIZZLE, vswizzlop-(UNKNOWN_CASE)) = typecheck(M, M) .
  op RELAXED-SWIZZLE :  -> WasmTerminal [ctor] .
  eq typecheck(RELAXED-SWIZZLE, vswizzlop-(UNKNOWN_CASE)) = typecheck(M, M) .
  op vextunop-- : WasmTerminal -> WasmType [ctor] .
  var N_VEXTUNOP-- : Nat . 
  ceq typecheck(i, vextunop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(JNN-1, Jnn-1) /\ typecheck(M-1, M-1) /\ typecheck(JNN-2, Jnn-2) /\ typecheck(M-2, M-2) /\ ((16 <= (2 * $lsizenn1(JNN-1))) /\ (((2 * $lsizenn1(JNN-1)) == $lsizenn2(JNN-2)) /\ ($lsizenn2(JNN-2) <= 32))) .
  op vextbinop-- : WasmTerminal -> WasmType [ctor] .
  var N_VEXTBINOP-- : Nat . 
  ceq typecheck(i, vextbinop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(JNN-1, Jnn-1) /\ typecheck(M-1, M-1) /\ typecheck(JNN-2, Jnn-2) /\ typecheck(M-2, M-2) /\ (((2 * $lsizenn1(JNN-1)) == $lsizenn2(JNN-2)) /\ ($lsizenn2(JNN-2) >= 16)) .
  var N_VEXTBINOP-- : Nat . 
  ceq typecheck(i, vextbinop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(JNN-1, Jnn-1) /\ typecheck(M-1, M-1) /\ typecheck(JNN-2, Jnn-2) /\ typecheck(M-2, M-2) /\ (((2 * $lsizenn1(JNN-1)) == $lsizenn2(JNN-2)) /\ ($lsizenn2(JNN-2) == 32)) .
  var N_VEXTBINOP-- : Nat . 
  ceq typecheck(i, vextbinop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(JNN-1, Jnn-1) /\ typecheck(M-1, M-1) /\ typecheck(JNN-2, Jnn-2) /\ typecheck(M-2, M-2) /\ (((2 * $lsizenn1(JNN-1)) == $lsizenn2(JNN-2)) /\ ($lsizenn2(JNN-2) == 16)) .
  op vextternop-- : WasmTerminal -> WasmType [ctor] .
  var N_VEXTTERNOP-- : Nat . 
  ceq typecheck(i, vextternop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(JNN-1, Jnn-1) /\ typecheck(M-1, M-1) /\ typecheck(JNN-2, Jnn-2) /\ typecheck(M-2, M-2) /\ (((4 * $lsizenn1(JNN-1)) == $lsizenn2(JNN-2)) /\ ($lsizenn2(JNN-2) == 32)) .
  op vcvtop-- : WasmTerminal -> WasmType [ctor] .
  var N_VCVTOP-- : Nat . 
  ceq typecheck(i, vcvtop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(JNN-1, Jnn-1) /\ typecheck(M-1, M-1) /\ typecheck(JNN-2, Jnn-2) /\ typecheck(M-2, M-2) /\ ($lsizenn2(JNN-2) == (2 * $lsizenn1(JNN-1))) .
  var N_VCVTOP-- : Nat . 
  ceq typecheck(i, vcvtop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(JNN-1, Jnn-1) /\ typecheck(M-1, M-1) /\ typecheck(FNN-2, Fnn-2) /\ typecheck(M-2, M-2) /\ (((($sizenn2(FNN-2) == $lsizenn1(JNN-1)) /\ ($lsizenn1(JNN-1) == 32)) /\ (0 == 0)) \/ (($sizenn2(FNN-2) == (2 * $lsizenn1(JNN-1))) /\ (0 == 0))) .
  var N_VCVTOP-- : Nat . 
  ceq typecheck(i, vcvtop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(FNN-1, Fnn-1) /\ typecheck(M-1, M-1) /\ typecheck(JNN-2, Jnn-2) /\ typecheck(M-2, M-2) /\ (((($sizenn1(FNN-1) == $lsizenn2(JNN-2)) /\ ($lsizenn2(JNN-2) == 32)) /\ (0 == 0)) \/ (($sizenn1(FNN-1) == (2 * $lsizenn2(JNN-2))) /\ (0 == 0))) .
  var N_VCVTOP-- : Nat . 
  ceq typecheck(i, vcvtop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(FNN-1, Fnn-1) /\ typecheck(M-1, M-1) /\ typecheck(JNN-2, Jnn-2) /\ typecheck(M-2, M-2) /\ (((($sizenn1(FNN-1) == $lsizenn2(JNN-2)) /\ ($lsizenn2(JNN-2) == 32)) /\ (0 == 0)) \/ (($sizenn1(FNN-1) == (2 * $lsizenn2(JNN-2))) /\ (0 == 0))) .
  var N_VCVTOP-- : Nat . 
  ceq typecheck(i, vcvtop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(FNN-1, Fnn-1) /\ typecheck(M-1, M-1) /\ typecheck(FNN-2, Fnn-2) /\ typecheck(M-2, M-2) /\ ($sizenn1(FNN-1) == (2 * $sizenn2(FNN-2))) .
  var N_VCVTOP-- : Nat . 
  ceq typecheck(i, vcvtop--(UNKNOWN_CASE, UNKNOWN_CASE)) = true 
   if typecheck(FNN-1, Fnn-1) /\ typecheck(M-1, M-1) /\ typecheck(FNN-2, Fnn-2) /\ typecheck(M-2, M-2) /\ ((2 * $sizenn1(FNN-1)) == $sizenn2(FNN-2)) .
  op memarg :  -> WasmType [ctor] .

  op loadop- : WasmTerminal -> WasmType [ctor] .
  var N_LOADOP- : Nat . 
  ceq typecheck(i, loadop-(INN)) = true 
   if typecheck(INN, Inn) /\ (0 < $sizenn(INN)) .
  op storeop- : WasmTerminal -> WasmType [ctor] .
  var N_STOREOP- : Nat . 
  ceq typecheck(i, storeop-(INN)) = true 
   if typecheck(INN, Inn) /\ (0 < $sizenn(INN)) .
  op vloadop- : WasmTerminal -> WasmType [ctor] .
  var N_VLOADOP- : Nat . 
  ceq typecheck(i, vloadop-(VECTYPE)) = true 
   if typecheck(VECTYPE, vectype) /\ ((0 * M) == ($vsize(VECTYPE) / 2)) .
  op SPLAT _ : WasmTerminal -> WasmTerminal [ctor] .
  var SZ1 : WasmTerminal .
  eq typecheck(SPLAT SZ1, vloadop-(VECTYPE)) = typecheck(VECTYPE, vectype) /\ typecheck(SZ1, sz) .
  var N_VLOADOP- : Nat . 
  ceq typecheck(i, vloadop-(VECTYPE)) = true 
   if typecheck(VECTYPE, vectype) /\ (0 >= 32) .
  op blocktype :  -> WasmType [ctor] .
  op -RESULT _ : WasmTerminal -> WasmTerminal [ctor] .
  var VALTYPE1 : WasmTerminal .
  eq typecheck(-RESULT VALTYPE1, blocktype) = typecheck(VALTYPE1, valtype) .
  eq typecheck(-RESULT eps, blocktype) = true .
  op -IDX _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(-IDX TYPEIDX1, blocktype) = typecheck(TYPEIDX1, typeidx) .
  op catch :  -> WasmType [ctor] .
  op CATCH _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TAGIDX1 : WasmTerminal .
  var LABELIDX1 : WasmTerminal .
  eq typecheck(CATCH TAGIDX1 LABELIDX1, catch) = typecheck(TAGIDX1, tagidx) /\ typecheck(LABELIDX1, labelidx) .
  op CATCH-REF _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TAGIDX1 : WasmTerminal .
  var LABELIDX1 : WasmTerminal .
  eq typecheck(CATCH-REF TAGIDX1 LABELIDX1, catch) = typecheck(TAGIDX1, tagidx) /\ typecheck(LABELIDX1, labelidx) .
  op CATCH-ALL _ : WasmTerminal -> WasmTerminal [ctor] .
  var LABELIDX1 : WasmTerminal .
  eq typecheck(CATCH-ALL LABELIDX1, catch) = typecheck(LABELIDX1, labelidx) .
  op CATCH-ALL-REF _ : WasmTerminal -> WasmTerminal [ctor] .
  var LABELIDX1 : WasmTerminal .
  eq typecheck(CATCH-ALL-REF LABELIDX1, catch) = typecheck(LABELIDX1, labelidx) .
  op instr :  -> WasmType [ctor] .
  op NOP :  -> WasmTerminal [ctor] .
  eq typecheck(NOP, instr) = true .
  op UNREACHABLE :  -> WasmTerminal [ctor] .
  eq typecheck(UNREACHABLE, instr) = true .
  op DROP :  -> WasmTerminal [ctor] .
  eq typecheck(DROP, instr) = true .
  op SELECT _ : WasmTerminals -> WasmTerminal [ctor] .
  var VALTYPE* : WasmTerminals .
  eq typecheck(SELECT VALTYPE*, instr) = typecheck(VALTYPE*, valtype) .
  eq typecheck(SELECT eps, instr) = true .
  op BLOCK _ _ : WasmTerminal WasmTerminals -> WasmTerminal [ctor] .
  var BLOCKTYPE1 : WasmTerminal .
  var INSTR* : WasmTerminals .
  eq typecheck(BLOCK BLOCKTYPE1 INSTR*, instr) = typecheck(BLOCKTYPE1, blocktype) /\ typecheck(INSTR*, instr) .
  op LOOP _ _ : WasmTerminal WasmTerminals -> WasmTerminal [ctor] .
  var BLOCKTYPE1 : WasmTerminal .
  var INSTR* : WasmTerminals .
  eq typecheck(LOOP BLOCKTYPE1 INSTR*, instr) = typecheck(BLOCKTYPE1, blocktype) /\ typecheck(INSTR*, instr) .
  op IF _ _ _ : WasmTerminal WasmTerminals WasmTerminals -> WasmTerminal [ctor] .
  var BLOCKTYPE1 : WasmTerminal .
  var INSTR* : WasmTerminals .
  var INSTR* : WasmTerminals .
  eq typecheck(IF BLOCKTYPE1 INSTR* INSTR*, instr) = typecheck(BLOCKTYPE1, blocktype) /\ typecheck(INSTR*, instr) /\ typecheck(INSTR*, instr) .
  op BR _ : WasmTerminal -> WasmTerminal [ctor] .
  var LABELIDX1 : WasmTerminal .
  eq typecheck(BR LABELIDX1, instr) = typecheck(LABELIDX1, labelidx) .
  op BR-IF _ : WasmTerminal -> WasmTerminal [ctor] .
  var LABELIDX1 : WasmTerminal .
  eq typecheck(BR-IF LABELIDX1, instr) = typecheck(LABELIDX1, labelidx) .
  op BR-TABLE _ _ : WasmTerminals WasmTerminal -> WasmTerminal [ctor] .
  var LABELIDX* : WasmTerminals .
  var LABELIDX2 : WasmTerminal .
  eq typecheck(BR-TABLE LABELIDX* LABELIDX2, instr) = typecheck(LABELIDX*, labelidx) /\ typecheck(LABELIDX2, labelidx) .
  op BR-ON-NULL _ : WasmTerminal -> WasmTerminal [ctor] .
  var LABELIDX1 : WasmTerminal .
  eq typecheck(BR-ON-NULL LABELIDX1, instr) = typecheck(LABELIDX1, labelidx) .
  op BR-ON-NON-NULL _ : WasmTerminal -> WasmTerminal [ctor] .
  var LABELIDX1 : WasmTerminal .
  eq typecheck(BR-ON-NON-NULL LABELIDX1, instr) = typecheck(LABELIDX1, labelidx) .
  op BR-ON-CAST _ _ _ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var LABELIDX1 : WasmTerminal .
  var REFTYPE1 : WasmTerminal .
  var REFTYPE2 : WasmTerminal .
  eq typecheck(BR-ON-CAST LABELIDX1 REFTYPE1 REFTYPE2, instr) = typecheck(LABELIDX1, labelidx) /\ typecheck(REFTYPE1, reftype) /\ typecheck(REFTYPE2, reftype) .
  op BR-ON-CAST-FAIL _ _ _ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var LABELIDX1 : WasmTerminal .
  var REFTYPE1 : WasmTerminal .
  var REFTYPE2 : WasmTerminal .
  eq typecheck(BR-ON-CAST-FAIL LABELIDX1 REFTYPE1 REFTYPE2, instr) = typecheck(LABELIDX1, labelidx) /\ typecheck(REFTYPE1, reftype) /\ typecheck(REFTYPE2, reftype) .
  op CALL _ : WasmTerminal -> WasmTerminal [ctor] .
  var FUNCIDX1 : WasmTerminal .
  eq typecheck(CALL FUNCIDX1, instr) = typecheck(FUNCIDX1, funcidx) .
  op CALL-REF _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEUSE1 : WasmTerminal .
  eq typecheck(CALL-REF TYPEUSE1, instr) = typecheck(TYPEUSE1, typeuse) .
  op CALL-INDIRECT _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  var TYPEUSE1 : WasmTerminal .
  eq typecheck(CALL-INDIRECT TABLEIDX1 TYPEUSE1, instr) = typecheck(TABLEIDX1, tableidx) /\ typecheck(TYPEUSE1, typeuse) .
  op RETURN :  -> WasmTerminal [ctor] .
  eq typecheck(RETURN, instr) = true .
  op RETURN-CALL _ : WasmTerminal -> WasmTerminal [ctor] .
  var FUNCIDX1 : WasmTerminal .
  eq typecheck(RETURN-CALL FUNCIDX1, instr) = typecheck(FUNCIDX1, funcidx) .
  op RETURN-CALL-REF _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEUSE1 : WasmTerminal .
  eq typecheck(RETURN-CALL-REF TYPEUSE1, instr) = typecheck(TYPEUSE1, typeuse) .
  op RETURN-CALL-INDIRECT _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  var TYPEUSE1 : WasmTerminal .
  eq typecheck(RETURN-CALL-INDIRECT TABLEIDX1 TYPEUSE1, instr) = typecheck(TABLEIDX1, tableidx) /\ typecheck(TYPEUSE1, typeuse) .
  op THROW _ : WasmTerminal -> WasmTerminal [ctor] .
  var TAGIDX1 : WasmTerminal .
  eq typecheck(THROW TAGIDX1, instr) = typecheck(TAGIDX1, tagidx) .
  op THROW-REF :  -> WasmTerminal [ctor] .
  eq typecheck(THROW-REF, instr) = true .
  op TRY-TABLE _ _ _ : WasmTerminal WasmTerminal WasmTerminals -> WasmTerminal [ctor] .
  var BLOCKTYPE1 : WasmTerminal .
  var LIST1 : WasmTerminal .
  var INSTR* : WasmTerminals .
  eq typecheck(TRY-TABLE BLOCKTYPE1 LIST1 INSTR*, instr) = typecheck(BLOCKTYPE1, blocktype) /\ typecheck(LIST1, list(catch)) /\ typecheck(INSTR*, instr) .
  op LOCAL.GET _ : WasmTerminal -> WasmTerminal [ctor] .
  var LOCALIDX1 : WasmTerminal .
  eq typecheck(LOCAL.GET LOCALIDX1, instr) = typecheck(LOCALIDX1, localidx) .
  op LOCAL.SET _ : WasmTerminal -> WasmTerminal [ctor] .
  var LOCALIDX1 : WasmTerminal .
  eq typecheck(LOCAL.SET LOCALIDX1, instr) = typecheck(LOCALIDX1, localidx) .
  op LOCAL.TEE _ : WasmTerminal -> WasmTerminal [ctor] .
  var LOCALIDX1 : WasmTerminal .
  eq typecheck(LOCAL.TEE LOCALIDX1, instr) = typecheck(LOCALIDX1, localidx) .
  op GLOBAL.GET _ : WasmTerminal -> WasmTerminal [ctor] .
  var GLOBALIDX1 : WasmTerminal .
  eq typecheck(GLOBAL.GET GLOBALIDX1, instr) = typecheck(GLOBALIDX1, globalidx) .
  op GLOBAL.SET _ : WasmTerminal -> WasmTerminal [ctor] .
  var GLOBALIDX1 : WasmTerminal .
  eq typecheck(GLOBAL.SET GLOBALIDX1, instr) = typecheck(GLOBALIDX1, globalidx) .
  op TABLE.GET _ : WasmTerminal -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  eq typecheck(TABLE.GET TABLEIDX1, instr) = typecheck(TABLEIDX1, tableidx) .
  op TABLE.SET _ : WasmTerminal -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  eq typecheck(TABLE.SET TABLEIDX1, instr) = typecheck(TABLEIDX1, tableidx) .
  op TABLE.SIZE _ : WasmTerminal -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  eq typecheck(TABLE.SIZE TABLEIDX1, instr) = typecheck(TABLEIDX1, tableidx) .
  op TABLE.GROW _ : WasmTerminal -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  eq typecheck(TABLE.GROW TABLEIDX1, instr) = typecheck(TABLEIDX1, tableidx) .
  op TABLE.FILL _ : WasmTerminal -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  eq typecheck(TABLE.FILL TABLEIDX1, instr) = typecheck(TABLEIDX1, tableidx) .
  op TABLE.COPY _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  var TABLEIDX2 : WasmTerminal .
  eq typecheck(TABLE.COPY TABLEIDX1 TABLEIDX2, instr) = typecheck(TABLEIDX1, tableidx) /\ typecheck(TABLEIDX2, tableidx) .
  op TABLE.INIT _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  var ELEMIDX1 : WasmTerminal .
  eq typecheck(TABLE.INIT TABLEIDX1 ELEMIDX1, instr) = typecheck(TABLEIDX1, tableidx) /\ typecheck(ELEMIDX1, elemidx) .
  op ELEM.DROP _ : WasmTerminal -> WasmTerminal [ctor] .
  var ELEMIDX1 : WasmTerminal .
  eq typecheck(ELEM.DROP ELEMIDX1, instr) = typecheck(ELEMIDX1, elemidx) .
  op LOAD _ _ _ _ : WasmTerminal WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NUMTYPE1 : WasmTerminal .
  var LOADOP-1 : WasmTerminal .
  var MEMIDX1 : WasmTerminal .
  var MEMARG1 : WasmTerminal .
  eq typecheck(LOAD NUMTYPE1 LOADOP-1 MEMIDX1 MEMARG1, instr) = typecheck(NUMTYPE1, numtype) /\ typecheck(LOADOP-1, loadop-(NUMTYPE)) /\ typecheck(MEMIDX1, memidx) /\ typecheck(MEMARG1, memarg) .
  op STORE _ _ _ _ : WasmTerminal WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NUMTYPE1 : WasmTerminal .
  var STOREOP-1 : WasmTerminal .
  var MEMIDX1 : WasmTerminal .
  var MEMARG1 : WasmTerminal .
  eq typecheck(STORE NUMTYPE1 STOREOP-1 MEMIDX1 MEMARG1, instr) = typecheck(NUMTYPE1, numtype) /\ typecheck(STOREOP-1, storeop-(NUMTYPE)) /\ typecheck(MEMIDX1, memidx) /\ typecheck(MEMARG1, memarg) .
  op VLOAD _ _ _ _ : WasmTerminal WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var VECTYPE1 : WasmTerminal .
  var VLOADOP-1 : WasmTerminal .
  var MEMIDX1 : WasmTerminal .
  var MEMARG1 : WasmTerminal .
  eq typecheck(VLOAD VECTYPE1 VLOADOP-1 MEMIDX1 MEMARG1, instr) = typecheck(VECTYPE1, vectype) /\ typecheck(VLOADOP-1, vloadop-(VECTYPE)) /\ typecheck(MEMIDX1, memidx) /\ typecheck(MEMARG1, memarg) .
  op VLOAD-LANE _ _ _ _ _ : WasmTerminal WasmTerminal WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var VECTYPE1 : WasmTerminal .
  var SZ1 : WasmTerminal .
  var MEMIDX1 : WasmTerminal .
  var MEMARG1 : WasmTerminal .
  var LANEIDX1 : WasmTerminal .
  eq typecheck(VLOAD-LANE VECTYPE1 SZ1 MEMIDX1 MEMARG1 LANEIDX1, instr) = typecheck(VECTYPE1, vectype) /\ typecheck(SZ1, sz) /\ typecheck(MEMIDX1, memidx) /\ typecheck(MEMARG1, memarg) /\ typecheck(LANEIDX1, laneidx) .
  op VSTORE _ _ _ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var VECTYPE1 : WasmTerminal .
  var MEMIDX1 : WasmTerminal .
  var MEMARG1 : WasmTerminal .
  eq typecheck(VSTORE VECTYPE1 MEMIDX1 MEMARG1, instr) = typecheck(VECTYPE1, vectype) /\ typecheck(MEMIDX1, memidx) /\ typecheck(MEMARG1, memarg) .
  op VSTORE-LANE _ _ _ _ _ : WasmTerminal WasmTerminal WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var VECTYPE1 : WasmTerminal .
  var SZ1 : WasmTerminal .
  var MEMIDX1 : WasmTerminal .
  var MEMARG1 : WasmTerminal .
  var LANEIDX1 : WasmTerminal .
  eq typecheck(VSTORE-LANE VECTYPE1 SZ1 MEMIDX1 MEMARG1 LANEIDX1, instr) = typecheck(VECTYPE1, vectype) /\ typecheck(SZ1, sz) /\ typecheck(MEMIDX1, memidx) /\ typecheck(MEMARG1, memarg) /\ typecheck(LANEIDX1, laneidx) .
  op MEMORY.SIZE _ : WasmTerminal -> WasmTerminal [ctor] .
  var MEMIDX1 : WasmTerminal .
  eq typecheck(MEMORY.SIZE MEMIDX1, instr) = typecheck(MEMIDX1, memidx) .
  op MEMORY.GROW _ : WasmTerminal -> WasmTerminal [ctor] .
  var MEMIDX1 : WasmTerminal .
  eq typecheck(MEMORY.GROW MEMIDX1, instr) = typecheck(MEMIDX1, memidx) .
  op MEMORY.FILL _ : WasmTerminal -> WasmTerminal [ctor] .
  var MEMIDX1 : WasmTerminal .
  eq typecheck(MEMORY.FILL MEMIDX1, instr) = typecheck(MEMIDX1, memidx) .
  op MEMORY.COPY _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var MEMIDX1 : WasmTerminal .
  var MEMIDX2 : WasmTerminal .
  eq typecheck(MEMORY.COPY MEMIDX1 MEMIDX2, instr) = typecheck(MEMIDX1, memidx) /\ typecheck(MEMIDX2, memidx) .
  op MEMORY.INIT _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var MEMIDX1 : WasmTerminal .
  var DATAIDX1 : WasmTerminal .
  eq typecheck(MEMORY.INIT MEMIDX1 DATAIDX1, instr) = typecheck(MEMIDX1, memidx) /\ typecheck(DATAIDX1, dataidx) .
  op DATA.DROP _ : WasmTerminal -> WasmTerminal [ctor] .
  var DATAIDX1 : WasmTerminal .
  eq typecheck(DATA.DROP DATAIDX1, instr) = typecheck(DATAIDX1, dataidx) .
  op REF.NULL _ : WasmTerminal -> WasmTerminal [ctor] .
  var HEAPTYPE1 : WasmTerminal .
  eq typecheck(REF.NULL HEAPTYPE1, instr) = typecheck(HEAPTYPE1, heaptype) .
  op REF.IS-NULL :  -> WasmTerminal [ctor] .
  eq typecheck(REF.IS-NULL, instr) = true .
  op REF.AS-NON-NULL :  -> WasmTerminal [ctor] .
  eq typecheck(REF.AS-NON-NULL, instr) = true .
  op REF.EQ :  -> WasmTerminal [ctor] .
  eq typecheck(REF.EQ, instr) = true .
  op REF.TEST _ : WasmTerminal -> WasmTerminal [ctor] .
  var REFTYPE1 : WasmTerminal .
  eq typecheck(REF.TEST REFTYPE1, instr) = typecheck(REFTYPE1, reftype) .
  op REF.CAST _ : WasmTerminal -> WasmTerminal [ctor] .
  var REFTYPE1 : WasmTerminal .
  eq typecheck(REF.CAST REFTYPE1, instr) = typecheck(REFTYPE1, reftype) .
  op REF.FUNC _ : WasmTerminal -> WasmTerminal [ctor] .
  var FUNCIDX1 : WasmTerminal .
  eq typecheck(REF.FUNC FUNCIDX1, instr) = typecheck(FUNCIDX1, funcidx) .
  op REF.I31 :  -> WasmTerminal [ctor] .
  eq typecheck(REF.I31, instr) = true .
  op I31.GET _ : WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  eq typecheck(I31.GET SX1, instr) = typecheck(SX1, sx) .
  op STRUCT.NEW _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(STRUCT.NEW TYPEIDX1, instr) = typecheck(TYPEIDX1, typeidx) .
  op STRUCT.NEW-DEFAULT _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(STRUCT.NEW-DEFAULT TYPEIDX1, instr) = typecheck(TYPEIDX1, typeidx) .
  op STRUCT.GET _ _ _ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  var TYPEIDX1 : WasmTerminal .
  var U321 : WasmTerminal .
  eq typecheck(STRUCT.GET SX1 TYPEIDX1 U321, instr) = typecheck(SX1, sx) /\ typecheck(TYPEIDX1, typeidx) /\ typecheck(U321, u32) .
  op STRUCT.SET _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  var U321 : WasmTerminal .
  eq typecheck(STRUCT.SET TYPEIDX1 U321, instr) = typecheck(TYPEIDX1, typeidx) /\ typecheck(U321, u32) .
  op ARRAY.NEW _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(ARRAY.NEW TYPEIDX1, instr) = typecheck(TYPEIDX1, typeidx) .
  op ARRAY.NEW-DEFAULT _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(ARRAY.NEW-DEFAULT TYPEIDX1, instr) = typecheck(TYPEIDX1, typeidx) .
  op ARRAY.NEW-FIXED _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  var U321 : WasmTerminal .
  eq typecheck(ARRAY.NEW-FIXED TYPEIDX1 U321, instr) = typecheck(TYPEIDX1, typeidx) /\ typecheck(U321, u32) .
  op ARRAY.NEW-DATA _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  var DATAIDX1 : WasmTerminal .
  eq typecheck(ARRAY.NEW-DATA TYPEIDX1 DATAIDX1, instr) = typecheck(TYPEIDX1, typeidx) /\ typecheck(DATAIDX1, dataidx) .
  op ARRAY.NEW-ELEM _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  var ELEMIDX1 : WasmTerminal .
  eq typecheck(ARRAY.NEW-ELEM TYPEIDX1 ELEMIDX1, instr) = typecheck(TYPEIDX1, typeidx) /\ typecheck(ELEMIDX1, elemidx) .
  op ARRAY.GET _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var SX1 : WasmTerminal .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(ARRAY.GET SX1 TYPEIDX1, instr) = typecheck(SX1, sx) /\ typecheck(TYPEIDX1, typeidx) .
  op ARRAY.SET _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(ARRAY.SET TYPEIDX1, instr) = typecheck(TYPEIDX1, typeidx) .
  op ARRAY.LEN :  -> WasmTerminal [ctor] .
  eq typecheck(ARRAY.LEN, instr) = true .
  op ARRAY.FILL _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(ARRAY.FILL TYPEIDX1, instr) = typecheck(TYPEIDX1, typeidx) .
  op ARRAY.COPY _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  var TYPEIDX2 : WasmTerminal .
  eq typecheck(ARRAY.COPY TYPEIDX1 TYPEIDX2, instr) = typecheck(TYPEIDX1, typeidx) /\ typecheck(TYPEIDX2, typeidx) .
  op ARRAY.INIT-DATA _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  var DATAIDX1 : WasmTerminal .
  eq typecheck(ARRAY.INIT-DATA TYPEIDX1 DATAIDX1, instr) = typecheck(TYPEIDX1, typeidx) /\ typecheck(DATAIDX1, dataidx) .
  op ARRAY.INIT-ELEM _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  var ELEMIDX1 : WasmTerminal .
  eq typecheck(ARRAY.INIT-ELEM TYPEIDX1 ELEMIDX1, instr) = typecheck(TYPEIDX1, typeidx) /\ typecheck(ELEMIDX1, elemidx) .
  op EXTERN.CONVERT-ANY :  -> WasmTerminal [ctor] .
  eq typecheck(EXTERN.CONVERT-ANY, instr) = true .
  op ANY.CONVERT-EXTERN :  -> WasmTerminal [ctor] .
  eq typecheck(ANY.CONVERT-EXTERN, instr) = true .
  op CONST _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NUMTYPE1 : WasmTerminal .
  var NUM-1 : WasmTerminal .
  eq typecheck(CONST NUMTYPE1 NUM-1, instr) = typecheck(NUMTYPE1, numtype) /\ typecheck(NUM-1, num-(NUMTYPE)) .
  op UNOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NUMTYPE1 : WasmTerminal .
  var UNOP-1 : WasmTerminal .
  eq typecheck(UNOP NUMTYPE1 UNOP-1, instr) = typecheck(NUMTYPE1, numtype) /\ typecheck(UNOP-1, unop-(NUMTYPE)) .
  op BINOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NUMTYPE1 : WasmTerminal .
  var BINOP-1 : WasmTerminal .
  eq typecheck(BINOP NUMTYPE1 BINOP-1, instr) = typecheck(NUMTYPE1, numtype) /\ typecheck(BINOP-1, binop-(NUMTYPE)) .
  op TESTOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NUMTYPE1 : WasmTerminal .
  var TESTOP-1 : WasmTerminal .
  eq typecheck(TESTOP NUMTYPE1 TESTOP-1, instr) = typecheck(NUMTYPE1, numtype) /\ typecheck(TESTOP-1, testop-(NUMTYPE)) .
  op RELOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NUMTYPE1 : WasmTerminal .
  var RELOP-1 : WasmTerminal .
  eq typecheck(RELOP NUMTYPE1 RELOP-1, instr) = typecheck(NUMTYPE1, numtype) /\ typecheck(RELOP-1, relop-(NUMTYPE)) .
  op CVTOP _ _ _ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NUMTYPE1 : WasmTerminal .
  var NUMTYPE2 : WasmTerminal .
  var CVTOP--1 : WasmTerminal .
  eq typecheck(CVTOP NUMTYPE1 NUMTYPE2 CVTOP--1, instr) = typecheck(NUMTYPE1, numtype) /\ typecheck(NUMTYPE2, numtype) /\ typecheck(CVTOP--1, cvtop--(NUMTYPE_2, NUMTYPE_1)) .
  op VCONST _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var VECTYPE1 : WasmTerminal .
  var VEC-1 : WasmTerminal .
  eq typecheck(VCONST VECTYPE1 VEC-1, instr) = typecheck(VECTYPE1, vectype) /\ typecheck(VEC-1, vec-(VECTYPE)) .
  op VVUNOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var VECTYPE1 : WasmTerminal .
  var VVUNOP1 : WasmTerminal .
  eq typecheck(VVUNOP VECTYPE1 VVUNOP1, instr) = typecheck(VECTYPE1, vectype) /\ typecheck(VVUNOP1, vvunop) .
  op VVBINOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var VECTYPE1 : WasmTerminal .
  var VVBINOP1 : WasmTerminal .
  eq typecheck(VVBINOP VECTYPE1 VVBINOP1, instr) = typecheck(VECTYPE1, vectype) /\ typecheck(VVBINOP1, vvbinop) .
  op VVTERNOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var VECTYPE1 : WasmTerminal .
  var VVTERNOP1 : WasmTerminal .
  eq typecheck(VVTERNOP VECTYPE1 VVTERNOP1, instr) = typecheck(VECTYPE1, vectype) /\ typecheck(VVTERNOP1, vvternop) .
  op VVTESTOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var VECTYPE1 : WasmTerminal .
  var VVTESTOP1 : WasmTerminal .
  eq typecheck(VVTESTOP VECTYPE1 VVTESTOP1, instr) = typecheck(VECTYPE1, vectype) /\ typecheck(VVTESTOP1, vvtestop) .
  op VUNOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var SHAPE1 : WasmTerminal .
  var VUNOP-1 : WasmTerminal .
  eq typecheck(VUNOP SHAPE1 VUNOP-1, instr) = typecheck(SHAPE1, shape) /\ typecheck(VUNOP-1, vunop-(SHAPE)) .
  op VBINOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var SHAPE1 : WasmTerminal .
  var VBINOP-1 : WasmTerminal .
  eq typecheck(VBINOP SHAPE1 VBINOP-1, instr) = typecheck(SHAPE1, shape) /\ typecheck(VBINOP-1, vbinop-(SHAPE)) .
  op VTERNOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var SHAPE1 : WasmTerminal .
  var VTERNOP-1 : WasmTerminal .
  eq typecheck(VTERNOP SHAPE1 VTERNOP-1, instr) = typecheck(SHAPE1, shape) /\ typecheck(VTERNOP-1, vternop-(SHAPE)) .
  op VTESTOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var SHAPE1 : WasmTerminal .
  var VTESTOP-1 : WasmTerminal .
  eq typecheck(VTESTOP SHAPE1 VTESTOP-1, instr) = typecheck(SHAPE1, shape) /\ typecheck(VTESTOP-1, vtestop-(SHAPE)) .
  op VRELOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var SHAPE1 : WasmTerminal .
  var VRELOP-1 : WasmTerminal .
  eq typecheck(VRELOP SHAPE1 VRELOP-1, instr) = typecheck(SHAPE1, shape) /\ typecheck(VRELOP-1, vrelop-(SHAPE)) .
  op VSHIFTOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var ISHAPE1 : WasmTerminal .
  var VSHIFTOP-1 : WasmTerminal .
  eq typecheck(VSHIFTOP ISHAPE1 VSHIFTOP-1, instr) = typecheck(ISHAPE1, ishape) /\ typecheck(VSHIFTOP-1, vshiftop-(ISHAPE)) .
  op VBITMASK _ : WasmTerminal -> WasmTerminal [ctor] .
  var ISHAPE1 : WasmTerminal .
  eq typecheck(VBITMASK ISHAPE1, instr) = typecheck(ISHAPE1, ishape) .
  op VSWIZZLOP _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var BSHAPE1 : WasmTerminal .
  var VSWIZZLOP-1 : WasmTerminal .
  eq typecheck(VSWIZZLOP BSHAPE1 VSWIZZLOP-1, instr) = typecheck(BSHAPE1, bshape) /\ typecheck(VSWIZZLOP-1, vswizzlop-(BSHAPE)) .
 
  ceq typecheck(i, instr) = true 
   if (UNKNOWN_CASE == $dim(0)) .
  op VEXTUNOP _ _ _ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var ISHAPE1 : WasmTerminal .
  var ISHAPE2 : WasmTerminal .
  var VEXTUNOP--1 : WasmTerminal .
  eq typecheck(VEXTUNOP ISHAPE1 ISHAPE2 VEXTUNOP--1, instr) = typecheck(ISHAPE1, ishape) /\ typecheck(ISHAPE2, ishape) /\ typecheck(VEXTUNOP--1, vextunop--(ISHAPE_2, ISHAPE_1)) .
  op VEXTBINOP _ _ _ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var ISHAPE1 : WasmTerminal .
  var ISHAPE2 : WasmTerminal .
  var VEXTBINOP--1 : WasmTerminal .
  eq typecheck(VEXTBINOP ISHAPE1 ISHAPE2 VEXTBINOP--1, instr) = typecheck(ISHAPE1, ishape) /\ typecheck(ISHAPE2, ishape) /\ typecheck(VEXTBINOP--1, vextbinop--(ISHAPE_2, ISHAPE_1)) .
  op VEXTTERNOP _ _ _ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var ISHAPE1 : WasmTerminal .
  var ISHAPE2 : WasmTerminal .
  var VEXTTERNOP--1 : WasmTerminal .
  eq typecheck(VEXTTERNOP ISHAPE1 ISHAPE2 VEXTTERNOP--1, instr) = typecheck(ISHAPE1, ishape) /\ typecheck(ISHAPE2, ishape) /\ typecheck(VEXTTERNOP--1, vextternop--(ISHAPE_2, ISHAPE_1)) .
 
  ceq typecheck(i, instr) = true 
   if (($lsize($lanetype(0)) == (2 * $lsize($lanetype(0)))) /\ ((2 * $lsize($lanetype(0))) <= 32)) .
  op VCVTOP _ _ _ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var SHAPE1 : WasmTerminal .
  var SHAPE2 : WasmTerminal .
  var VCVTOP--1 : WasmTerminal .
  eq typecheck(VCVTOP SHAPE1 SHAPE2 VCVTOP--1, instr) = typecheck(SHAPE1, shape) /\ typecheck(SHAPE2, shape) /\ typecheck(VCVTOP--1, vcvtop--(SHAPE_2, SHAPE_1)) .
  op VSPLAT _ : WasmTerminal -> WasmTerminal [ctor] .
  var SHAPE1 : WasmTerminal .
  eq typecheck(VSPLAT SHAPE1, instr) = typecheck(SHAPE1, shape) .
 
  ceq typecheck(i, instr) = true 
   if ((0 == 0) == 0) .
  op VREPLACE-LANE _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var SHAPE1 : WasmTerminal .
  var LANEIDX1 : WasmTerminal .
  eq typecheck(VREPLACE-LANE SHAPE1 LANEIDX1, instr) = typecheck(SHAPE1, shape) /\ typecheck(LANEIDX1, laneidx) .
  op expr :  -> WasmType [ctor] .
  eq typecheck(INSTRS, expr) =  typecheck(INSTRS, instr) .

  op $memarg0 :  -> WasmTerminal .
  eq memarg0 = 0 .


  op $const : WasmTerminal WasmTerminal -> WasmTerminal .
  var CONSTTYPE : WasmTerminal .
  var LIT_ : WasmTerminal .
  eq const(NUMTYPE) = CONST .
  eq const(VECTYPE) = VCONST .


  op $free_shape : WasmTerminal -> WasmTerminal .
  var SHAPE : WasmTerminal .
  eq free_shape(UNKNOWN_CASE) = $free-lanetype(LANETYPE) .


  op $free_blocktype : WasmTerminal -> WasmTerminal .
  var BLOCKTYPE : WasmTerminal .
  eq free_blocktype(_RESULT) = $free-opt(0) .
  eq free_blocktype(_IDX) = $free-typeidx(TYPEIDX) .


  op $shift_labelidxs : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq shift_labelidxs(0) = 0 .
  eq shift_labelidxs(0) = $shift-labelidxs(0) .
  eq shift_labelidxs(0) = 0 .


  op $free_instr : WasmTerminal -> WasmTerminal .
  var INSTR : WasmTerminal .
  eq free_instr(NOP) = 0 .
  eq free_instr(UNREACHABLE) = 0 .
  eq free_instr(DROP) = 0 .
  eq free_instr(SELECT) = $free-opt(0) .
  eq free_instr(BLOCK) = 0 .
  eq free_instr(LOOP) = 0 .
  eq free_instr(IF) = 0 .
  eq free_instr(BR) = $free-labelidx(LABELIDX) .
  eq free_instr(BR_IF) = $free-labelidx(LABELIDX) .
  eq free_instr(BR_TABLE) = 0 .
  eq free_instr(BR_ON_NULL) = $free-labelidx(LABELIDX) .
  eq free_instr(BR_ON_NON_NULL) = $free-labelidx(LABELIDX) .
  eq free_instr(BR_ON_CAST) = 0 .
  eq free_instr(BR_ON_CAST_FAIL) = 0 .
  eq free_instr(CALL) = $free-funcidx(FUNCIDX) .
  eq free_instr(CALL_REF) = $free-typeuse(TYPEUSE) .
  eq free_instr(CALL_INDIRECT) = 0 .
  eq free_instr(RETURN) = 0 .
  eq free_instr(RETURN_CALL) = $free-funcidx(FUNCIDX) .
  eq free_instr(RETURN_CALL_REF) = $free-typeuse(TYPEUSE) .
  eq free_instr(RETURN_CALL_INDIRECT) = 0 .
  eq free_instr(CONST) = $free-numtype(NUMTYPE) .
  eq free_instr(UNOP) = $free-numtype(NUMTYPE) .
  eq free_instr(BINOP) = $free-numtype(NUMTYPE) .
  eq free_instr(TESTOP) = $free-numtype(NUMTYPE) .
  eq free_instr(RELOP) = $free-numtype(NUMTYPE) .
  eq free_instr(CVTOP) = 0 .
  eq free_instr(VCONST) = $free-vectype(VECTYPE) .
  eq free_instr(VVUNOP) = $free-vectype(VECTYPE) .
  eq free_instr(VVBINOP) = $free-vectype(VECTYPE) .
  eq free_instr(VVTERNOP) = $free-vectype(VECTYPE) .
  eq free_instr(VVTESTOP) = $free-vectype(VECTYPE) .
  eq free_instr(VUNOP) = $free-shape(SHAPE) .
  eq free_instr(VBINOP) = $free-shape(SHAPE) .
  eq free_instr(VTERNOP) = $free-shape(SHAPE) .
  eq free_instr(VTESTOP) = $free-shape(SHAPE) .
  eq free_instr(VRELOP) = $free-shape(SHAPE) .
  eq free_instr(VSHIFTOP) = $free-shape(0) .
  eq free_instr(VBITMASK) = $free-shape(0) .
  eq free_instr(VSWIZZLOP) = $free-shape(0) .
  eq free_instr(VSHUFFLE) = $free-shape(0) .
  eq free_instr(VEXTUNOP) = 0 .
  eq free_instr(VEXTBINOP) = 0 .
  eq free_instr(VEXTTERNOP) = 0 .
  eq free_instr(VNARROW) = 0 .
  eq free_instr(VCVTOP) = 0 .
  eq free_instr(VSPLAT) = $free-shape(SHAPE) .
  eq free_instr(VEXTRACT_LANE) = $free-shape(SHAPE) .
  eq free_instr(VREPLACE_LANE) = $free-shape(SHAPE) .
  eq free_instr(REF.NULL) = $free-heaptype(HEAPTYPE) .
  eq free_instr(REF.IS_NULL) = 0 .
  eq free_instr(REF.AS_NON_NULL) = 0 .
  eq free_instr(REF.EQ) = 0 .
  eq free_instr(REF.TEST) = $free-reftype(REFTYPE) .
  eq free_instr(REF.CAST) = $free-reftype(REFTYPE) .
  eq free_instr(REF.FUNC) = $free-funcidx(FUNCIDX) .
  eq free_instr(REF.I31) = 0 .
  eq free_instr(I31.GET) = 0 .
  eq free_instr(STRUCT.NEW) = 0 .
  eq free_instr(STRUCT.NEW_DEFAULT) = $free-typeidx(TYPEIDX) .
  eq free_instr(STRUCT.GET) = $free-typeidx(TYPEIDX) .
  eq free_instr(STRUCT.SET) = $free-typeidx(TYPEIDX) .
  eq free_instr(ARRAY.NEW) = $free-typeidx(TYPEIDX) .
  eq free_instr(ARRAY.NEW_DEFAULT) = $free-typeidx(TYPEIDX) .
  eq free_instr(ARRAY.NEW_FIXED) = $free-typeidx(TYPEIDX) .
  eq free_instr(ARRAY.NEW_DATA) = 0 .
  eq free_instr(ARRAY.NEW_ELEM) = 0 .
  eq free_instr(ARRAY.GET) = $free-typeidx(TYPEIDX) .
  eq free_instr(ARRAY.SET) = $free-typeidx(TYPEIDX) .
  eq free_instr(ARRAY.LEN) = 0 .
  eq free_instr(ARRAY.FILL) = $free-typeidx(TYPEIDX) .
  eq free_instr(ARRAY.COPY) = 0 .
  eq free_instr(ARRAY.INIT_DATA) = 0 .
  eq free_instr(ARRAY.INIT_ELEM) = 0 .
  eq free_instr(EXTERN.CONVERT_ANY) = 0 .
  eq free_instr(ANY.CONVERT_EXTERN) = 0 .
  eq free_instr(LOCAL.GET) = $free-localidx(LOCALIDX) .
  eq free_instr(LOCAL.SET) = $free-localidx(LOCALIDX) .
  eq free_instr(LOCAL.TEE) = $free-localidx(LOCALIDX) .
  eq free_instr(GLOBAL.GET) = $free-globalidx(GLOBALIDX) .
  eq free_instr(GLOBAL.SET) = $free-globalidx(GLOBALIDX) .
  eq free_instr(TABLE.GET) = $free-tableidx(TABLEIDX) .
  eq free_instr(TABLE.SET) = $free-tableidx(TABLEIDX) .
  eq free_instr(TABLE.SIZE) = $free-tableidx(TABLEIDX) .
  eq free_instr(TABLE.GROW) = $free-tableidx(TABLEIDX) .
  eq free_instr(TABLE.FILL) = $free-tableidx(TABLEIDX) .
  eq free_instr(TABLE.COPY) = 0 .
  eq free_instr(TABLE.INIT) = 0 .
  eq free_instr(ELEM.DROP) = $free-elemidx(ELEMIDX) .
  eq free_instr(LOAD) = 0 .
  eq free_instr(STORE) = 0 .
  eq free_instr(VLOAD) = 0 .
  eq free_instr(VLOAD_LANE) = 0 .
  eq free_instr(VSTORE) = 0 .
  eq free_instr(VSTORE_LANE) = 0 .
  eq free_instr(MEMORY.SIZE) = $free-memidx(MEMIDX) .
  eq free_instr(MEMORY.GROW) = $free-memidx(MEMIDX) .
  eq free_instr(MEMORY.FILL) = $free-memidx(MEMIDX) .
  eq free_instr(MEMORY.COPY) = 0 .
  eq free_instr(MEMORY.INIT) = 0 .
  eq free_instr(DATA.DROP) = $free-dataidx(DATAIDX) .


  op $free_block : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq free_block(0) = 0 .


  op $free_expr : WasmTerminal -> WasmTerminal .
  var EXPR : WasmTerminal .
  eq free_expr(0) = $free-list(0) .

  op elemmode :  -> WasmType [ctor] .
  op ACTIVE _ _ : WasmTerminal WasmTerminals -> WasmTerminal [ctor] .
  var TABLEIDX1 : WasmTerminal .
  var EXPR1 : WasmTerminals .
  eq typecheck(ACTIVE TABLEIDX1 EXPR1, elemmode) = typecheck(TABLEIDX1, tableidx) /\ typecheck(EXPR1, expr) .
  op PASSIVE :  -> WasmTerminal [ctor] .
  eq typecheck(PASSIVE, elemmode) = true .
  op DECLARE :  -> WasmTerminal [ctor] .
  eq typecheck(DECLARE, elemmode) = true .
  op datamode :  -> WasmType [ctor] .
  op ACTIVE _ _ : WasmTerminal WasmTerminals -> WasmTerminal [ctor] .
  var MEMIDX1 : WasmTerminal .
  var EXPR1 : WasmTerminals .
  eq typecheck(ACTIVE MEMIDX1 EXPR1, datamode) = typecheck(MEMIDX1, memidx) /\ typecheck(EXPR1, expr) .
  op PASSIVE :  -> WasmTerminal [ctor] .
  eq typecheck(PASSIVE, datamode) = true .
  op type :  -> WasmType [ctor] .
  op TYPE _ : WasmTerminal -> WasmTerminal [ctor] .
  var RECTYPE1 : WasmTerminal .
  eq typecheck(TYPE RECTYPE1, type) = typecheck(RECTYPE1, rectype) .
  op tag :  -> WasmType [ctor] .
  op TAG _ : WasmTerminal -> WasmTerminal [ctor] .
  var TAGTYPE1 : WasmTerminal .
  eq typecheck(TAG TAGTYPE1, tag) = typecheck(TAGTYPE1, tagtype) .
  op global :  -> WasmType [ctor] .
  op GLOBAL _ _ : WasmTerminal WasmTerminals -> WasmTerminal [ctor] .
  var GLOBALTYPE1 : WasmTerminal .
  var EXPR1 : WasmTerminals .
  eq typecheck(GLOBAL GLOBALTYPE1 EXPR1, global) = typecheck(GLOBALTYPE1, globaltype) /\ typecheck(EXPR1, expr) .
  op mem :  -> WasmType [ctor] .
  op MEMORY _ : WasmTerminal -> WasmTerminal [ctor] .
  var MEMTYPE1 : WasmTerminal .
  eq typecheck(MEMORY MEMTYPE1, mem) = typecheck(MEMTYPE1, memtype) .
  op table :  -> WasmType [ctor] .
  op TABLE _ _ : WasmTerminal WasmTerminals -> WasmTerminal [ctor] .
  var TABLETYPE1 : WasmTerminal .
  var EXPR1 : WasmTerminals .
  eq typecheck(TABLE TABLETYPE1 EXPR1, table) = typecheck(TABLETYPE1, tabletype) /\ typecheck(EXPR1, expr) .
  op data :  -> WasmType [ctor] .
  op DATA _ _ : WasmTerminals WasmTerminal -> WasmTerminal [ctor] .
  var BYTE* : WasmTerminals .
  var DATAMODE1 : WasmTerminal .
  eq typecheck(DATA BYTE* DATAMODE1, data) = typecheck(BYTE*, byte) /\ typecheck(DATAMODE1, datamode) .
  op local :  -> WasmType [ctor] .
  op LOCAL _ : WasmTerminal -> WasmTerminal [ctor] .
  var VALTYPE1 : WasmTerminal .
  eq typecheck(LOCAL VALTYPE1, local) = typecheck(VALTYPE1, valtype) .
  op func :  -> WasmType [ctor] .
  op FUNC _ _ _ : WasmTerminal WasmTerminals WasmTerminals -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  var LOCAL* : WasmTerminals .
  var EXPR1 : WasmTerminals .
  eq typecheck(FUNC TYPEIDX1 LOCAL* EXPR1, func) = typecheck(TYPEIDX1, typeidx) /\ typecheck(LOCAL*, local) /\ typecheck(EXPR1, expr) .
  op elem :  -> WasmType [ctor] .
  op ELEM _ _ _ : WasmTerminal WasmTerminals WasmTerminal -> WasmTerminal [ctor] .
  var REFTYPE1 : WasmTerminal .
  var EXPR* : WasmTerminals .
  var ELEMMODE1 : WasmTerminal .
  eq typecheck(ELEM REFTYPE1 EXPR* ELEMMODE1, elem) = typecheck(REFTYPE1, reftype) /\ typecheck(EXPR*, expr) /\ typecheck(ELEMMODE1, elemmode) .
  op start :  -> WasmType [ctor] .
  op START _ : WasmTerminal -> WasmTerminal [ctor] .
  var FUNCIDX1 : WasmTerminal .
  eq typecheck(START FUNCIDX1, start) = typecheck(FUNCIDX1, funcidx) .
  op import :  -> WasmType [ctor] .
  op IMPORT _ _ _ : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NAME1 : WasmTerminal .
  var NAME2 : WasmTerminal .
  var EXTERNTYPE1 : WasmTerminal .
  eq typecheck(IMPORT NAME1 NAME2 EXTERNTYPE1, import) = typecheck(NAME1, name) /\ typecheck(NAME2, name) /\ typecheck(EXTERNTYPE1, externtype) .
  op export :  -> WasmType [ctor] .
  op EXPORT _ _ : WasmTerminal WasmTerminal -> WasmTerminal [ctor] .
  var NAME1 : WasmTerminal .
  var EXTERNIDX1 : WasmTerminal .
  eq typecheck(EXPORT NAME1 EXTERNIDX1, export) = typecheck(NAME1, name) /\ typecheck(EXTERNIDX1, externidx) .
  op module :  -> WasmType [ctor] .
  op MODULE _ _ _ _ _ _ _ _ _ _ _ : WasmTerminals WasmTerminals WasmTerminals WasmTerminals WasmTerminals WasmTerminals WasmTerminals WasmTerminals WasmTerminals WasmTerminal WasmTerminals -> WasmTerminal [ctor] .
  var TYPE* : WasmTerminals .
  var IMPORT* : WasmTerminals .
  var TAG* : WasmTerminals .
  var GLOBAL* : WasmTerminals .
  var MEM* : WasmTerminals .
  var TABLE* : WasmTerminals .
  var FUNC* : WasmTerminals .
  var DATA* : WasmTerminals .
  var ELEM* : WasmTerminals .
  var START1 : WasmTerminal .
  var EXPORT* : WasmTerminals .
  eq typecheck(MODULE TYPE* IMPORT* TAG* GLOBAL* MEM* TABLE* FUNC* DATA* ELEM* START1 EXPORT*, module) = typecheck(TYPE*, type) /\ typecheck(IMPORT*, import) /\ typecheck(TAG*, tag) /\ typecheck(GLOBAL*, global) /\ typecheck(MEM*, mem) /\ typecheck(TABLE*, table) /\ typecheck(FUNC*, func) /\ typecheck(DATA*, data) /\ typecheck(ELEM*, elem) /\ typecheck(START1, start) /\ typecheck(EXPORT*, export) .

  op $free_type : WasmTerminal -> WasmTerminal .
  var TYPE : WasmTerminal .
  eq free_type(TYPE) = $free-rectype(RECTYPE) .


  op $free_tag : WasmTerminal -> WasmTerminal .
  var TAG : WasmTerminal .
  eq free_tag(TAG) = $free-tagtype(TAGTYPE) .


  op $free_global : WasmTerminal -> WasmTerminal .
  var GLOBAL : WasmTerminal .
  eq free_global(GLOBAL) = 0 .


  op $free_mem : WasmTerminal -> WasmTerminal .
  var MEM : WasmTerminal .
  eq free_mem(MEMORY) = $free-memtype(MEMTYPE) .


  op $free_table : WasmTerminal -> WasmTerminal .
  var TABLE : WasmTerminal .
  eq free_table(TABLE) = 0 .


  op $free_local : WasmTerminal -> WasmTerminal .
  var LOCAL : WasmTerminal .
  eq free_local(LOCAL) = $free-valtype(T) .


  op $free_func : WasmTerminal -> WasmTerminal .
  var FUNC : WasmTerminal .
  eq free_func(FUNC) = 0 .


  op $free_datamode : WasmTerminal -> WasmTerminal .
  var DATAMODE : WasmTerminal .
  eq free_datamode(ACTIVE) = 0 .
  eq free_datamode(PASSIVE) = 0 .


  op $free_data : WasmTerminal -> WasmTerminal .
  var DATA : WasmTerminal .
  eq free_data(DATA) = $free-datamode(DATAMODE) .


  op $free_elemmode : WasmTerminal -> WasmTerminal .
  var ELEMMODE : WasmTerminal .
  eq free_elemmode(ACTIVE) = 0 .
  eq free_elemmode(PASSIVE) = 0 .
  eq free_elemmode(DECLARE) = 0 .


  op $free_elem : WasmTerminal -> WasmTerminal .
  var ELEM : WasmTerminal .
  eq free_elem(ELEM) = 0 .


  op $free_start : WasmTerminal -> WasmTerminal .
  var START : WasmTerminal .
  eq free_start(START) = $free-funcidx(FUNCIDX) .


  op $free_import : WasmTerminal -> WasmTerminal .
  var IMPORT : WasmTerminal .
  eq free_import(IMPORT) = $free-externtype(EXTERNTYPE) .


  op $free_export : WasmTerminal -> WasmTerminal .
  var EXPORT : WasmTerminal .
  eq free_export(EXPORT) = $free-externidx(EXTERNIDX) .


  op $free_module : WasmTerminal -> WasmTerminal .
  var MODULE : WasmTerminal .
  eq free_module(MODULE) = 0 .


  op $funcidx_module : WasmTerminal -> WasmTerminal .
  var MODULE : WasmTerminal .
  var MODULE : WasmTerminal .
  eq $funcidx_module(MODULE) = 0 .


  op $dataidx_funcs : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq dataidx_funcs(0) = 0 .

  op init :  -> WasmType [ctor] .
  op SET :  -> WasmTerminal [ctor] .
  eq typecheck(SET, init) = true .
  op UNSET :  -> WasmTerminal [ctor] .
  eq typecheck(UNSET, init) = true .
  op localtype :  -> WasmType [ctor] .

  var INIT1 : WasmTerminal .
  var VALTYPE1 : WasmTerminal .
  eq typecheck(INIT1 VALTYPE1, localtype) = typecheck(INIT1, init) /\ typecheck(VALTYPE1, valtype) .
  op instrtype :  -> WasmType [ctor] .
  op arrow- _ _ _ : WasmTerminals WasmTerminals WasmTerminals -> WasmTerminal [ctor] .
  var RESULTTYPE1 : WasmTerminals .
  var LOCALIDX* : WasmTerminals .
  var RESULTTYPE2 : WasmTerminals .
  eq typecheck(arrow- RESULTTYPE1 LOCALIDX* RESULTTYPE2, instrtype) = typecheck(RESULTTYPE1, resulttype) /\ typecheck(LOCALIDX*, localidx) /\ typecheck(RESULTTYPE2, resulttype) .
  op context :  -> WasmType [ctor] .


  op $with_locals : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var CONTEXT : WasmTerminal .
  var _ : WasmTerminal .
  var _ : WasmTerminal .
  var C : WasmTerminal .
  eq $with_locals(C) = C .
  var C : WasmTerminal .
  eq $with_locals(C) = $with-locals(0, 0, 0) .


  op $clos_deftypes : WasmTerminal -> WasmTerminal .
  var _ : WasmTerminal .
  eq clos_deftypes(0) = 0 .
  eq clos_deftypes(0) = 0 .


  op $clos_valtype : WasmTerminal WasmTerminal -> WasmTerminal .
  var CONTEXT : WasmTerminal .
  var VALTYPE : WasmTerminal .
  var C : WasmTerminal .
  eq $clos_valtype(C) = $subst-all-valtype(T, 0) .


  op $clos_deftype : WasmTerminal WasmTerminal -> WasmTerminal .
  var CONTEXT : WasmTerminal .
  var DEFTYPE : WasmTerminal .
  var C : WasmTerminal .
  eq $clos_deftype(C) = $subst-all-deftype(DT, 0) .


  op $clos_tagtype : WasmTerminal WasmTerminal -> WasmTerminal .
  var CONTEXT : WasmTerminal .
  var TAGTYPE : WasmTerminal .
  var C : WasmTerminal .
  eq $clos_tagtype(C) = $subst-all-tagtype(JT, 0) .


  op $clos_externtype : WasmTerminal WasmTerminal -> WasmTerminal .
  var CONTEXT : WasmTerminal .
  var EXTERNTYPE : WasmTerminal .
  var C : WasmTerminal .
  eq $clos_externtype(C) = $subst-all-externtype(XT, 0) .


  op $clos_moduletype : WasmTerminal WasmTerminal -> WasmTerminal .
  var CONTEXT : WasmTerminal .
  var MODULETYPE : WasmTerminal .
  var C : WasmTerminal .
  eq $clos_moduletype(C) = $subst-all-moduletype(MMT, 0) .

  op oktypeidx :  -> WasmType [ctor] .
  op OK _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(OK TYPEIDX1, oktypeidx) = typecheck(TYPEIDX1, typeidx) .
  op oktypeidxnat :  -> WasmType [ctor] .
  op OK _ : WasmTerminal -> WasmTerminal [ctor] .
  var TYPEIDX1 : WasmTerminal .
  eq typecheck(OK TYPEIDX1, oktypeidxnat) = typecheck(TYPEIDX1, typeidx) .

  op $before : WasmTerminal WasmTerminal WasmTerminal -> WasmTerminal .
  var TYPEUSE : WasmTerminal .
  var TYPEIDX : WasmTerminal .
  var NAT : WasmTerminal .
  eq before(DEFTYPE) = 0 .
  eq before(_IDX) = (0 < 0) .
  eq before(REC) = (J < I) .


  op $unrollht : WasmTerminal WasmTerminal -> WasmTerminal .
  var CONTEXT : WasmTerminal .
  var HEAPTYPE : WasmTerminal .
  var C : WasmTerminal .
  eq $unrollht(C) = $unrolldt(DEFTYPE) .
  var C : WasmTerminal .
  eq $unrollht(C) = $unrolldt(0) .
  var C : WasmTerminal .
  eq $unrollht(C) = 0 .























  op $is_packtype : WasmTerminal -> WasmTerminal .
  var STORAGETYPE : WasmTerminal .
  var ZT : WasmTerminal .
  eq $is_packtype(ZT) = (ZT == $unpack(ZT)) .



  op nonfuncs :  -> WasmType [ctor] .

  var GLOBAL* : WasmTerminals .
  var MEM* : WasmTerminals .
  var TABLE* : WasmTerminals .
  var ELEM* : WasmTerminals .
  eq typecheck(GLOBAL* MEM* TABLE* ELEM*, nonfuncs) = typecheck(GLOBAL*, global) /\ typecheck(MEM*, mem) /\ typecheck(TABLE*, table) /\ typecheck(ELEM*, elem) .

  op $funcidx_nonfuncs : WasmTerminal -> WasmTerminal .
  var NONFUNCS : WasmTerminal .
  eq funcidx_nonfuncs(UNKNOWN_CASE) = $funcidx-module(MODULE) .


endm
