[package]
name = "spacewasm-poison-runner"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
spacewasm = { git = "https://github.com/nasa/spacewasm", rev = "839feec79fcd7137e2e5f1a19922127f97d6d1d8" }

[build-dependencies]
wat = "1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = false
