load /Users/minsung/Dev/projects/Spec2Maude/optimization/semantics_optimization.maude
load model-checker.maude

mod WASM2MAUDE-MODELCHECK is
  protecting WASM-BUILTINS .
  including MODEL-CHECKER .

  sort ModelState .
  subsort ModelState < State .
  op boot : -> ModelState [ctor] .
  op init : SpectecTerminal -> ModelState [ctor frozen (1)] .
  op ready : SpectecTerminal -> ModelState [ctor] .
  op exec : SpectecTerminal -> ModelState [ctor frozen (1)] .
  op finished : SpectecTerminal -> ModelState [ctor] .

  op inputModule : -> SpectecTerminal .
  op inputName : -> SpectecTerminals .
  op inputArgs : -> ValList .
  op emptyStore : -> SpectecTerminal .
  op expected : -> Instr .
  op rejected : -> Instr .
  op fibBody : -> InstrList .
  op fibElse : -> InstrList .
  op findFunc : SpectecTerminals SpectecTerminals ~> Nat .
  op returned : SpectecTerminal -> Prop [ctor] .

  vars C C2 Z XA : SpectecTerminal .
  var RESULT : Instr .
  vars NAME OTHER EXPORTS : SpectecTerminals .
  var RESULTS : InstrList .
  var ADDR : Nat .
  var ST : ModelState .
  var P : Prop .

  eq fibElse =
    instrConcat(LOCAL.GET(0),
    instrConcat(CONST(I64, 2),
    instrConcat(BINOP(I64, spectec-SUB),
    instrConcat(CALL(0),
    instrConcat(LOCAL.GET(0),
    instrConcat(CONST(I64, 1),
    instrConcat(BINOP(I64, spectec-SUB),
    instrConcat(CALL(0), BINOP(I64, ADD))))))))) .

  eq fibBody =
    instrConcat(LOCAL.GET(0),
    instrConcat(CONST(I64, 1),
    instrConcat(RELOP(I64, LE(U)),
      IF__ELSE_(-RESULT(_?(I64)), CONST(I64, 1), fibElse)))) .

  eq inputModule = MODULE(TYPE(REC(SUB(_?(FINAL), eps, FUNC_->_(I64, I64)))), eps, eps, eps,
eps, eps, spectec-FUNC-2(0, eps, fibBody),
eps, eps, eps, EXPORT((102 105 98), FUNC(0))) .
  eq inputName = 102 105 98 .
  eq inputArgs = valList(CONST(I64, 5)) .
  eq expected = CONST(I64, 8) .
  eq rejected = CONST(I64, 6) .
  eq emptyStore = {(item('TAGS, eps) ;
  (item('GLOBALS, eps) ;
   (item('MEMS, eps) ;
    (item('TABLES, eps) ;
     (item('FUNCS, eps) ;
      (item('DATAS, eps) ;
       (item('ELEMS, eps) ;
        (item('STRUCTS, eps) ; (item('ARRAYS, eps) ; item('EXNS, eps))))))))))} .

  eq findFunc({(item('NAME, NAME) ; item('ADDR, FUNC(ADDR)))} EXPORTS, NAME) = ADDR .
  ceq findFunc({(item('NAME, OTHER) ; item('ADDR, XA))} EXPORTS, NAME) = findFunc(EXPORTS, NAME)
    if OTHER =/= NAME .

  crl [instantiate] : boot => init(C)
    if instantiate(emptyStore, inputModule, eps) => C .
  crl [init-step] : init(C) => init(C2)
    if Step(C) => C2 .
  crl [initialize] : init(C) => ready(Z)
    if (Z ; instrNil) := C .
  rl [invoke] : ready(Z) => exec(invoke(spectec-store(Z),
findFunc(value('EXPORTS, spectec-moduleinst(Z)), inputName), inputArgs)) .
  crl [execute-step] : exec(C) => exec(C2)
    if Step(C) => C2 .
  crl [finished] : exec(C) => finished(RESULT)
    if (Z ; RESULTS) := C
    /\ RESULT := RESULTS
    /\ typecheck(RESULT, val) = true .

  eq finished(RESULT) |= returned(RESULT) = true .
  eq ST |= P = false [owise] .
endm

search [1, 200] in WASM2MAUDE-MODELCHECK :
  boot =>* finished(RESULT)
  such that RESULT == rejected .

quit
