fmod DSL-OPTION is
  protecting DSL-PRETYPE .

  op _? : SpectecTerminal -> SpectecTerminal [ctor] .
  op _! : SpectecTerminal ~> SpectecTerminals .

  --- CAT-opt is partial: two present options have no concatenation rule.
  op optionConcat : SpectecTerminals SpectecTerminals ~> SpectecTerminals .

  var K : [SpectecTerminal] .
  var TYPE : SpectecType .

  eq optionConcat(eps, eps) = eps .
  eq optionConcat(K ?, eps) = K ? .
  eq optionConcat(eps, K ?) = K ? .

  eq (K ?)! = K .
  eq typecheck(K ?, TYPE) = typecheck(K, TYPE) .
endfm
