fmod DSL-TERM is
  sort SpectecTerminal .
  sort SpectecType .
  sort SpectecDef .
endfm

fmod DSL-PRETYPE-BASE is
  protecting DSL-TERM .
  protecting BOOL .
  protecting NAT .
  protecting INT .
  protecting RAT .
  protecting FLOAT .
  protecting STRING .

  subsorts Nat Int < SpectecTerminal .

  ops bool nat int rat real text : -> SpectecType [ctor] .
  ops iterOpt iterList iterList1 : SpectecType -> SpectecType [ctor] .
  op iterListN : SpectecType Nat -> SpectecType [ctor] .

  op bool : Bool -> SpectecTerminal [ctor] .
  op rat : Rat -> SpectecTerminal [ctor] .
  op float : Float -> SpectecTerminal [ctor] .
  op text : String -> SpectecTerminal [ctor] .

  op typecheck : [SpectecTerminal] SpectecType -> Bool .

  var B : Bool .
  var N : Nat .
  var I : Int .
  var R : Rat .
  var F : Float .
  var S : String .
  eq typecheck(bool(B), bool) = true .
  eq typecheck(N, nat) = true .
  eq typecheck(I, int) = true .
  eq typecheck(rat(R), rat) = true .
  eq typecheck(float(F), real) = true .
  eq typecheck(text(S), text) = true .

endfm
