fmod DSL-TERM is
  sort SpectecTerminal .
  sort SpectecType .
  sort SpectecDef .
endfm

fmod DSL-PRETYPE is
  protecting DSL-TERM .
  protecting BOOL .
  protecting NAT .
  protecting INT .
  protecting RAT .
  protecting FLOAT .
  protecting STRING .

  sort SpectecTerminals .

  subsorts Nat Int < SpectecTerminal .
  subsort SpectecTerminal < SpectecTerminals .

  ops bool nat int rat real text : -> SpectecType [ctor] .

  op bool : Bool -> SpectecTerminal [ctor] .
  op rat : Rat -> SpectecTerminal [ctor] .
  op float : Float -> SpectecTerminal [ctor] .
  op text : String -> SpectecTerminal [ctor] .

  op eps : -> SpectecTerminals [ctor] .
  op __ : SpectecTerminals SpectecTerminals -> SpectecTerminals
    [ctor assoc id: eps] .

  --- A nested sequence is one element of an outer sequence.

  op seq : SpectecTerminals -> SpectecTerminal [ctor] .
  op unseq : SpectecTerminal ~> SpectecTerminals .
  eq unseq(seq(TS)) = TS .

  op typecheck : [SpectecTerminal] SpectecType -> Bool .

  var B : Bool .
  var N : Nat .
  var I : Int .
  var R : Rat .
  var F : Float .
  var S : String .
  var K : [SpectecTerminal] .
  var T : SpectecTerminal .
  var TS : SpectecTerminals .
  var TYPE : SpectecType .

  eq typecheck(bool(B), bool) = true .
  eq typecheck(N, nat) = true .
  eq typecheck(I, int) = true .
  eq typecheck(rat(R), rat) = true .
  eq typecheck(float(F), real) = true .
  eq typecheck(text(S), text) = true .

  eq typecheck(eps, TYPE) = true .
  ceq typecheck(T TS, TYPE) = typecheck(TS, TYPE)
    if TS =/= eps /\ typecheck(T, TYPE) .
  eq typecheck(K, TYPE) = false [owise] .
endfm
