mod SORT-SEQUENCE-PROTOTYPE is
  protecting NAT .

  sort SpectecTerminal .
  sort SpectecTerminals .
  subsort SpectecTerminal < SpectecTerminals .

  sorts Val Instr .
  subsort Val < Instr .
  subsort Instr < SpectecTerminal .

  sorts EmptySeq Vals Instrs .
  subsort EmptySeq < Vals .
  subsort Vals < Instrs .
  subsort Instrs < SpectecTerminals .
  subsort Val < Vals .
  subsort Instr < Instrs .

  op eps : -> EmptySeq [ctor] .
  op __ : Vals Vals -> Vals [ctor assoc id: eps] .
  op __ : Instrs Instrs -> Instrs [ctor assoc id: eps] .
  op __ : SpectecTerminals SpectecTerminals
    -> SpectecTerminals [ctor assoc id: eps] .

  op val : Nat -> Val [ctor] .
  op add : -> Instr [ctor] .
endm

select SORT-SEQUENCE-PROTOTYPE .

parse val(1) .
parse val(1) val(2) .
parse val(1) val(2) add .

quit
