fmod ASSOC-SORT-PROTOTYPE is
  protecting NAT .

  sorts Terminal Terminals EmptySeq Val Instr Vals Instrs .

  subsort Val < Instr .
  subsort Instr < Terminal .
  subsort Terminal < Terminals .

  subsort EmptySeq < Vals .
  subsort Val < Vals .
  subsort Vals < Instrs .
  subsort Instr < Instrs .
  subsort Instrs < Terminals .

  op eps : -> EmptySeq [ctor] .
  op __ : Terminals Terminals -> Terminals [ctor assoc id: eps] .
  op __ : Vals Vals -> Vals [ctor assoc id: eps] .
  op __ : Instrs Instrs -> Instrs [ctor assoc id: eps] .

  op val : Nat -> Val [ctor] .
  op instr : Nat -> Instr [ctor] .

  op classify : Terminals -> Nat .

  vars VS : Vals .
  vars IS REST : Instrs .

  eq classify(VS IS REST) = 1 .
endfm

red in ASSOC-SORT-PROTOTYPE : classify(val(1) val(2) instr(3) instr(4)) .
quit
