fmod SPECTEC-BUILTIN-TYPES is
  protecting SPEC2MAUDE-TYPES . --- in ../generated/typed.maude
  protecting CONVERSION * ( --- RAT, FLOAT, STRING, BOOL, NAT, INT
    op -_ : Float -> Float to nativeFloatNeg,
    op _+_ : Float Float -> Float to nativeFloatAdd,
    op _-_ : Float Float -> Float to nativeFloatSub,
    op _*_ : Float Float -> Float to nativeFloatMul,
    op _/_ : Float Float -> Float to nativeFloatDiv,
    op _rem_ : Float Float -> Float to floatRem,
    op _^_ : Float Float -> Float to nativeFloatPow,
    op abs : Float -> Float to floatAbs,
    op floor : Float -> Float to floatFloor,
    op ceiling : Float -> Float to floatCeiling,
    op min : Float Float -> Float to floatMin,
    op max : Float Float -> Float to floatMax,
    op _<_ : Float Float -> Bool to floatLess,
    op _<=_ : Float Float -> Bool to floatLessEqual,
    op _>_ : Float Float -> Bool to floatGreater,
    op _>=_ : Float Float -> Bool to floatGreaterEqual,
    op _xor_ : Nat Nat -> Nat to integerXor,
    op _+_ : String String -> String to stringConcat,
    op _<_ : String String -> Bool to stringLess,
    op _<=_ : String String -> Bool to stringLessEqual,
    op _>_ : String String -> Bool to stringGreater,
    op _>=_ : String String -> Bool to stringGreaterEqual,
    op char : Nat -> Char to nativeChar,
    op float : Rat -> Float to nativeToFloat,
    op rat : FiniteFloat -> Rat to nativeToRat,
    op float : String -> Float to nativeParseFloat,
    op rat : String NzNat -> Rat to nativeParseRat,
    op string : Float -> String to nativeFloatString,
    op string : Rat NzNat -> String to nativeRatString
  ) . --- Maude prelude에서 Float/String 등의 동일 이름 연산(ex: _+_)이 충돌하는 것을 피하기 위해 renaming


  protecting QID * ( --- for RECORD
    op _xor_ : Nat Nat -> Nat to integerXor,
    op _+_ : String String -> String to stringConcat,
    op _<_ : String String -> Bool to stringLess,
    op _<=_ : String String -> Bool to stringLessEqual,
    op _>_ : String String -> Bool to stringGreater,
    op _>=_ : String String -> Bool to stringGreaterEqual,
    op char : Nat -> Char to nativeChar
  ) .

  --- 기본 타입 (ast.ml line 28 & num.ml line 14)
  subsorts Bool Rat Float String < SpectecTerminal . 

  ops bool nat int rat real text : -> SpectecType [ctor] .
  ops iterOpt iterList : SpectecType -> SpectecType [ctor] .

  op typecheck : SpectecTerminals SpectecType -> Bool .

  var B : Bool .
  var N : Nat .
  var I : Int .
  var R : Rat .
  var F : Float .
  var S : String .
  eq typecheck(B, bool) = true .
  eq typecheck(N, nat) = true .
  eq typecheck(I, int) = true .
  eq typecheck(R, rat) = true .
  eq typecheck(F, real) = true .
  eq typecheck(S, text) = true .
endfm
