fmod DSL-RECORD is
  protecting DSL-SEQUENCE .
  protecting QID .

  sorts Record RecordItem RecordItems .
  subsort Record < SpectecTerminal .
  subsort RecordItem < RecordItems .

  op EMPTY : -> RecordItems [ctor] .
  op _;_ : RecordItems RecordItems -> RecordItems
    [ctor assoc id: EMPTY] .
  op item : Qid SpectecTerminals -> RecordItem [ctor] .
  op {_} : RecordItems -> Record [ctor] .

  op value : Qid Record -> SpectecTerminals .
  op value : Qid RecordItems -> SpectecTerminals .

  op _._ : Record Qid -> SpectecTerminals .
  op _++_ : Record Record -> Record .
  op _[._=_] : Record Qid SpectecTerminals -> Record .
  op _[._=++_] : Record Qid SpectecTerminals -> Record .

  op composeItems : RecordItems RecordItems -> RecordItems .
  op composeValues : SpectecTerminals SpectecTerminals -> SpectecTerminals .
  op setItem : RecordItems Qid SpectecTerminals -> RecordItems .

  vars FIELD OTHER : Qid .
  vars ITEMS ITEMS2 : RecordItems .
  vars VALUE NEW-VALUE : SpectecTerminals .
  var RECORD : Record .

  eq value(FIELD, {ITEMS}) = value(FIELD, ITEMS) .
  eq value(FIELD, EMPTY) = eps .
  eq value(FIELD, item(FIELD, VALUE) ; ITEMS) = VALUE .
  ceq value(FIELD, item(OTHER, VALUE) ; ITEMS) = value(FIELD, ITEMS)
    if FIELD =/= OTHER .

  eq RECORD . FIELD = value(FIELD, RECORD) .

  eq {ITEMS} ++ {ITEMS2} = {composeItems(ITEMS, ITEMS2)} .

  eq composeItems(EMPTY, EMPTY) = EMPTY .
  eq composeItems(item(FIELD, VALUE) ; ITEMS,
                  item(FIELD, NEW-VALUE) ; ITEMS2)
    = item(FIELD, composeValues(VALUE, NEW-VALUE))
      ; composeItems(ITEMS, ITEMS2) .

  eq composeValues({ITEMS}, {ITEMS2}) = {composeItems(ITEMS, ITEMS2)} .
  eq composeValues(VALUE, NEW-VALUE) = VALUE ++ NEW-VALUE [owise] .

  eq {ITEMS}[. FIELD = NEW-VALUE]
    = {setItem(ITEMS, FIELD, NEW-VALUE)} .

  eq setItem(EMPTY, FIELD, NEW-VALUE)
    = item(FIELD, NEW-VALUE) .
  eq setItem(item(FIELD, VALUE) ; ITEMS, FIELD, NEW-VALUE)
    = item(FIELD, NEW-VALUE) ; ITEMS .
  ceq setItem(item(OTHER, VALUE) ; ITEMS, FIELD, NEW-VALUE)
    = item(OTHER, VALUE) ; setItem(ITEMS, FIELD, NEW-VALUE)
    if FIELD =/= OTHER .

  eq RECORD[. FIELD =++ NEW-VALUE]
    = RECORD[. FIELD = value(FIELD, RECORD) ++ NEW-VALUE] .
endfm
