(* IterE and IterPr at their use: a call of a generated helper, or a
 * direct translation when no helper is needed (TRANSLATION_MAP.md,
 * section 6). The helpers themselves are generated by Iter_helpers. *)

open Util.Source
open Il.Ast
open Maude_il


let app name args = App (name, args)

let rec sequence = function
  | [] -> Const "eps"
  | [term] -> term
  | term :: terms -> app "_ _" [term; sequence terms]

let rec sequence_with representation = function
  | [] -> Const representation.Hintd.empty
  | [term] -> term
  | term :: terms ->
      app representation.concat [term; sequence_with representation terms]

let sequence_of_typ index typ terms =
  sequence_with (Prescan.sequence_representation index typ) terms

let empty_of_typ index typ =
  let representation = Prescan.sequence_representation index typ in
  Const representation.empty

let iterated_typ body iter =
  IterT (body.note, iter) $ body.note.at

(* IL nat and int values are native Maude Nat and Int terms; every other
 * value is a SpectecTerminal.  A native value enters a SpectecTerminal(s)
 * position as #_ V and leaves it through #rat (spectec-builtin-types.maude). *)
let native_sort sort = sort = "Nat" || sort = "Int"

let coerce ~actual ~expected term =
  match native_sort actual, native_sort expected, term with
  | true, false, _ -> app "#_" [term]
  | false, true, App ("#_", [value]) -> value  (* #rat(# V) = V *)
  | false, true, _ -> app "#rat" [term]
  | true, true, _ | false, false, _ -> term

let to_sort index ~sort typ term =
  coerce ~actual:(Prescan.sort_of_typ index typ) ~expected:sort term

let as_sequence_element index typ term =
  match
    Hintd.sequence_element_wrappers
      (Prescan.sort_metadata index) typ
  with
  | Some (box, _) -> app box [term]
  | None -> to_sort index ~sort:"SpectecTerminal" typ term


(* Type iteration *)

let length value = app "len" [value]

let length_of_typ index typ value =
  let representation = Prescan.sequence_representation index typ in
  app representation.size [value]

let typecheck value element_type =
  BoolCond (app "typecheck" [value; element_type])

let translate_conditions translate_count value element_type iter =
  let check = typecheck value element_type in
  match iter with
  | Opt ->
      [check; BoolCond (app "_<=_" [length value; Const "1"])]
  | List ->
      [check]
  | List1 ->
      [check; BoolCond (app "_<_" [Const "0"; length value])]
  | ListN (count, _) ->
      [check; EqCond (length value, translate_count count)]


(* Bound and captured variables *)

let translate_captures index captures =
  captures
  |> List.map (function
       | Prescan.VariableCapture (id, typ) ->
           Prescan.source_variable index id typ
       | Prescan.TypeCapture id ->
           Prescan.source_variable_with_sort index id "SpectecType")

let captures index body =
  match Prescan.iteration index body with
  | Some iteration -> iteration.Prescan.captures
  | None -> invalid_arg "IterE is missing from the prescan index"

let capture_variables index body =
  captures index body |> translate_captures index

let term_of_variable (variable : variable) =
  Var variable

let terms_of_variables variables =
  List.map term_of_variable variables

let capture_terms index body =
  capture_variables index body |> terms_of_variables


(* IterE terms *)

let source_iteration source =
  match source.note.it with
  | IterT (_, iter) -> Some iter
  | _ -> None

let rec identity_body_id index exp =
  match exp.it with
  | VarE id -> Some id
  | CaseE (mixop, payload) when Mixop.is_hole_only mixop ->
      begin match payload.it with
      | TupE [single] -> identity_body_id index single
      | _ -> identity_body_id index payload
      end
  | UncaseE (inner, mixop) when Mixop.is_hole_only mixop ->
      identity_body_id index inner
  | ProjE ({it = UncaseE (inner, mixop); _}, 0)
    when Mixop.is_hole_only mixop && Xl.Mixop.arity mixop = 1 ->
      identity_body_id index inner
  | SubE (inner, source, target)
    when Prescan.same_representation index source target ->
      identity_body_id index inner
  | IterE (inner, (iter, [(binder, source)])) ->
      begin match identity_body_id index inner, source.it,
                  source_iteration source with
      | Some inner_id, VarE source_id, Some source_iter
        when inner_id.it = binder.it && Il.Eq.eq_iter iter source_iter
             && Prescan.same_representation index source.note exp.note ->
          Some source_id
      | _ -> None
      end
  | _ -> None

let rec identity_requirements index exp =
  match exp.it with
  | SubE (inner, source, target)
    when Prescan.same_representation index source target ->
      source :: identity_requirements index inner
  | CaseE (mixop, payload) when Mixop.is_hole_only mixop ->
      begin match payload.it with
      | TupE [single] -> identity_requirements index single
      | _ -> identity_requirements index payload
      end
  | UncaseE (inner, mixop) when Mixop.is_hole_only mixop ->
      identity_requirements index inner
  | ProjE ({it = UncaseE (inner, mixop); _}, 0)
    when Mixop.is_hole_only mixop && Xl.Mixop.arity mixop = 1 ->
      identity_requirements index inner
  | IterE (inner, (iter, [_])) ->
      identity_requirements index inner
      |> List.map (fun typ -> IterT (typ, iter) $ typ.at)
  | VarE _ | BoolE _ | NumE _ | TextE _ | UnE _ | BinE _ | CmpE _
  | TupE _ | ProjE _ | CaseE _ | UncaseE _ | OptE _ | TheE _ | StrE _
  | DotE _ | CompE _ | ListE _ | LiftE _ | MemE _ | LenE _ | CatE _
  | IdxE _ | SliceE _ | UpdE _ | ExtE _ | IfE _ | CallE _ | IterE _
  | CvtE _ | SubE _ ->
      []

let identity_source index body (iter, generators) =
  match identity_body_id index body, generators with
  | Some body_id, [(generator_id, source)] ->
      begin match source_iteration source with
      | Some source_iter
        when body_id.it = generator_id.it
             && Il.Eq.eq_iter iter source_iter
             && Prescan.same_representation index source.note
                  (iterated_typ body iter) ->
          Some source
      | _ -> None
      end
  | _ -> None

let identity_requirement_guards index translate_conditions subject iter body =
  identity_requirements index body
  |> List.concat_map (fun typ ->
       translate_conditions subject (IterT (typ, iter) $ typ.at))

(* An IterE is translated to a call of a generated helper. The call is
 * recorded as a request, and only requested helpers are generated. *)
let request_helper index body kind =
  match Prescan.iteration index body with
  | Some iteration ->
      Prescan.request index iteration.Prescan.name kind;
      iteration
  | None -> invalid_arg "IterE is missing from the prescan index"

let controls translate_exp = function
  | Opt | List | List1 ->
      []
  | ListN (count, None) ->
      [translate_exp count]
  | ListN (count, Some _) ->
      [translate_exp count; Const "0"]

let translate_term index translate_exp body (iter, generators) =
  match identity_source index body (iter, generators) with
  | Some source -> translate_exp source
  | None ->
      match iter, generators with
      | ListN (count, None), [] ->
          let typ = iterated_typ body iter in
          let representation = Prescan.sequence_representation index typ in
          app representation.repeat
            [ translate_exp count
            ; translate_exp body |> as_sequence_element index body.note
            ]
      | (Opt | List | List1), [] ->
          invalid_arg "IterE with Opt, List, or List1 requires a generator"
      | ListN _, _ | (Opt | List | List1), _ :: _ ->
          let captures = capture_terms index body in
          let sources =
            List.map (fun (_, source) -> translate_exp source) generators
          in
          let helper = request_helper index body ForwardHelper in
          app helper.name (captures @ controls translate_exp iter @ sources)


(* IterE patterns: the variables of a sequence pattern are recovered by a
 * projector helper (Iter_helpers). *)

let generator_element (_, source) =
  match source.note.it with
  | IterT (element, _) -> element
  | _ -> invalid_arg "iteration generator must have an iteration type"

let source_head index generator head =
  term_of_variable head
  |> as_sequence_element index (generator_element generator)

let source_arguments index iter generators heads tails =
  match iter with
  | Opt ->
      List.map2
        (fun generator head -> app "_?" [source_head index generator head])
        generators heads
  | List | List1 | ListN _ ->
      List.map2
        (fun (generator, head) tail ->
          let _, source = generator in
          sequence_of_typ index source.note
            [source_head index generator head; term_of_variable tail])
        (List.combine generators heads) tails

let translate_identity_pattern index translate_pattern translate_conditions
    body (iter, generators) =
  match identity_source index body (iter, generators) with
  | None -> None
  | Some source ->
      begin match translate_pattern source with
      | None -> None
      | Some (term, guards) ->
          let cardinality_length = length_of_typ index source.note term in
          let requirement_guards =
            identity_requirement_guards index translate_conditions term iter body
          in
          let cardinality =
            match iter with
            | Opt ->
                Some [BoolCond (app "_<=_" [cardinality_length; Const "1"])]
            | List -> Some []
            | List1 ->
                Some [BoolCond (app "_<_" [Const "0"; cardinality_length])]
            | ListN (count, _) ->
                begin match translate_pattern count with
                | Some (count, count_guards) ->
                    Some (MatchCond (count, cardinality_length) :: count_guards)
                | None -> None
                end
          in
          Option.map
            (fun cardinality ->
              term, guards @ requirement_guards @ cardinality)
            cardinality
      end

let projector_local_bound captures iter =
  let bound =
    List.fold_left
      (fun bound -> function
        | Prescan.VariableCapture (id, _) -> Il.Free.Set.add id.it bound
        | Prescan.TypeCapture _ -> bound)
      Il.Free.Set.empty captures
  in
  let bound =
    match iter with
    | ListN (count, _) ->
        Il.Free.Set.union bound Il.Free.(free_exp count).varid
    | Opt | List | List1 -> bound
  in
  match iter with
  | ListN (_, Some id) -> Il.Free.Set.add id.it bound
  | Opt | List | List1 | ListN (_, None) -> bound

let projector_supported index translate_pattern can_bind_body bound body iterexp =
  let _, generators = iterexp in
  generators <> []
  && identity_source index body iterexp = None
  && (Option.is_some (translate_pattern body) || can_bind_body bound body)
  && List.for_all
       (fun (id, _) -> Il.Free.Set.mem id.it Il.Free.(free_exp body).varid)
       generators

let column_term index generators columns =
  match generators, columns with
  | [_], [column] -> column
  | _, _ ->
      List.map2
        (fun (_, source) column ->
          as_sequence_element index source.note column)
        generators columns
      |> sequence
      |> fun columns -> app "tuple" [columns]

let rec translate_source_patterns translate_pattern = function
  | [] -> Some ([], [])
  | (_, source) :: generators ->
      begin match
        translate_pattern source,
        translate_source_patterns translate_pattern generators
      with
      | Some (term, guards), Some (terms, remaining_guards) ->
          Some (term :: terms, guards @ remaining_guards)
      | None, _ | _, None -> None
      end

let pattern_count index typ translate_pattern translate_exp known subject = function
  | ListN (count, _) when known count ->
      Some (translate_exp count, [])
  | ListN (({it = VarE _; _} as count), _) ->
      translate_pattern count
      |> Option.map (fun (pattern, guards) ->
           let size = length_of_typ index typ subject in
           pattern, MatchCond (pattern, size) :: guards)
  | ListN _ -> None
  | Opt | List | List1 -> Some (Const "0", [])

let identity_cardinality index typ translate_exp known subject = function
  | Opt ->
      [BoolCond
         (app "_<=_" [length_of_typ index typ subject; Const "1"])]
  | List -> []
  | List1 ->
      [BoolCond
         (app "_<_" [Const "0"; length_of_typ index typ subject])]
  | ListN (count, _) when known count ->
      [EqCond (length_of_typ index typ subject, translate_exp count)]
  | ListN _ -> []

let translate_pattern index translate_source_pattern translate_exp
    translate_conditions known is_bound can_bind_body body (iter, generators)
    subject =
  let result_typ = iterated_typ body iter in
  let captures = captures index body in
  let count_variables =
    match iter with
    | ListN (count, _) when not (known count) ->
        Il.Free.(free_exp count).varid
    | Opt | List | List1 | ListN _ -> Il.Free.Set.empty
  in
  let captures_ready () =
    List.for_all
      (function
        | Prescan.VariableCapture (id, _) ->
            is_bound id.it || Il.Free.Set.mem id.it count_variables
        | Prescan.TypeCapture _ -> true)
      captures
  in
  match
    translate_source_patterns translate_source_pattern generators
  with
  | None -> None
  | Some (source_patterns, source_guards) ->
      begin match
        identity_source index body (iter, generators), source_patterns
      with
      | Some source, [source_pattern] ->
          begin match pattern_count index source.note translate_source_pattern
                        translate_exp known subject iter with
          | None -> None
          | Some (_, count_conditions) ->
              if not (captures_ready ()) then
                invalid_arg "IterE pattern has an unbound capture";
              let value =
                match source_pattern with
                | Var _ -> source_pattern
                | Const _ | App _ -> subject
              in
              Some
                ( count_conditions
                  @ (MatchCond (source_pattern, subject) :: source_guards)
                  @ identity_requirement_guards index translate_conditions
                      value iter body
                  @ identity_cardinality index source.note translate_exp known
                      value iter)
          end
      | None, _ when
          projector_supported index translate_source_pattern can_bind_body
            (projector_local_bound captures iter)
            body (iter, generators) ->
          begin match pattern_count index result_typ translate_source_pattern
                        translate_exp known subject iter with
          | None -> None
          | Some (count, count_conditions) ->
              if not (captures_ready ()) then
                invalid_arg "IterE pattern has an unbound capture";
              let captures = capture_terms index body in
              let controls =
                match iter with
                | Opt | List | List1 -> []
                | ListN (_, None) -> [count]
                | ListN (_, Some _) -> [count; Const "0"]
              in
              let projected =
                let helper = request_helper index body ProjectorHelper in
                app helper.projector_name (captures @ controls @ [subject])
              in
              (* The projector checks each body; matching its columns retains
               * the generator constraints without rebuilding the subject. *)
              Some
                ( count_conditions
                  @ (MatchCond
                       (column_term index generators source_patterns, projected)
                     :: source_guards))
          end
      | Some _, _ | None, _ -> None
      end

(* Premise iteration *)

let premise_helper_name iteration = iteration.Prescan.name

let premise_output_name iteration position =
  fst (List.nth iteration.Prescan.output_names position)

let premise_output_possible iteration position =
  let iter, generators = iteration.Prescan.iterexp in
  position >= 0 && position < List.length generators
  && match iter with ListN _ -> true | _ -> List.length generators > 1

let premise_helper_call index translate_exp iteration =
  Prescan.request index iteration.Prescan.name CheckHelper;
  let iter, generators = iteration.Prescan.iterexp in
  let captures =
    translate_captures index iteration.Prescan.captures
    |> terms_of_variables
  in
  let sources = List.map (fun (_, source) -> translate_exp source) generators in
  app (premise_helper_name iteration)
    (captures @ controls translate_exp iter @ sources)

let premise_output_call index translate_exp iteration position =
  let iter, generators = iteration.Prescan.iterexp in
  let captures =
    translate_captures index iteration.Prescan.captures
    |> terms_of_variables
  in
  let sources =
    generators |> Prescan.remove_at position
    |> List.map (fun (_, source) -> translate_exp source)
  in
  app (premise_output_name iteration position)
    (captures @ controls translate_exp iter @ sources)

let translate_premise index translate_exp premise =
  match Prescan.premise_iteration index premise with
  | Some iteration ->
      let call =
        premise_helper_call index translate_exp iteration
      in
      [EqCondition (BoolCond call)]
  | None -> invalid_arg "IterPr is missing from the prescan index"
